window.AUGGIE_COMICS = window.AUGGIE_COMICS || [];
window.AUGGIE_COMICS.push(

  // ===================== AUGGIE AND SPACE =====================

  // 135 — A rocket made of a cardboard box
  {
    id: 135, age: "4-6", category: "space",
    title: { en: "Auggie's Cardboard Rocket", hi: "ऑगी का डिब्बा-रॉकेट" },
    blurb: { en: "A giant empty box, a shy friend and one big dream. Can a cardboard rocket really reach the stars?", hi: "एक बड़ा-सा खाली डिब्बा, एक शर्मीला दोस्त और एक बड़ा सपना। क्या गत्ते का रॉकेट सच में तारों तक पहुँचेगा?" },
    moral: { en: "With a friend and a big imagination, even a box can reach the stars.", hi: "दोस्त साथ हो और सोच बड़ी हो, तो एक डिब्बा भी तारों तक पहुँच जाता है।" },
    cover: { bg: "bedroom", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.33 }, { id: "kabir", pose: "cheer", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "rocket", x: 0.1 }, { id: "telescope", x: 0.52 }, { id: "star", x: 0.88, y: 0.12 } ], fx: { en: "BLAST OFF!", hi: "उड़ चले!" } },
    panels: [
      { bg: "home", chars: [ { id: "auggie", pose: "point", mood: "happy", x: 0.3 }, { id: "kabir", pose: "stand", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "laptop", x: 0.52 } ],
        cap: { en: "Papa's new laptop came in a GIANT box.", hi: "पापा का नया लैपटॉप आया... एक बहुत बड़े डिब्बे में!" },
        say: [ { who: 0, en: "A giant box! Perfect for a giant nap!", hi: "इतना बड़ा डिब्बा! इसमें तो बड़ी वाली झपकी बनती है!" },
               { who: 1, en: "No, Auggie... let's make a ROCKET!", hi: "ऊँहूँ ऑगी... चलो, इसका रॉकेट बनाते हैं!", kind: "whisper" } ] },
      { bg: "home", chars: [ { id: "kabir", pose: "stand", mood: "laugh", x: 0.28 }, { id: "auggie", pose: "cheer", mood: "laugh", x: 0.7, flip: true } ], props: [ { id: "rocket", x: 0.5 } ],
        cap: { en: "Kabir paints the rocket. Auggie helps... with his tail!", hi: "कबीर रॉकेट रंग रहा है। ऑगी भी हाथ बँटा रहा है... मतलब, पूँछ बँटा रहा है!" },
        say: [ { who: 0, en: "Auggie! Your tail painted my nose BLUE!", hi: "ऑगी! तुम्हारी पूँछ ने मेरी नाक नीली कर दी!" } ],
        fx: { en: "SWISH!", hi: "सर्र!" }, action: true },
      { bg: "home", chars: [ { id: "auggie", pose: "sit", mood: "determined", x: 0.3 }, { id: "kabir", pose: "cheer", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "rocket", x: 0.1 }, { id: "star", x: 0.9, y: 0.15 } ],
        cap: { en: "Mission Stars! Captain Auggie does the countdown.", hi: "मिशन तारे! कैप्टन ऑगी उल्टी गिनती गिन रहा है।" },
        say: [ { who: 0, en: "Ten, nine, carrot, eight... um... carrot... ONE!", hi: "दस, नौ, गाजर, आठ... उम्म... गाजर... एक!" },
               { who: 1, en: "Carrot isn't a number! BLAST OFF!", hi: "गाजर कोई गिनती है क्या! चलो, उड़ो!", kind: "shout" } ] },
      { bg: "home", chars: [ { id: "auggie", pose: "lie", mood: "sad", x: 0.35 }, { id: "kabir", pose: "stand", mood: "sad", x: 0.75, flip: true } ], props: [ { id: "rocket", x: 0.12 } ],
        cap: { en: "Nothing happens. Then the box goes... CRUNCH.", hi: "कुछ नहीं हुआ। उल्टा डिब्बा ही पिचक गया!" },
        say: [ { who: 0, en: "Not even one carrot high. And I wagged SO hard!", hi: "एक गाजर जितना भी नहीं उड़े! और मैंने कितनी ज़ोर से पूँछ घुमाई थी!" } ],
        fx: { en: "CRUNCH!", hi: "चर्र-मर्र!" }, action: true },
      { bg: "home", chars: [ { id: "auggie", pose: "point", mood: "happy", x: 0.3 }, { id: "nanu", pose: "point", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "telescope", x: 0.52 } ],
        say: [ { who: 1, en: "Earth pulls us down. Only giant rocket engines break free!", hi: "धरती सबको नीचे खींचती है, बेटा। उससे छूटने को बड़े-बड़े इंजन लगते हैं!" },
               { who: 0, en: "Wait! Nanu's telescope makes far stars look close!", hi: "रुको! नानू की दूरबीन से तो दूर वाले तारे भी पास दिखते हैं!" } ] },
      { bg: "bedroom", chars: [ { id: "kabir", pose: "stand", mood: "surprised", x: 0.25 }, { id: "auggie", pose: "sit", mood: "happy", x: 0.7, flip: true } ], props: [ { id: "telescope", x: 0.08 }, { id: "rocket", x: 0.92 }, { id: "star", x: 0.45, y: 0.12 } ],
        cap: { en: "That night, the box rocket reached the stars... through Nanu's telescope!", hi: "उस रात डिब्बा-रॉकेट तारों तक पहुँच ही गया... नानू की दूरबीन के रास्ते!" },
        say: [ { who: 1, en: "Kabir first! Good captains share. Then... rocket nap!", hi: "पहले कबीर! अच्छे कैप्टन बाँटते हैं। उसके बाद... रॉकेट में झपकी!" },
               { who: 0, en: "Wow! A star is winking at me, Auggie!", hi: "अरे वाह! ऑगी, एक तारा मुझे आँख मार रहा है!" } ],
        fx: { en: "WOW!", hi: "वाह!" }, action: true }
    ]
  },

  // 136 — Who switched off the stars? (city lights vs the village sky)
  {
    id: 136, age: "4-6", category: "space",
    title: { en: "Who Switched Off the Stars?", hi: "तारे किसने बुझा दिए?" },
    blurb: { en: "Only three stars above Chamakpur tonight! Did somebody switch the rest off? Detective Auggie is on the case.", hi: "आज चमकपुर के आसमान में बस तीन तारे! बाक़ी किसने बंद कर दिए? जासूस ऑगी पता लगाकर रहेगा!" },
    moral: { en: "Stars never go away; turn off extra lights and they come out to play.", hi: "तारे कहीं नहीं जाते; फ़ालतू बत्तियाँ बुझाओ, तो वो खेलने निकल आते हैं।" },
    cover: { bg: "nightsky", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.35 }, { id: "nanu", pose: "point", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "star", x: 0.15, y: 0.15 }, { id: "star", x: 0.55, y: 0.1 }, { id: "telescope", x: 0.92 } ], fx: { en: "WOW!", hi: "वाह!" } },
    panels: [
      { bg: "bedroom", chars: [ { id: "auggie", pose: "sit", mood: "sad", x: 0.3 }, { id: "nanu", pose: "stand", mood: "laugh", x: 0.72, flip: true } ],
        cap: { en: "Night in Chamakpur. Auggie wants to count the stars.", hi: "चमकपुर की रात। ऑगी को तारे गिनने हैं।" },
        say: [ { who: 0, en: "One, two, three... Who switched off the other stars?", hi: "एक, दो, तीन... बस? बाक़ी तारे किसने बुझा दिए?" },
               { who: 1, en: "A star mystery! Find the switch, Detective Auggie!", hi: "वाह, तारों का रहस्य! जासूस ऑगी, स्विच ढूँढो तो!" } ] },
      { bg: "bedroom", chars: [ { id: "auggie", pose: "cheer", mood: "determined", x: 0.3 }, { id: "papa", pose: "sit", mood: "surprised", x: 0.72, flip: true } ], props: [ { id: "laptop", x: 0.9 } ],
        cap: { en: "Auggie's plan: switch OFF every light in the house!", hi: "ऑगी का प्लान: घर की हर बत्ती बंद!" },
        say: [ { who: 1, en: "Hey! Lights off? I was typing a GREAT joke!", hi: "अरे! बत्ती किसने बुझाई? मैं एक चुटकुला लिख रहा था!" },
               { who: 0, en: "Shh, Papa! Stars are shy. They need the dark!", hi: "श्श्श पापा! तारे शर्मीले होते हैं। उन्हें अँधेरा चाहिए!", kind: "whisper" } ],
        fx: { en: "CLICK!", hi: "खट्!" }, action: true },
      { bg: "bedroom", chars: [ { id: "auggie", pose: "think", mood: "surprised", x: 0.3 }, { id: "nanu", pose: "point", mood: "happy", x: 0.72, flip: true } ],
        say: [ { who: 0, en: "Still three stars! Is the whole CITY too shiny?", hi: "अब भी तीन ही! कहीं पूरा शहर ही तो ज़्यादा नहीं चमक रहा?" },
               { who: 1, en: "Yes! City lights make the sky too bright for stars.", hi: "बिल्कुल! शहर की बत्तियों की चमक में तारे छुप जाते हैं।" } ] },
      { bg: "village", chars: [ { id: "auggie", pose: "cheer", mood: "determined", x: 0.3 }, { id: "cow", pose: "stand", mood: "laugh", x: 0.72, flip: true } ],
        cap: { en: "On Saturday, Nanu takes Auggie to a village far from city lights.", hi: "शनिवार को नानू ऑगी को शहर की बत्तियों से दूर एक गाँव ले गए।" },
        say: [ { who: 0, en: "Is it night yet? Now? NOW?", hi: "रात हुई? अब? अब हुई?" },
               { who: 1, en: "Patience, city dog! This night is worth the wait.", hi: "सब्र करो, शहरी बाबू! यहाँ की रात इंतज़ार के लायक़ है।" } ] },
      { bg: "nightsky", chars: [ { id: "auggie", pose: "cheer", mood: "surprised", x: 0.3 }, { id: "nanu", pose: "point", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "star", x: 0.15, y: 0.12 }, { id: "star", x: 0.5, y: 0.08 } ],
        cap: { en: "Night falls. No streetlights. And the sky is FULL of stars!", hi: "रात हुई। न बत्तियाँ, न चमक... और आसमान तारों से भरा पड़ा है!" },
        say: [ { who: 0, en: "Somebody switched ALL the stars back on!", hi: "किसी ने सारे तारे वापस जला दिए!", kind: "shout" },
               { who: 1, en: "They were always there, hiding behind the city lights.", hi: "वो तो हमेशा यहीं थे, बेटा। बस शहर की चमक में छुपे थे।" } ],
        fx: { en: "WOW!", hi: "वाह!" }, action: true },
      { bg: "nightsky", chars: [ { id: "auggie", pose: "lie", mood: "sleepy", x: 0.3 }, { id: "nanu", pose: "sit", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "star", x: 0.5, y: 0.1 } ],
        cap: { en: "Auggie counts the stars in carrots... and falls asleep at ninety-nine.", hi: "ऑगी तारे गाजरों में गिनता रहा... और निन्यानवे पर खर्राटे!" },
        say: [ { who: 1, en: "Keep counting! On a dark night, we can see thousands!", hi: "गिनते रहो! अँधेरी रात में तो हज़ारों तारे दिखते हैं!" },
               { who: 0, en: "Back home... let's switch off lights we don't need...", hi: "घर जाकर... फ़ालतू बत्तियाँ बुझाएँगे... ताकि तारे झाँक सकें...", kind: "whisper" } ],
        fx: { en: "SNORE!", hi: "खर्र!" }, action: true }
    ]
  },

  // 137 — The space station where things float (a dream)
  {
    id: 137, age: "4-6", category: "space",
    title: { en: "The Carrot That Floated Away", hi: "उड़ गई ऑगी की गाजर!" },
    blurb: { en: "On the space station everything floats... even Auggie's lunch! Can he catch his runaway carrot?", hi: "स्पेस स्टेशन पर सब कुछ तैरता है... ऑगी का खाना भी! क्या वो अपनी भागती गाजर पकड़ पाएगा?" },
    moral: { en: "Keep your things in their place, on Earth and in space!", hi: "अपनी चीज़ें सही जगह रखो, धरती पर भी और अंतरिक्ष में भी!" },
    cover: { bg: "space", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.35 }, { id: "zibbo", pose: "wave", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "star", x: 0.12, y: 0.2 }, { id: "planet", x: 0.55, y: 0.12 } ], fx: { en: "WHEE!", hi: "ऊऊऊ!" } },
    panels: [
      { bg: "bedroom", chars: [ { id: "auggie", pose: "lie", mood: "sleepy", x: 0.3 }, { id: "nanu", pose: "sit", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "book", x: 0.52 } ],
        cap: { en: "Nanu reads about astronauts. That night, Auggie dreamed...", hi: "नानू अंतरिक्ष यात्रियों की किताब पढ़ रहे हैं। उस रात ऑगी ने सपना देखा..." },
        say: [ { who: 1, en: "On the space station, everything floats!", hi: "स्पेस स्टेशन पर हर चीज़ तैरती रहती है!" },
               { who: 0, en: "Everything? Even... carrots?", hi: "सब कुछ? गाजर भी...?", kind: "whisper" } ] },
      { bg: "space", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "zibbo", pose: "wave", mood: "happy", x: 0.72, flip: true } ],
        cap: { en: "...he was an astronaut on the space station, high above Earth!", hi: "...कि वो धरती से बहुत ऊपर, स्पेस स्टेशन पर अंतरिक्ष यात्री है!" },
        say: [ { who: 0, en: "Wheee! I'm floating like a balloon!", hi: "ऊऊऊ! मैं तो गुब्बारे जैसा तैर रहा हूँ!", kind: "shout" },
               { who: 1, en: "Zeep! Welcome aboard! Lunch time?", hi: "ज़ीप! स्वागत है! कुछ खाओगे?" } ],
        fx: { en: "WHEE!", hi: "ऊऊऊ!" }, action: true },
      { bg: "space", chars: [ { id: "auggie", pose: "stand", mood: "surprised", x: 0.3 }, { id: "zibbo", pose: "point", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "carrot", x: 0.52, y: 0.42 } ],
        cap: { en: "Auggie opens his tiffin. His carrot floats right out!", hi: "ऑगी ने टिफ़िन खोला... और गाजर फुर्र से बाहर तैर गई!" },
        say: [ { who: 0, en: "My carrot! Come back! SIT! STAY!", hi: "मेरी गाजर! वापस आओ! बैठो! रुको!", kind: "shout" },
               { who: 1, en: "Ha! Carrots don't know 'sit'!", hi: "हा हा! गाजर 'बैठो' नहीं समझती!" } ] },
      { bg: "space", chars: [ { id: "auggie", pose: "lie", mood: "surprised", x: 0.35 }, { id: "zibbo", pose: "stand", mood: "laugh", x: 0.75, flip: true } ],
        cap: { en: "Auggie doggy-paddles after it... and spins upside down!", hi: "ऑगी गाजर के पीछे तैरने लगा... और उल्टा घूम गया!" },
        say: [ { who: 0, en: "Paddling works in the lake... not in space!", hi: "पानी में तो मैं मस्त तैरता हूँ... यहाँ तो लट्टू बन गया!" } ],
        fx: { en: "WHIRL!", hi: "गोल-गोल!" }, action: true },
      { bg: "space", chars: [ { id: "auggie", pose: "think", mood: "determined", x: 0.3 }, { id: "zibbo", pose: "point", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "carrot", x: 0.46, y: 0.5 } ],
        cap: { en: "Auggie stops chasing. The carrot drifts slowly back... right into his mouth!", hi: "ऑगी ने भागना छोड़ा। गाजर धीरे-धीरे लौटी... सीधे उसके मुँह में!" },
        say: [ { who: 0, en: "No chasing. Just sniff... wait... open wide!", hi: "भागना बंद। बस सूँघो... रुको... मुँह खोलो!", kind: "think" },
               { who: 1, en: "Zeep! Up here, we stick things down with sticky strips!", hi: "ज़ीप! यहाँ हम हर चीज़ चिपकने वाली पट्टी से चिपकाकर रखते हैं!" } ],
        fx: { en: "CHOMP!", hi: "कट्ट!" }, action: true },
      { bg: "bedroom", chars: [ { id: "auggie", pose: "lie", mood: "happy", x: 0.3 }, { id: "mumma", pose: "sit", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "bowl", x: 0.52 } ],
        cap: { en: "Morning! Auggie puts his carrot safely in his bowl.", hi: "सुबह! ऑगी ने अपनी गाजर सँभालकर कटोरे में रख दी।" },
        say: [ { who: 1, en: "Why is my astronaut hugging his bowl?", hi: "मेरा अंतरिक्ष यात्री कटोरे से क्यों चिपका है?" },
               { who: 0, en: "Things float away if you don't keep them in place!", hi: "चीज़ें जगह पर न रखो, तो तैरकर भाग जाती हैं!" } ] }
    ]
  },

  // 138 — A comet with a tail like Auggie's
  {
    id: 138, age: "6-10", category: "space",
    title: { en: "The Comet With Auggie's Tail", hi: "पुच्छल तारा और ऑगी की पूँछ" },
    blurb: { en: "A comet with a glowing tail is visiting! But it only shows up before sunrise, and Auggie never, ever wakes up early.", hi: "चमकती पूँछ वाला पुच्छल तारा आया है! पर वो दिखेगा सिर्फ़ सुबह-सुबह... और ऑगी तो सुबह उठता ही नहीं!" },
    moral: { en: "Some wonderful things only come to those who wait patiently.", hi: "कुछ कमाल की चीज़ें उन्हीं को दिखती हैं, जो सब्र से इंतज़ार करते हैं।" },
    cover: { bg: "nightsky", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "nanu", pose: "point", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "star", x: 0.5, y: 0.12 }, { id: "telescope", x: 0.92 } ], fx: { en: "WHOOSH!", hi: "सर्र्र!" } },
    panels: [
      { bg: "home", chars: [ { id: "auggie", pose: "lie", mood: "surprised", x: 0.3 }, { id: "nanu", pose: "sit", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "book", x: 0.9 } ],
        cap: { en: "Big news in Chamakpur: a comet is visiting our sky this week!", hi: "चमकपुर में बड़ी ख़बर: इस हफ़्ते आसमान में एक पुच्छल तारा आया है!" },
        say: [ { who: 1, en: "It's best seen just before sunrise, Auggie. Around five o'clock!", hi: "सबसे अच्छा दिखेगा सूरज निकलने से ठीक पहले, ऑगी। सुबह पाँच बजे!" },
               { who: 0, en: "Five? That's the middle of my deepest nap!", hi: "पाँच बजे? उस वक़्त तो मेरी सबसे गहरी नींद चल रही होती है!" } ] },
      { bg: "home", chars: [ { id: "auggie", pose: "cheer", mood: "happy", x: 0.3 }, { id: "nanu", pose: "point", mood: "happy", x: 0.72, flip: true } ],
        say: [ { who: 1, en: "A comet is a giant dirty snowball. Near the Sun, it grows a glowing tail!", hi: "धूमकेतु बर्फ़ और धूल का बड़ा-सा मैला गोला है। सूरज के पास आकर उसकी चमकती पूँछ निकल आती है!" },
               { who: 0, en: "A tail? Pfft. Nobody has a better tail than me!", hi: "पूँछ? हुँह! मेरी पूँछ से बढ़िया पूँछ किसी की नहीं!" } ] },
      { bg: "bedroom", chars: [ { id: "auggie", pose: "lie", mood: "sleepy", x: 0.3 }, { id: "mausi", pose: "stand", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "clock", x: 0.52 }, { id: "camera", x: 0.92 } ],
        cap: { en: "4:30 in the morning. Mausi is ready. Auggie is... not.", hi: "सुबह के साढ़े चार। मौसी तैयार। ऑगी... बिल्कुल नहीं।" },
        say: [ { who: 1, en: "Wake up! Comet selfie! Hold that pose!", hi: "उठो ऑगी! धूमकेतु के साथ सेल्फ़ी! पोज़ पकड़ो!", kind: "shout" },
               { who: 0, en: "Tell the comet to come to MY bed.", hi: "धूमकेतु से कहो, मेरे बिस्तर पर आकर मिल ले।", kind: "whisper" } ],
        fx: { en: "TRRING!", hi: "ट्रिन-ट्रिन!" }, action: true },
      { bg: "nightsky", chars: [ { id: "auggie", pose: "sit", mood: "sad", x: 0.3 }, { id: "nanu", pose: "stand", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "cloud", x: 0.3, y: 0.15 }, { id: "cloud", x: 0.7, y: 0.18 } ],
        cap: { en: "Up on Nanu's roof... thick clouds cover the whole sky.", hi: "नानू की छत पर... पूरे आसमान पर घने बादल छाए हैं।" },
        say: [ { who: 0, en: "Clouds! Even the comet is sleeping in. Can I go back to bed?", hi: "बादल! धूमकेतु भी सो रहा है। मैं भी वापस सो जाऊँ?" },
               { who: 1, en: "Sky-watchers need patience. Clouds move, Auggie. Let's wait.", hi: "आसमान देखने वालों को सब्र चाहिए, बेटा। बादल तो चलते रहते हैं।" } ] },
      { bg: "nightsky", chars: [ { id: "auggie", pose: "blast", mood: "determined", x: 0.35 }, { id: "mausi", pose: "stand", mood: "laugh", x: 0.75, flip: true } ], props: [ { id: "cloud", x: 0.5, y: 0.15 } ],
        say: [ { who: 0, en: "Hey, clouds! Shoo! Move it! Comet coming through!", hi: "ऐ बादलो! हटो! चलो-चलो! धूमकेतु को रास्ता दो!", kind: "shout" },
               { who: 1, en: "Clouds didn't budge... but the whole lane just woke up!", hi: "बादल तो टस से मस नहीं हुए... पर पूरी गली जाग गई!" } ],
        fx: { en: "WOOF!", hi: "भौं-भौं!" }, action: true },
      { bg: "nightsky", chars: [ { id: "auggie", pose: "sit", mood: "determined", x: 0.3 }, { id: "nanu", pose: "sit", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "cloud", x: 0.5, y: 0.12 } ],
        cap: { en: "Slowly, quietly, the clouds begin to drift apart...", hi: "धीरे-धीरे, चुपचाप, बादल खिसकने लगे..." },
        say: [ { who: 0, en: "Okay. No barking. I'll wait quietly... like a very patient carrot.", hi: "ठीक है। भौंकना बंद। मैं चुपचाप इंतज़ार करूँगा... एकदम सब्र वाली गाजर की तरह।" },
               { who: 1, en: "Good! Some comets visit only once in a lifetime. Worth a little wait.", hi: "शाबाश! कुछ धूमकेतु तो ज़िंदगी में एक ही बार आते हैं। थोड़ा रुकना बनता है।" } ] },
      { bg: "nightsky", chars: [ { id: "auggie", pose: "cheer", mood: "surprised", x: 0.3 }, { id: "nanu", pose: "point", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "star", x: 0.5, y: 0.12 }, { id: "telescope", x: 0.92 } ],
        cap: { en: "And there it is! A fuzzy glowing ball with a long, shining tail!", hi: "और वो रहा! एक धुँधला चमकता गोला, पीछे लंबी चमचमाती पूँछ!" },
        say: [ { who: 0, en: "Nanu! It has a tail like mine... but it doesn't wag!", hi: "नानू! इसकी पूँछ तो मेरी जैसी है... पर ये हिलती क्यों नहीं?" },
               { who: 1, en: "The Sun's wind blows it. A comet's tail always points away from the Sun!", hi: "सूरज की हवा उसे धकेलती है। धूमकेतु की पूँछ हमेशा सूरज से उल्टी तरफ़ रहती है!" } ],
        fx: { en: "WOW!", hi: "वाह!" }, action: true },
      { bg: "home", chars: [ { id: "mausi", pose: "stand", mood: "laugh", x: 0.2 }, { id: "auggie", pose: "lie", mood: "happy", x: 0.5 }, { id: "nanu", pose: "sit", mood: "laugh", x: 0.8, flip: true } ], props: [ { id: "camera", x: 0.35, y: 0.3 } ],
        say: [ { who: 0, en: "Best selfie ever! One sky, two tails!", hi: "अब तक की सबसे बढ़िया सेल्फ़ी! एक आसमान, दो पूँछें!" },
               { who: 1, en: "I almost slept through it. Waiting was worth it. Now... comet-sized nap!", hi: "मैं तो सोता ही रह जाता! इंतज़ार का फल मीठा निकला। अब... धूमकेतु जितनी लंबी झपकी!" } ] }
    ]
  },

  // 139 — The space dog who wants to come home (a dream)
  {
    id: 139, age: "6-10", category: "space",
    title: { en: "Pinku, the Homesick Space Pug", hi: "अंतरिक्ष में पिंकू को घर की याद" },
    blurb: { en: "Pinku says Earth is boring and he's moving to space forever. His 'forever' lasts about five seconds.", hi: "पिंकू कहता है धरती बोरिंग है, वो हमेशा के लिए अंतरिक्ष जा रहा है। पर उसका 'हमेशा' बस पाँच सेकंड चलता है!" },
    moral: { en: "Missing home is not silly; it means home is full of love.", hi: "घर की याद आना बचपना नहीं; इसका मतलब है घर प्यार से भरा है।" },
    cover: { bg: "space", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.22 }, { id: "pinku", pose: "stand", mood: "surprised", x: 0.5 }, { id: "zibbo", pose: "wave", mood: "happy", x: 0.78, flip: true } ], props: [ { id: "ufo", x: 0.5, y: 0.15 }, { id: "planet", x: 0.1, y: 0.15 } ], fx: { en: "ZOOM!", hi: "ज़ूम!" } },
    panels: [
      { bg: "bedroom", chars: [ { id: "auggie", pose: "lie", mood: "sleepy", x: 0.3 }, { id: "pinku", pose: "sit", mood: "determined", x: 0.72, flip: true } ],
        cap: { en: "Pinku is sleeping over, feeling dramatic. That night, Auggie dreamed...", hi: "पिंकू ऑगी के घर रुका है, पूरे फ़िल्मी मूड में। उस रात ऑगी ने सपना देखा..." },
        say: [ { who: 1, en: "Earth is SO boring. Tomorrow I'm moving to space. Forever!", hi: "धरती कितनी बोरिंग है! कल से मैं अंतरिक्ष में रहूँगा। हमेशा के लिए!" },
               { who: 0, en: "Take carrots. Space has no carrot shops... zzz.", hi: "गाजर ले जाना। वहाँ गाजर की दुकान नहीं है... खर्र...", kind: "whisper" } ] },
      { bg: "space", chars: [ { id: "auggie", pose: "stand", mood: "surprised", x: 0.22 }, { id: "pinku", pose: "cheer", mood: "laugh", x: 0.5 }, { id: "zibbo", pose: "point", mood: "laugh", x: 0.8, flip: true } ], props: [ { id: "rocket", x: 0.06 } ],
        cap: { en: "...he and Zibbo found a tiny astronaut floating near a rocket. It was Pinku!", hi: "...कि ज़िब्बो के साथ घूमते हुए उसे रॉकेट के पास एक नन्हा अंतरिक्ष यात्री दिखा। अरे, ये तो पिंकू है!" },
        say: [ { who: 1, en: "Behold! Pinku, the first pug in space! I'm NEVER going home!", hi: "देखो, देखो! पिंकू, अंतरिक्ष में पहला पग! मैं कभी घर नहीं जाऊँगा!", kind: "shout" },
               { who: 2, en: "Zeep! Then why is your helmet all steamy?", hi: "ज़ीप! तो फिर तुम्हारा हेलमेट अंदर से भाप-भाप क्यों है?" } ] },
      { bg: "space", chars: [ { id: "zibbo", pose: "point", mood: "happy", x: 0.22 }, { id: "auggie", pose: "stand", mood: "happy", x: 0.5 }, { id: "pinku", pose: "stand", mood: "sad", x: 0.8, flip: true } ], props: [ { id: "planet", x: 0.5, y: 0.15 } ],
        say: [ { who: 0, en: "That blue marble is Earth. It's blue because oceans cover most of it!", hi: "वो नीला कंचा तुम्हारी धरती है। नीली इसलिए, क्योंकि उसका ज़्यादातर हिस्सा समुद्र है!" },
               { who: 1, en: "Somewhere down there is my bed... and my bowl... and Mumma.", hi: "वहीं कहीं नीचे मेरा बिस्तर है... मेरा कटोरा... और मम्मा।" } ] },
      { bg: "space", chars: [ { id: "pinku", pose: "lie", mood: "sad", x: 0.3 }, { id: "auggie", pose: "stand", mood: "surprised", x: 0.72, flip: true } ],
        say: [ { who: 0, en: "WAAAH! I miss my cushion! I miss belly rubs! I want to go HOME!", hi: "ऊँ-ऊँ! मुझे मेरी गद्दी चाहिए! पेट-खुजाई चाहिए! मुझे घर जाना है!", kind: "shout" },
               { who: 1, en: "But you said 'never' five seconds ago!", hi: "पर तुमने तो अभी पाँच सेकंड पहले 'कभी नहीं' बोला था!" } ],
        fx: { en: "WAAAH!", hi: "ऊँ-ऊँ!" }, action: true },
      { bg: "space", chars: [ { id: "pinku", pose: "sit", mood: "sad", x: 0.3 }, { id: "auggie", pose: "sit", mood: "happy", x: 0.72, flip: true } ],
        say: [ { who: 0, en: "This isn't drama, Auggie. I really, truly miss home.", hi: "ये नाटक नहीं है, ऑगी। मुझे सच में घर की बहुत याद आ रही है।", kind: "whisper" },
               { who: 1, en: "Missing home isn't silly. It just means home is full of love.", hi: "घर याद आना बुरी बात नहीं, पिंकू। मतलब तुम्हारा घर प्यार से भरा है।" } ] },
      { bg: "space", chars: [ { id: "pinku", pose: "cheer", mood: "determined", x: 0.3 }, { id: "zibbo", pose: "stand", mood: "laugh", x: 0.72, flip: true } ],
        cap: { en: "Pinku tries to jump straight back down to Earth...", hi: "पिंकू ने सीधे धरती की तरफ़ छलाँग लगा दी..." },
        say: [ { who: 0, en: "Here I go! Wheee... wait, which way is DOWN?", hi: "ये चला! ऊऊऊ... रुको, नीचे किधर है?", kind: "shout" },
               { who: 1, en: "Zeep! Out here there's no up or down! Hop in my UFO.", hi: "ज़ीप! यहाँ ऊपर-नीचे कुछ नहीं होता! चलो, मेरी उड़न-तश्तरी में बैठो।" } ],
        fx: { en: "SPIN!", hi: "घूम-घाम!" }, action: true },
      { bg: "space", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.22 }, { id: "pinku", pose: "lie", mood: "scared", x: 0.5 }, { id: "zibbo", pose: "point", mood: "happy", x: 0.8, flip: true } ], props: [ { id: "ufo", x: 0.5, y: 0.15 } ],
        cap: { en: "Heat shield glowing, parachutes open... the UFO splashes down in the sea!", hi: "हीट-शील्ड दहकी, पैराशूट खुले... और उड़न-तश्तरी छपाक से समुद्र में उतरी!" },
        say: [ { who: 2, en: "Coming home gets HOT! The heat shield keeps us safe.", hi: "लौटते वक़्त बहुत गरमी होती है! हीट-शील्ड हमें बचाती है।" },
               { who: 1, en: "HOT?! I'm a pug! I shall now faint... dramatically!", hi: "गरमी?! मैं पग हूँ! मैं अब बेहोश हो रहा हूँ... पूरे स्टाइल में!" } ],
        fx: { en: "SPLASH!", hi: "छपाक!" }, action: true },
      { bg: "bedroom", chars: [ { id: "pinku", pose: "lie", mood: "laugh", x: 0.3 }, { id: "auggie", pose: "sit", mood: "laugh", x: 0.72, flip: true } ],
        cap: { en: "Morning. Auggie tells Pinku the dream. Pinku hugs his cushion very tightly.", hi: "सुबह ऑगी ने पिंकू को सपना सुनाया। पिंकू ने झट से अपनी गद्दी कसकर पकड़ ली।" },
        say: [ { who: 0, en: "I'm NEVER leaving Earth again. Earth has cushions!", hi: "मैं अब धरती छोड़कर कभी नहीं जाऊँगा। धरती पर गद्दियाँ हैं!" },
               { who: 1, en: "Never? Or five-seconds never?", hi: "कभी नहीं? या पाँच सेकंड वाला 'कभी नहीं'?" } ] }
    ]
  },

  // 140 — A Mars picnic in a dream
  {
    id: 140, age: "6-10", category: "space",
    title: { en: "Auggie's Picnic on Mars", hi: "मंगल ग्रह पर ऑगी की पिकनिक" },
    blurb: { en: "Auggie has hidden ten carrots for tomorrow's picnic, all for himself. Then he dreams of a picnic on Mars...", hi: "कल की पिकनिक के लिए ऑगी ने दस गाजरें छुपा रखी हैं, सब अपने लिए। फिर उसे सपना आता है... मंगल पर पिकनिक का!" },
    moral: { en: "A picnic tastes best when everyone gets a share.", hi: "पिकनिक का असली मज़ा तभी है, जब सबको हिस्सा मिले।" },
    cover: { bg: "space", chars: [ { id: "auggie", pose: "sit", mood: "laugh", x: 0.3 }, { id: "zibbo", pose: "cheer", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "planet", x: 0.12, y: 0.18 }, { id: "ufo", x: 0.88, y: 0.15 } ], fx: { en: "CRUNCH!", hi: "कुरकुर!" } },
    panels: [
      { bg: "bedroom", chars: [ { id: "auggie", pose: "lie", mood: "happy", x: 0.3 }, { id: "mumma", pose: "sit", mood: "surprised", x: 0.72, flip: true } ], props: [ { id: "book", x: 0.52 } ],
        cap: { en: "Picnic tomorrow! Auggie has a secret under his blanket. That night, he dreamed...", hi: "कल पिकनिक है! ऑगी के कंबल के नीचे एक राज़ छुपा है। उस रात उसने सपना देखा..." },
        say: [ { who: 1, en: "Mats, sandwiches, Mittsy's hat... wait, where did the ten carrots go?", hi: "दरी, सैंडविच, मिट्सी की टोपी... अरे, दस गाजरें कहाँ गईं?" },
               { who: 0, en: "Carrots? Never heard of them.", hi: "गाजर? वो क्या होती है?", kind: "whisper" } ] },
      { bg: "space", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "zibbo", pose: "wave", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "planet", x: 0.5, y: 0.12 } ],
        cap: { en: "...he was having a picnic on Mars with Zibbo!", hi: "...कि वो ज़िब्बो के साथ मंगल ग्रह पर पिकनिक मना रहा है!" },
        say: [ { who: 1, en: "Zeep! Welcome to Mars! India's Mangalyaan reached here on its very first try!", hi: "ज़ीप! मंगल पर स्वागत है! भारत का मंगलयान तो पहली ही कोशिश में यहाँ पहुँच गया था!" },
               { who: 0, en: "Nice view, Zibbo! Now... where's the FOOD?", hi: "वाह, क्या नज़ारा है! अब... खाना कहाँ है?" } ] },
      { bg: "space", chars: [ { id: "auggie", pose: "point", mood: "surprised", x: 0.3 }, { id: "zibbo", pose: "stand", mood: "laugh", x: 0.72, flip: true } ],
        cap: { en: "Auggie grabs a carrot, opens wide and...", hi: "ऑगी ने गाजर उठाई, बड़ा-सा मुँह खोला और..." },
        say: [ { who: 0, en: "OW! My helmet! I can't eat through glass!", hi: "आउच! मेरा हेलमेट! शीशे के आर-पार कैसे खाऊँ?", kind: "shout" },
               { who: 1, en: "Mars air is too thin to breathe. Helmets stay ON!", hi: "मंगल की हवा बहुत पतली है, साँस नहीं ले सकते। हेलमेट मत उतारना!" } ],
        fx: { en: "CLONK!", hi: "ठक्क!" }, action: true },
      { bg: "space", chars: [ { id: "auggie", pose: "run", mood: "determined", x: 0.35 }, { id: "zibbo", pose: "stand", mood: "scared", x: 0.75, flip: true } ], props: [ { id: "cloud", x: 0.6, y: 0.2 } ],
        cap: { en: "Then a Mars dust storm blows the picnic mat away!", hi: "तभी मंगल की धूल भरी आँधी आई और दरी उड़ा ले गई!" },
        say: [ { who: 1, en: "Zeep! Mars dust storms can cover the whole planet!", hi: "ज़ीप! मंगल की आँधी तो पूरे ग्रह को ढक लेती है!" },
               { who: 0, en: "Come back, mat! I haven't had ONE bite!", hi: "रुक जा दरी! मैंने तो एक कौर भी नहीं खाया!", kind: "shout" } ],
        fx: { en: "WHOOSH!", hi: "सूँऽऽ!" }, action: true },
      { bg: "space", chars: [ { id: "zibbo", pose: "sit", mood: "sad", x: 0.3 }, { id: "auggie", pose: "think", mood: "sad", x: 0.72, flip: true } ],
        say: [ { who: 0, en: "I didn't bring any food. I've never been to a picnic before...", hi: "मैं तो खाना लाया ही नहीं। मैं पहले कभी पिकनिक पर गया ही नहीं..." },
               { who: 1, en: "Ten carrots... all mine... but Zibbo has zero.", hi: "दस गाजरें... सब मेरी... पर ज़िब्बो के पास एक भी नहीं।", kind: "think" } ] },
      { bg: "space", chars: [ { id: "auggie", pose: "wave", mood: "happy", x: 0.3 }, { id: "zibbo", pose: "cheer", mood: "surprised", x: 0.72, flip: true } ], props: [ { id: "carrot", x: 0.5 }, { id: "ufo", x: 0.5, y: 0.15 } ],
        say: [ { who: 0, en: "Zibbo, I hid these for me. But a picnic is for sharing. Five for you!", hi: "ज़िब्बो, ये मैंने अपने लिए छुपाई थीं। पर पिकनिक तो बाँटने के लिए होती है। पाँच तुम्हारी!" },
               { who: 1, en: "Zeep zeep! My first picnic! Quick, into my UFO, it has air inside!", hi: "ज़ीप-ज़ीप! मेरी पहली पिकनिक! जल्दी, उड़न-तश्तरी में चलो, अंदर हवा है!" } ] },
      { bg: "space", chars: [ { id: "auggie", pose: "sit", mood: "laugh", x: 0.3 }, { id: "zibbo", pose: "sit", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "carrot", x: 0.5 }, { id: "sun", x: 0.5, y: 0.15 } ],
        cap: { en: "Helmets off, carrots out! Outside, the Mars sunset glows... BLUE!", hi: "हेलमेट उतरे, गाजरें निकलीं! और बाहर मंगल का सूरज डूब रहा है... नीले रंग में!" },
        say: [ { who: 1, en: "Tiny Mars dust makes its sunsets look blue!", hi: "मंगल की बारीक धूल की वजह से वहाँ सूरज नीला डूबता है!" },
               { who: 0, en: "Blue sunset, orange carrots, green friend. Best picnic EVER!", hi: "नीला सूरज, नारंगी गाजर, हरा दोस्त। अब तक की सबसे बढ़िया पिकनिक!" } ],
        fx: { en: "CRUNCH!", hi: "कुरकुर!" }, action: true },
      { bg: "home", chars: [ { id: "mumma", pose: "stand", mood: "laugh", x: 0.2 }, { id: "auggie", pose: "cheer", mood: "happy", x: 0.5 }, { id: "papa", pose: "stand", mood: "laugh", x: 0.8, flip: true } ],
        cap: { en: "Morning! Auggie brings out his secret carrots, one for everyone.", hi: "सुबह! ऑगी अपनी छुपाई गाजरें निकाल लाया, सबके लिए एक-एक।" },
        say: [ { who: 0, en: "So THAT's where my ten carrots went! HA HA HA!", hi: "अच्छा, तो मेरी दस गाजरें यहाँ थीं! हा हा हा!" },
               { who: 2, en: "An astronaut's favourite meal? LAUNCH!", hi: "सुना है ऑगी मंगल पर गया था? तभी आज का दिन इतना मंगलमय है!" } ] }
    ]
  },

  // ===================== AUGGIE AND GHOST =====================

  // 141 — The "ghost" that is a bedsheet on the clothesline
  {
    id: 141, age: "4-6", category: "ghost",
    title: { en: "The Ghost on the Clothesline", hi: "रस्सी वाला भूत!" },
    blurb: { en: "Something big and white is waving in the dark garden. Is it a GHOST? Auggie's nose will find out!", hi: "अँधेरे आँगन में कुछ बड़ा-सा, सफ़ेद-सा हिल रहा है। कहीं भूत तो नहीं? ऑगी की नाक पता लगाएगी!" },
    moral: { en: "Things look scary in the dark, but a brave closer look makes them friendly.", hi: "अँधेरे में चीज़ें डरावनी लगती हैं, पर हिम्मत से पास जाकर देखो तो सब अपना-सा लगता है।" },
    cover: { bg: "citynight", chars: [ { id: "auggie", pose: "point", mood: "surprised", x: 0.3 }, { id: "bhootu", pose: "wave", mood: "laugh", x: 0.72, flip: true } ], fx: { en: "BOO!", hi: "बू!" } },
    panels: [
      { bg: "citynight", chars: [ { id: "auggie", pose: "stand", mood: "scared", x: 0.4 } ],
        cap: { en: "Night. Auggie goes out for one last sniff in the garden.", hi: "रात हो गई। ऑगी आँगन में आख़िरी बार सूँघने निकला।" },
        say: [ { who: 0, en: "A big white GHOST! And it's waving at me!", hi: "हाय राम! बड़ा-सा सफ़ेद भूत! मुझे हाथ हिला रहा है!", kind: "shout" } ],
        fx: { en: "EEK!", hi: "ईईक!" }, action: true },
      { bg: "home", chars: [ { id: "auggie", pose: "sit", mood: "scared", x: 0.3 }, { id: "dadi", pose: "stand", mood: "laugh", x: 0.72, flip: true } ],
        say: [ { who: 0, en: "Dadi! A ghost! Hide me in your saree!", hi: "दादी! भूत! मुझे अपनी साड़ी में छुपा लो!" },
               { who: 1, en: "Arre, my brave boy! Go on, take a sniff first.", hi: "अरे मेरे शेर! डरना बाद में, पहले सूँघ तो ले!" } ] },
      { bg: "citynight", chars: [ { id: "auggie", pose: "point", mood: "determined", x: 0.4 } ],
        cap: { en: "Auggie takes one tiny brave step. Then another...", hi: "ऑगी ने एक नन्हा-सा हिम्मत वाला क़दम बढ़ाया। फिर एक और..." },
        say: [ { who: 0, en: "Brave dogs sniff first... and scream later.", hi: "बहादुर कुत्ते पहले सूँघते हैं... चीख़ते बाद में।", kind: "whisper" } ],
        fx: { en: "SNIFF!", hi: "सूँ-सूँ!" }, action: true },
      { bg: "citynight", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.35 }, { id: "dadi", pose: "stand", mood: "laugh", x: 0.75, flip: true } ],
        cap: { en: "It smells of Dadi's soap. It's Dadi's bedsheet on the clothesline!", hi: "इसमें तो दादी के साबुन की ख़ुशबू है! ये दादी की चादर है, रस्सी पर सूख रही!" },
        say: [ { who: 0, en: "Wait... ghosts don't smell like soap!", hi: "रुको... भूत से साबुन की ख़ुशबू थोड़े आती है!" },
               { who: 1, en: "The wind makes it wave, beta!", hi: "हवा से हिल रही है, बेटा!" } ] },
      { bg: "citynight", chars: [ { id: "auggie", pose: "stand", mood: "surprised", x: 0.3 }, { id: "bhootu", pose: "cheer", mood: "laugh", x: 0.72, flip: true } ],
        cap: { en: "FLOP! The sheet falls on Auggie. Then... a tiny giggle!", hi: "धप्प! चादर ऑगी के ऊपर गिर गई। तभी... एक नन्ही-सी खिलखिलाहट!" },
        say: [ { who: 1, en: "Hee hee! You're the funniest ghost I've ever seen!", hi: "ही ही! इतना मज़ेदार भूत तो मैंने कभी नहीं देखा!" },
               { who: 0, en: "Bhootu! YOU'RE the real ghost, silly!", hi: "भूतू! असली भूत तो तुम हो, बुद्धू!" } ],
        fx: { en: "FLOP!", hi: "धप्प!" }, action: true },
      { bg: "citynight", chars: [ { id: "auggie", pose: "sit", mood: "happy", x: 0.2 }, { id: "bhootu", pose: "wave", mood: "happy", x: 0.5 }, { id: "dadi", pose: "stand", mood: "laugh", x: 0.8, flip: true } ],
        cap: { en: "Dadi, Auggie and Bhootu fold the sheet together.", hi: "दादी, ऑगी और भूतू ने मिलकर चादर तह की।" },
        say: [ { who: 2, en: "Here, a secret carrot from my pallu. Shh!", hi: "ले, मेरे पल्लू की ख़ुफ़िया गाजर। किसी से कहना मत!" },
               { who: 1, en: "Hide-and-seek tomorrow? No bedsheets allowed!", hi: "कल छुपन-छुपाई खेलें? पर चादर में छुपना मना!" } ] }
    ]
  },

  // 142 — The midnight fridge noise
  {
    id: 142, age: "4-6", category: "ghost",
    title: { en: "Who's Humming in the Kitchen?", hi: "रसोई में कौन गुनगुना रहा है?" },
    blurb: { en: "HMMMM! Something is humming in the kitchen at midnight. A monster? A ghost? Or something... cooler?", hi: "हम्म्म्म! आधी रात को रसोई में कोई गुनगुना रहा है। राक्षस? भूत? या कुछ... ठंडा-ठंडा?" },
    moral: { en: "Night noises are usually just everyday things doing their jobs.", hi: "रात की आवाज़ें ज़्यादातर रोज़ की चीज़ें ही होती हैं, बस अपना काम करती हुई।" },
    cover: { bg: "kitchen", chars: [ { id: "auggie", pose: "stand", mood: "surprised", x: 0.3 }, { id: "bhootu", pose: "cheer", mood: "laugh", x: 0.72, flip: true } ], fx: { en: "HMMMM!", hi: "हम्म्म्म!" } },
    panels: [
      { bg: "bedroom", chars: [ { id: "auggie", pose: "stand", mood: "scared", x: 0.3 }, { id: "papa", pose: "lie", mood: "sleepy", x: 0.72, flip: true } ],
        cap: { en: "Midnight. Everyone is asleep. Then Auggie hears it...", hi: "आधी रात। सब सो रहे हैं। तभी ऑगी को कुछ सुनाई दिया..." },
        say: [ { who: 0, en: "Something in the kitchen is GROWLING, Papa!", hi: "पापा! रसोई में कोई गुर्रा रहा है!", kind: "whisper" } ],
        fx: { en: "HMMMM!", hi: "हम्म्म्म!" }, action: true },
      { bg: "bedroom", chars: [ { id: "auggie", pose: "stand", mood: "determined", x: 0.3 }, { id: "papa", pose: "lie", mood: "sleepy", x: 0.72, flip: true } ],
        say: [ { who: 1, en: "Must be a hungry monster... just like you. Zzz.", hi: "कोई भूखा राक्षस होगा... बिल्कुल तेरे जैसा। खर्र..." },
               { who: 0, en: "Then I'll go! Somebody has to guard the carrots!", hi: "तो मैं ही जाता हूँ! गाजरों की रखवाली कौन करेगा?" } ] },
      { bg: "kitchen", chars: [ { id: "auggie", pose: "point", mood: "scared", x: 0.4 } ],
        cap: { en: "Auggie tiptoes into the kitchen. The big fridge hums...", hi: "ऑगी दबे पाँव रसोई में आया। बड़ा फ़्रिज गुनगुना रहा है..." },
        say: [ { who: 0, en: "Mr Fridge... is that YOU growling?", hi: "फ़्रिज जी... क्या आप गुर्रा रहे हैं?", kind: "whisper" } ] },
      { bg: "kitchen", chars: [ { id: "auggie", pose: "stand", mood: "scared", x: 0.3 }, { id: "bhootu", pose: "stand", mood: "scared", x: 0.72, flip: true } ],
        cap: { en: "The fridge door is open. Something small and white is inside!", hi: "फ़्रिज का दरवाज़ा खुला है। अंदर कुछ छोटा-सा, सफ़ेद-सा बैठा है!" },
        say: [ { who: 0, en: "EEEK! A fridge ghost!", hi: "ईईक! फ़्रिज वाला भूत!", kind: "shout" },
               { who: 1, en: "EEEK! A big yellow monster!", hi: "ईईक! बड़ा पीला राक्षस!", kind: "shout" } ],
        fx: { en: "EEEK!", hi: "ईईक!" }, action: true },
      { bg: "kitchen", chars: [ { id: "auggie", pose: "sit", mood: "laugh", x: 0.3 }, { id: "bhootu", pose: "sit", mood: "happy", x: 0.72, flip: true } ],
        say: [ { who: 1, en: "Sorry! The fridge hums me lullabies. It's so cool!", hi: "सॉरी! फ़्रिज मुझे लोरी सुनाता है। और अंदर कितनी ठंडक है!" },
               { who: 0, en: "It hums when it's working hard to keep food cold.", hi: "फ़्रिज खाना ठंडा रखने के लिए मेहनत करता है, तभी हम्म्म करता है।" } ] },
      { bg: "kitchen", chars: [ { id: "auggie", pose: "sit", mood: "happy", x: 0.3 }, { id: "bhootu", pose: "wave", mood: "laugh", x: 0.72, flip: true } ],
        cap: { en: "Auggie shuts the fridge door. Then the two friends share one crunchy carrot.", hi: "ऑगी ने फ़्रिज बंद किया। फिर दोनों दोस्तों ने मिलकर एक कुरकुरी गाजर खाई।" },
        say: [ { who: 0, en: "Door shut, cold stays in! Now let's hum together.", hi: "दरवाज़ा बंद, ठंडक अंदर! चलो, अब साथ में गुनगुनाते हैं।" },
               { who: 1, en: "Hmm-hmm-hmm! Best midnight friend ever!", hi: "हम्म-हम्म-हम्म! आधी रात का सबसे प्यारा दोस्त!" } ],
        fx: { en: "CRUNCH!", hi: "कुरकुर!" }, action: true }
    ]
  },

  // 143 — The old bungalow at the end of the lane; lonely Bhootu finds a friend
  {
    id: 143, age: "4-6", category: "ghost",
    title: { en: "Who Lives in the Old Bungalow?", hi: "पुराने बंगले में कौन रहता है?" },
    blurb: { en: "Auggie's ball rolls into the old bungalow where nobody ever goes. Then it rolls back... all by itself!", hi: "ऑगी की गेंद उस पुराने बंगले में चली गई, जहाँ कोई नहीं जाता। फिर वो अपने आप लुढ़ककर वापस आ गई!" },
    moral: { en: "Even someone who seems scary might just be waiting for a friend.", hi: "जो डरावना लगता है, हो सकता है वो बस एक दोस्त का इंतज़ार कर रहा हो।" },
    cover: { bg: "haunted", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "bhootu", pose: "wave", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "ball", x: 0.52 } ], fx: { en: "PEEKABOO!", hi: "झाँक-झाँक!" } },
    panels: [
      { bg: "citynight", chars: [ { id: "auggie", pose: "stand", mood: "surprised", x: 0.3 }, { id: "moti", pose: "stand", mood: "scared", x: 0.72, flip: true } ],
        cap: { en: "Auggie's ball bounces into the old bungalow at the end of the lane.", hi: "ऑगी की गेंद उछलकर गली के आख़िरी पुराने बंगले में जा गिरी।" },
        say: [ { who: 1, en: "Nobody goes in there. They say a GHOST lives inside!", hi: "वहाँ कोई नहीं जाता, भाई। सुना है अंदर भूत रहता है!" },
               { who: 0, en: "But... that's my FAVOURITE ball!", hi: "पर... वो मेरी सबसे प्यारी गेंद है!" } ] },
      { bg: "haunted", chars: [ { id: "auggie", pose: "point", mood: "determined", x: 0.4 } ],
        cap: { en: "Auggie decides. Favourite ball. Brave nose. In he goes!", hi: "ऑगी ने ठान लिया। प्यारी गेंद। बहादुर नाक। चलो अंदर!" },
        say: [ { who: 0, en: "One carrot... two carrots... three carrots... GO!", hi: "एक गाजर... दो गाजर... तीन गाजर... चलो!", kind: "whisper" } ],
        fx: { en: "CREAK!", hi: "चर्र्र!" }, action: true },
      { bg: "haunted", chars: [ { id: "auggie", pose: "stand", mood: "scared", x: 0.35 } ], props: [ { id: "ball", x: 0.72 } ],
        cap: { en: "Then the ball rolls back to Auggie... ALL by itself!", hi: "तभी गेंद लुढ़कती हुई वापस ऑगी के पास आई... अपने आप!" },
        say: [ { who: 0, en: "Who... who's there? I'm a VERY big dog!", hi: "क-क-कौन है? मैं बहुत बड़ा कुत्ता हूँ, हाँ!", kind: "shout" } ] },
      { bg: "haunted", chars: [ { id: "auggie", pose: "sit", mood: "surprised", x: 0.3 }, { id: "bhootu", pose: "wave", mood: "happy", x: 0.72, flip: true } ],
        say: [ { who: 1, en: "Hello... I rolled it back. Will you play with me?", hi: "हेलो... गेंद मैंने लौटाई। मेरे साथ खेलोगे?", kind: "whisper" },
               { who: 0, en: "A tiny ghost? You're smaller than my bowl!", hi: "नन्हा-सा भूत? तुम तो मेरे कटोरे से भी छोटे हो!" } ] },
      { bg: "haunted", chars: [ { id: "auggie", pose: "stand", mood: "determined", x: 0.3 }, { id: "bhootu", pose: "sit", mood: "sad", x: 0.72, flip: true } ],
        say: [ { who: 1, en: "Everyone screams and runs away. Nobody ever plays with me.", hi: "सब चीख़कर भाग जाते हैं। मेरे साथ कोई नहीं खेलता।" },
               { who: 0, en: "I'm not running. Let's play hide-and-seek!", hi: "मैं नहीं भागूँगा। चलो, छुपन-छुपाई खेलते हैं!" } ] },
      { bg: "haunted", chars: [ { id: "auggie", pose: "point", mood: "laugh", x: 0.2 }, { id: "bhootu", pose: "cheer", mood: "laugh", x: 0.5 }, { id: "moti", pose: "stand", mood: "happy", x: 0.8, flip: true } ],
        cap: { en: "Bhootu hides. Auggie sniffs: old books and jasmine. Found you!", hi: "भूतू छुपा। ऑगी ने सूँघा: पुरानी किताबें और चमेली। मिल गया!" },
        say: [ { who: 1, en: "Hee hee! My very first friend!", hi: "ही ही! मेरा सबसे पहला दोस्त!" },
               { who: 2, en: "Ghost or not... can I play too?", hi: "भूत हो या न हो... मैं भी खेलूँ?" } ],
        fx: { en: "FOUND YOU!", hi: "मिल गया!" }, action: true }
    ]
  },

  // 144 — The fancy-dress party (not Halloween)
  {
    id: 144, age: "6-10", category: "ghost",
    title: { en: "Fancy Dress and a Real Ghost", hi: "फ़ैंसी ड्रेस में असली भूत!" },
    blurb: { en: "Auggie wants the fancy-dress trophy so badly. So why is he inviting a REAL ghost to the party?", hi: "ऑगी को फ़ैंसी ड्रेस की ट्रॉफ़ी हर हाल में चाहिए। फिर वो पार्टी में एक असली भूत को क्यों बुला रहा है?" },
    moral: { en: "Cheering for a friend can feel even better than winning.", hi: "दोस्त की जीत पर ताली बजाना, ख़ुद जीतने से भी ज़्यादा मीठा लगता है।" },
    cover: { bg: "garden", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.22 }, { id: "bhootu", pose: "cheer", mood: "happy", x: 0.5 }, { id: "missji", pose: "stand", mood: "laugh", x: 0.8, flip: true } ], props: [ { id: "trophy", x: 0.36, y: 0.25 }, { id: "balloon", x: 0.92, y: 0.15 } ], fx: { en: "TA-DA!", hi: "टा-डा!" } },
    panels: [
      { bg: "home", chars: [ { id: "auggie", pose: "cheer", mood: "determined", x: 0.3 }, { id: "anaya", pose: "point", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "trophy", x: 0.52 } ],
        cap: { en: "Sunday is the colony fancy-dress party. First prize: a shiny gold trophy!", hi: "रविवार को कॉलोनी में फ़ैंसी ड्रेस पार्टी है। पहला इनाम: चमचमाती सुनहरी ट्रॉफ़ी!" },
        say: [ { who: 1, en: "Come as anything you like, Auggie! Miss Ji is the judge!", hi: "जो बनना हो बनो, ऑगी! जज बनेंगी मिस जी!" },
               { who: 0, en: "That trophy is MINE. I'll be the best-dressed dog in Chamakpur!", hi: "वो ट्रॉफ़ी तो मेरी है! चमकपुर का सबसे सजा-धजा कुत्ता मैं ही बनूँगा!" } ] },
      { bg: "home", chars: [ { id: "auggie", pose: "stand", mood: "laugh", x: 0.3 }, { id: "mausi", pose: "stand", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "camera", x: 0.92 } ],
        cap: { en: "Mausi makes Auggie a costume. He's a giant, very orange... carrot!", hi: "मौसी ने ऑगी की पोशाक बनाई। वो बन गया एक बड़ी-सी, नारंगी... गाजर!" },
        say: [ { who: 1, en: "Hold that pose! Auggie... are you EATING your costume?", hi: "पोज़ पकड़ो! ऑगी... तुम अपनी पोशाक खा रहे हो क्या?" },
               { who: 0, en: "I can't help it. I look delicious!", hi: "क्या करूँ, मौसी! मैं दिख ही इतना स्वादिष्ट रहा हूँ!" } ],
        fx: { en: "NIBBLE!", hi: "कुतर-कुतर!" }, action: true },
      { bg: "haunted", chars: [ { id: "auggie", pose: "stand", mood: "happy", x: 0.3 }, { id: "bhootu", pose: "stand", mood: "sad", x: 0.72, flip: true } ],
        cap: { en: "On the way, Auggie passes the old bungalow. Bhootu is at the window, looking glum.", hi: "रास्ते में पुराना बंगला आया। खिड़की पर भूतू उदास बैठा है।" },
        say: [ { who: 1, en: "A party? I can't go. Everyone screams when they see a ghost.", hi: "पार्टी? मैं नहीं जा सकता। भूत देखते ही सब चीख़ने लगते हैं।" } ] },
      { bg: "haunted", chars: [ { id: "auggie", pose: "think", mood: "determined", x: 0.3 }, { id: "bhootu", pose: "stand", mood: "surprised", x: 0.72, flip: true } ],
        say: [ { who: 0, en: "It's FANCY DRESS! Everyone will think you're a costume. Come as yourself!", hi: "अरे, फ़ैंसी ड्रेस है! सब सोचेंगे तुमने पोशाक पहनी है। तुम बस तुम बनकर आओ!" },
               { who: 1, en: "Me? At a party? With real friends? Eeee!", hi: "मैं? पार्टी में? सच के दोस्तों के साथ? ईईई!", kind: "shout" } ] },
      { bg: "garden", chars: [ { id: "rohan", pose: "stand", mood: "surprised", x: 0.22 }, { id: "bhootu", pose: "cheer", mood: "laugh", x: 0.5 }, { id: "kabir", pose: "stand", mood: "happy", x: 0.8, flip: true } ], props: [ { id: "balloon", x: 0.08, y: 0.15 } ],
        say: [ { who: 0, en: "Wow! Best ghost costume ever! It even FLOATS!", hi: "वाह! क्या ग़ज़ब का भूत बना है! ये तो तैर भी रहा है!" },
               { who: 2, en: "How do you glow like that? Batteries?", hi: "तुम ऐसे चमकते कैसे हो? बैटरी से?", kind: "whisper" } ] },
      { bg: "garden", chars: [ { id: "auggie", pose: "sit", mood: "sad", x: 0.3 }, { id: "missji", pose: "stand", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "trophy", x: 0.52 } ],
        say: [ { who: 1, en: "And the gold trophy goes to... the little floating ghost!", hi: "और सुनहरी ट्रॉफ़ी जाती है... नन्हे तैरते भूत को!", kind: "shout" },
               { who: 0, en: "I wanted that trophy so much... but look how happy Bhootu is.", hi: "मुझे वो ट्रॉफ़ी कितनी चाहिए थी... पर देखो, भूतू कितना ख़ुश है!", kind: "think" } ],
        fx: { en: "TA-DA!", hi: "टा-डा!" }, action: true },
      { bg: "garden", chars: [ { id: "auggie", pose: "sit", mood: "happy", x: 0.3 }, { id: "bhootu", pose: "stand", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "trophy", x: 0.52 } ],
        say: [ { who: 1, en: "It was your idea, Auggie. You should have it.", hi: "आइडिया तो तुम्हारा था, ऑगी। ट्रॉफ़ी तुम रखो।" },
               { who: 0, en: "No way! Watching my friend win feels even better than winning.", hi: "बिल्कुल नहीं! दोस्त को जीतते देखना, ख़ुद जीतने से भी बढ़िया लगता है।" } ] },
      { bg: "garden", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.22 }, { id: "bhootu", pose: "cheer", mood: "laugh", x: 0.5 }, { id: "missji", pose: "stand", mood: "laugh", x: 0.8, flip: true } ],
        cap: { en: "Bhootu whispers the truth: he's a REAL ghost. The kids just cheer louder!", hi: "भूतू ने धीरे से सच बताया: वो असली भूत है! बच्चों ने और ज़ोर से ताली बजाई!" },
        say: [ { who: 2, en: "Special prize for the Most Delicious Costume... one fresh carrot!", hi: "और 'सबसे स्वादिष्ट पोशाक' का ख़ास इनाम... एक ताज़ी गाजर!" },
               { who: 0, en: "Finally! A prize I'm ALLOWED to eat!", hi: "आख़िरकार! ऐसा इनाम जिसे खाने की इजाज़त है!" } ],
        fx: { en: "CLAP-CLAP!", hi: "तालियाँ!" }, action: true }
    ]
  },

  // 145 — Pinku is sure the house is haunted (and faints dramatically)
  {
    id: 145, age: "6-10", category: "ghost",
    title: { en: "Pinku and the Haunted Sleepover", hi: "पिंकू और भूतिया स्लीपओवर" },
    blurb: { en: "Pinku is the bravest pug in Chamakpur, he says. Then the curtains move, the tap drips, and he faints. Again. And again.", hi: "पिंकू कहता है वो चमकपुर का सबसे बहादुर पग है। फिर पर्दे हिले, नल टपका... और वो बेहोश। फिर से। और फिर से!" },
    moral: { en: "When you're scared, say so, and check things out together with a friend.", hi: "डर लगे तो बोल दो, और किसी दोस्त के साथ मिलकर देखो कि असल में है क्या।" },
    cover: { bg: "bedroom", chars: [ { id: "pinku", pose: "lie", mood: "scared", x: 0.25 }, { id: "auggie", pose: "stand", mood: "laugh", x: 0.52 }, { id: "bhootu", pose: "wave", mood: "happy", x: 0.8, flip: true } ], fx: { en: "THUD!", hi: "धप्प!" } },
    panels: [
      { bg: "home", chars: [ { id: "pinku", pose: "stand", mood: "determined", x: 0.3 }, { id: "auggie", pose: "sit", mood: "happy", x: 0.72, flip: true } ],
        cap: { en: "Pinku arrives for a sleepover, carrying his pillow and a LOT of attitude.", hi: "पिंकू स्लीपओवर के लिए आया है। साथ में तकिया, और नख़रे पूरे।" },
        say: [ { who: 0, en: "Ghosts? Pah! I am the bravest pug in all of Chamakpur!", hi: "भूत? हुँह! मैं पूरे चमकपुर का सबसे बहादुर पग हूँ!" },
               { who: 1, en: "Great! Dadi says our house makes funny noises at night.", hi: "बढ़िया! दादी कहती हैं, रात को हमारा घर अजीब-अजीब आवाज़ें करता है।" } ] },
      { bg: "bedroom", chars: [ { id: "pinku", pose: "lie", mood: "scared", x: 0.3 }, { id: "auggie", pose: "stand", mood: "laugh", x: 0.72, flip: true } ],
        cap: { en: "Night. The curtain flaps. Something goes 'Wooooo'...", hi: "रात। पर्दा फड़फड़ाया। कहीं से आवाज़ आई, 'हूऊऊऊ'..." },
        say: [ { who: 0, en: "A GHOST! Tell everyone I was VERY brave!", hi: "भूत! सबको बताना, मैं बहुत बहादुर था!", kind: "shout" },
               { who: 1, en: "It's just the fan, Pinku! It blows the curtain and whistles.", hi: "अरे, ये तो पंखा है, पिंकू! पर्दा उड़ाता है और सीटी बजाता है।" } ],
        fx: { en: "THUD!", hi: "धप्प!" }, action: true },
      { bg: "kitchen", chars: [ { id: "pinku", pose: "lie", mood: "scared", x: 0.3 }, { id: "auggie", pose: "stand", mood: "determined", x: 0.72, flip: true } ],
        cap: { en: "Then, from the kitchen: tap... tap... tap... Pinku faints again, carefully onto a cushion.", hi: "फिर रसोई से: टप... टप... टप... पिंकू फिर बेहोश... पर गद्दी देखकर!" },
        say: [ { who: 1, en: "Ghost footsteps? No! Just the tap dripping. Let's shut it tight!", hi: "भूत के क़दम? नहीं जी! नल टपक रहा है। चलो, कसकर बंद करो!" },
               { who: 0, en: "I wasn't fainting. I was... resting my eyes.", hi: "मैं बेहोश नहीं हुआ था। बस... आँखों को आराम दे रहा था।" } ],
        fx: { en: "DRIP!", hi: "टप-टप!" }, action: true },
      { bg: "bedroom", chars: [ { id: "auggie", pose: "think", mood: "laugh", x: 0.3 }, { id: "pinku", pose: "stand", mood: "scared", x: 0.72, flip: true } ],
        say: [ { who: 1, en: "Muddy GHOST footprints! Leading right to the big bed!", hi: "भूत के कीचड़ वाले पैरों के निशान! सीधे बड़े बिस्तर तक!", kind: "shout" },
               { who: 0, en: "Umm... those are mine. I took a secret nap on Papa's bed.", hi: "अम्म... वो मेरे हैं। मैंने चुपके से पापा के बिस्तर पर झपकी ली थी।" } ] },
      { bg: "bedroom", chars: [ { id: "pinku", pose: "sit", mood: "sad", x: 0.3 }, { id: "auggie", pose: "sit", mood: "happy", x: 0.72, flip: true } ],
        say: [ { who: 0, en: "Auggie... can I hold your paw? For, um... science reasons.", hi: "ऑगी... तुम्हारा पंजा पकड़ लूँ? वो क्या है... विज्ञान के लिए।", kind: "whisper" },
               { who: 1, en: "Of course. Being scared is okay. Asking for a paw is brave.", hi: "बिल्कुल! डरना ठीक है। पंजा माँगना तो बहादुरी है।" } ] },
      { bg: "bedroom", chars: [ { id: "pinku", pose: "lie", mood: "scared", x: 0.22 }, { id: "auggie", pose: "sit", mood: "surprised", x: 0.5 }, { id: "bhootu", pose: "wave", mood: "happy", x: 0.8, flip: true } ],
        cap: { en: "A soft glow floats in, carrying a tiny pillow...", hi: "एक हल्की-सी रोशनी तैरती हुई अंदर आई, हाथ में नन्हा-सा तकिया लिए..." },
        say: [ { who: 2, en: "Hello! I heard there's a sleepover. Can I join?", hi: "हेलो! सुना यहाँ स्लीपओवर है। मैं भी आ जाऊँ?" },
               { who: 0, en: "A REAL GHOST! I'm fainting... for real this time!", hi: "असली भूत! इस बार मैं सच में बेहोश हो रहा हूँ!", kind: "shout" } ],
        fx: { en: "FLOP!", hi: "धड़ाम!" }, action: true },
      { bg: "bedroom", chars: [ { id: "pinku", pose: "lie", mood: "surprised", x: 0.3 }, { id: "bhootu", pose: "stand", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "bowl", x: 0.52 } ],
        say: [ { who: 0, en: "You're a ghost... and you brought me WATER?", hi: "तुम भूत हो... और मेरे लिए पानी लाए?" },
               { who: 1, en: "You fainted! And I've never had a friend to look after before.", hi: "तुम बेहोश हो गए थे! और मेरा कभी कोई दोस्त ही नहीं था, जिसका ख़याल रखूँ।" } ] },
      { bg: "bedroom", chars: [ { id: "pinku", pose: "lie", mood: "happy", x: 0.22 }, { id: "bhootu", pose: "lie", mood: "laugh", x: 0.5, flip: true }, { id: "auggie", pose: "lie", mood: "sleepy", x: 0.8, flip: true } ],
        cap: { en: "Soon, the only scary sound left in the house is Auggie's snoring.", hi: "थोड़ी देर में घर में बस एक ही डरावनी आवाज़ बची: ऑगी के खर्राटे!" },
        say: [ { who: 0, en: "You're not scary at all, Bhootu. You're... kind of adorable.", hi: "तुम ज़रा भी डरावने नहीं हो, भूतू। तुम तो... बड़े प्यारे हो।" },
               { who: 1, en: "And you're the bravest pug in Chamakpur. Mostly.", hi: "और तुम चमकपुर के सबसे बहादुर पग हो। ज़्यादातर।" } ] }
    ]
  },

  // 146 — Bhootu is scared of Auggie's sneeze
  {
    id: 146, age: "6-10", category: "ghost",
    title: { en: "Bhootu and the Big Sneeze", hi: "भूतू और ऑगी की महा-छींक" },
    blurb: { en: "Auggie's sneeze is SO big, tiny Bhootu hides in a trunk and won't come out. How do you say sorry for a sneeze?", hi: "ऑगी की छींक इतनी ज़ोरदार थी कि नन्हा भूतू एक संदूक में जा छुपा, और बाहर ही नहीं आ रहा! छींक के लिए सॉरी कैसे बोलें?" },
    moral: { en: "Say sorry even for accidents, and ask questions instead of running away.", hi: "ग़लती अनजाने में हो, तब भी सॉरी बोलो; और डर लगे तो भागने से पहले पूछ लो।" },
    cover: { bg: "haunted", chars: [ { id: "auggie", pose: "blast", mood: "surprised", x: 0.3 }, { id: "bhootu", pose: "stand", mood: "scared", x: 0.72, flip: true } ], fx: { en: "ACHOO!", hi: "आछूँ!" } },
    panels: [
      { bg: "haunted", chars: [ { id: "auggie", pose: "sit", mood: "happy", x: 0.3 }, { id: "bhootu", pose: "cheer", mood: "laugh", x: 0.72, flip: true } ],
        cap: { en: "Hide-and-seek in Bhootu's dusty old bungalow. Auggie is counting.", hi: "भूतू के धूल भरे पुराने बंगले में छुपन-छुपाई। ऑगी गिनती गिन रहा है।" },
        say: [ { who: 1, en: "Count to ten! And NO sniffing, you cheater nose!", hi: "दस तक गिनो! और सूँघना मना है, चालू नाक!" },
               { who: 0, en: "One carrot, two carrots, three... ooh, this dust tickles...", hi: "एक गाजर, दो गाजर, तीन... उफ़, ये धूल गुदगुदी कर रही है..." } ] },
      { bg: "haunted", chars: [ { id: "auggie", pose: "blast", mood: "surprised", x: 0.35 }, { id: "bhootu", pose: "stand", mood: "scared", x: 0.75, flip: true } ],
        cap: { en: "The dust tickles Auggie's big nose. Ah... ahh... AHHH...", hi: "धूल ने ऑगी की बड़ी नाक में गुदगुदी की। आ... आ... आऽऽऽ..." },
        say: [ { who: 0, en: "AAA-CHOOOO!", hi: "आऽऽ-छूँऽऽ!", kind: "shout" },
               { who: 1, en: "EEEK! Thunder in your NOSE!", hi: "ईईक! तुम्हारी नाक में बादल गरजा!", kind: "shout" } ],
        fx: { en: "ACHOO!", hi: "आछूँ!" }, action: true },
      { bg: "haunted", chars: [ { id: "auggie", pose: "stand", mood: "sad", x: 0.3 }, { id: "bhootu", pose: "stand", mood: "scared", x: 0.72, flip: true } ], props: [ { id: "chest", x: 0.9 } ],
        cap: { en: "WHOOSH! Bhootu zooms into an old trunk and slams the lid.", hi: "सर्र! भूतू उड़कर एक पुराने संदूक में घुसा और ढक्कन बंद!" },
        say: [ { who: 0, en: "It was only a sneeze, Bhootu! Come out!", hi: "अरे, वो बस छींक थी, भूतू! बाहर आ जाओ!" },
               { who: 1, en: "Nothing is ONLY a sneeze when you're this tiny!", hi: "जब तुम इतने छोटे हो, तो कोई छींक 'बस छींक' नहीं होती!" } ] },
      { bg: "home", chars: [ { id: "auggie", pose: "lie", mood: "sad", x: 0.3 }, { id: "dadi", pose: "sit", mood: "happy", x: 0.72, flip: true } ],
        cap: { en: "Three days later. No Bhootu. No hide-and-seek. Auggie is too sad even for carrots.", hi: "तीन दिन बीत गए। न भूतू, न छुपन-छुपाई। ऑगी इतना उदास है कि गाजर भी नहीं भा रही।" },
        say: [ { who: 0, en: "But Dadi, I didn't MEAN to sneeze! Why should I say sorry?", hi: "पर दादी, मैंने जान-बूझकर थोड़ी छींका! मैं सॉरी क्यों बोलूँ?" },
               { who: 1, en: "Because he got scared, beta. Sorry isn't only for things we mean.", hi: "क्योंकि वो डर गया, बेटा। सॉरी सिर्फ़ जान-बूझकर की ग़लती के लिए नहीं होता।" } ] },
      { bg: "haunted", chars: [ { id: "auggie", pose: "stand", mood: "surprised", x: 0.3 }, { id: "bhootu", pose: "stand", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "chest", x: 0.9 } ],
        cap: { en: "Auggie holds the sneeze in with all his might... it comes out as a tiny squeak!", hi: "ऑगी ने पूरी ताक़त से छींक रोकी... और निकली बस एक नन्ही-सी 'चूँ'!" },
        say: [ { who: 1, en: "Hee hee! Your ears just flew up like kites!", hi: "ही ही! तुम्हारे कान तो पतंग जैसे उड़ गए!" } ],
        fx: { en: "SQUEAK!", hi: "चूँ!" }, action: true },
      { bg: "haunted", chars: [ { id: "auggie", pose: "sit", mood: "happy", x: 0.3 }, { id: "bhootu", pose: "stand", mood: "sad", x: 0.72, flip: true } ],
        say: [ { who: 0, en: "Sorry I scared you, Bhootu. My nose has no volume button.", hi: "तुम्हें डराने के लिए सॉरी, भूतू। मेरी नाक में आवाज़ कम करने का बटन ही नहीं है।" },
               { who: 1, en: "Sorry I hid for three days. I should've just asked what a sneeze is.", hi: "सॉरी, मैं तीन दिन छुपा रहा। मुझे बस पूछ लेना चाहिए था कि छींक होती क्या है।" } ] },
      { bg: "haunted", chars: [ { id: "anaya", pose: "blast", mood: "determined", x: 0.22 }, { id: "auggie", pose: "cheer", mood: "laugh", x: 0.5, flip: true }, { id: "bhootu", pose: "cheer", mood: "happy", x: 0.8, flip: true } ],
        cap: { en: "Auggie explains: a sneeze is just your nose sweeping out dust. So... cleaning party!", hi: "ऑगी ने समझाया: छींक मतलब नाक अंदर की धूल बाहर झाड़ रही है। तो चलो... सफ़ाई पार्टी!" },
        say: [ { who: 0, en: "Less dust, fewer sneezes! And always sneeze into your elbow!", hi: "धूल कम, छींक कम! और छींको तो कोहनी में, समझे?" },
               { who: 1, en: "Which elbow? I've got FOUR legs!", hi: "कौन-सी कोहनी? मेरी तो चार टाँगें हैं!" } ] },
      { bg: "garden", chars: [ { id: "auggie", pose: "lie", mood: "laugh", x: 0.3 }, { id: "bhootu", pose: "cheer", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "flower", x: 0.52 } ],
        cap: { en: "Clean bungalow, happy friends. Then Bhootu makes a teeny sound...", hi: "साफ़-सुथरा बंगला, ख़ुश दोस्त। तभी भूतू की एक नन्ही-सी आवाज़ आई..." },
        say: [ { who: 1, en: "Achoo! My first sneeze! It's not scary at all... it's FUN!", hi: "आछूँ! मेरी पहली छींक! ये तो डरावनी नहीं... मज़ेदार है!" },
               { who: 0, en: "Tiny ghost, tiny sneeze! Now... ready or not, here I come!", hi: "नन्हा भूत, नन्ही छींक! अब... तैयार हो या नहीं, मैं आया!" } ],
        fx: { en: "CHOO!", hi: "छूँ!" }, action: true }
    ]
  }
);
