window.AUGGIE_COMICS = window.AUGGIE_COMICS || [];
window.AUGGIE_COMICS.push(

  // ===================== AUGGIE AND HOLIDAY =====================

  // 123 — Packing chaos: Mumma's list vs Auggie's one carrot
  {
    id: 123, age: "4-6", category: "holiday",
    title: { en: "Mumma's List, Auggie's Carrot", hi: "मम्मा की लिस्ट, ऑगी की गाजर" },
    blurb: { en: "Mumma packed forty things. Auggie packed one carrot. So who is really ready for the holiday?", hi: "मम्मा ने चालीस चीज़ें रखीं, ऑगी ने बस एक गाजर। अब बताओ, छुट्टी के लिए असल में तैयार कौन है?" },
    moral: { en: "Packing is quicker and happier when everyone helps.", hi: "सब मिलकर पैकिंग करें, तो काम जल्दी भी होता है और मज़ेदार भी।" },
    cover: { bg: "home", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.33 }, { id: "mumma", pose: "point", mood: "laugh", x: 0.75, flip: true } ], props: [ { id: "suitcase", x: 0.12 }, { id: "bowl", x: 0.55, y: 0.85 } ], fx: { en: "PACKED!", hi: "पैक!" } },
    panels: [
      { bg: "home", chars: [ { id: "mumma", pose: "point", mood: "happy", x: 0.3 }, { id: "auggie", pose: "sit", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "suitcase", x: 0.52, y: 0.82 } ],
        cap: { en: "Holiday tomorrow! Mumma has a list. A very, VERY long list.", hi: "कल से छुट्टियाँ! मम्मा के पास एक लिस्ट है। लंबी, बहुत लंबी लिस्ट।" },
        say: [ { who: 0, en: "Sunscreen, hats, snacks, towels... and this is list FOUR!", hi: "सनस्क्रीन, टोपी, नमकीन, तौलिये... और ये है लिस्ट नंबर चार!" } ] },
      { bg: "home", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "papa", pose: "stand", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "suitcase", x: 0.52, y: 0.82 } ],
        cap: { en: "Auggie packs his bag too. One carrot. Plop. Done!", hi: "ऑगी ने भी अपना बैग लगाया। एक गाजर। टप्प। हो गया!" },
        say: [ { who: 0, en: "All packed! One carrot. What else does a holiday need?", hi: "मेरी पैकिंग पूरी! एक गाजर। छुट्टी में और क्या चाहिए?" },
               { who: 1, en: "Mottu! Auggie finished packing before you!", hi: "मोटू! ऑगी की पैकिंग तो तुमसे पहले हो गई!" } ] },
      { bg: "home", chars: [ { id: "mumma", pose: "point", mood: "surprised", x: 0.3 }, { id: "auggie", pose: "think", mood: "surprised", x: 0.72, flip: true } ],
        say: [ { who: 0, en: "Your harness? Your bowl? Your water bottle? Your leash?", hi: "और तेरा हार्नेस? कटोरा? पानी की बोतल? पट्टा? वो कौन रखेगा?" },
               { who: 1, en: "Wait... they don't just magically appear?", hi: "अरे... वो सब अपने आप नहीं आ जाते?" } ] },
      { bg: "home", chars: [ { id: "auggie", pose: "lie", mood: "determined", x: 0.38 }, { id: "papa", pose: "stand", mood: "laugh", x: 0.78, flip: true } ], props: [ { id: "suitcase", x: 0.38, y: 0.85 } ],
        cap: { en: "Auggie's big plan: sit in the suitcase and pack EVERYTHING!", hi: "ऑगी का बड़ा प्लान: खुद सूटकेस में बैठ जाओ, सब पैक!" },
        say: [ { who: 1, en: "Mottu, it won't shut! It's full of Labrador!", hi: "मोटू, ये बंद ही नहीं हो रहा! इसमें तो पूरा लैब्राडोर ठुसा है!" } ],
        fx: { en: "SQUISH!", hi: "ठुस!" }, action: true },
      { bg: "home", chars: [ { id: "auggie", pose: "point", mood: "determined", x: 0.3 }, { id: "mumma", pose: "cheer", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "bowl", x: 0.5, y: 0.85 }, { id: "bottle", x: 0.58, y: 0.82 } ],
        cap: { en: "Then Auggie has an idea. His nose can read lists!", hi: "फिर ऑगी को सूझा: उसकी नाक भी लिस्ट पढ़ सकती है!" },
        say: [ { who: 0, en: "Harness under the sofa! Bowl behind the door!", hi: "हार्नेस सोफ़े के नीचे! कटोरा दरवाज़े के पीछे!" },
               { who: 1, en: "Tick, tick, tick! Your nose beats my lists!", hi: "टिक, टिक, टिक! तेरी नाक तो मेरी लिस्ट से भी तेज़!" } ],
        fx: { en: "SNIFF!", hi: "सूँ-सूँ!" }, action: true },
      { bg: "city", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.33 }, { id: "mumma", pose: "stand", mood: "laugh", x: 0.75, flip: true } ], props: [ { id: "car", x: 0.12 }, { id: "suitcase", x: 0.93 } ],
        cap: { en: "Morning! Auggie rides in the car, buckled into his harness.", hi: "सुबह हो गई! ऑगी कार में हार्नेस से बँधकर आराम से बैठा है।" },
        say: [ { who: 0, en: "Mumma! You packed MY carrot too?", hi: "मम्मा! आपने मेरी गाजर भी रख ली?" },
               { who: 1, en: "Of course! You're item number one on every list!", hi: "और क्या! हर लिस्ट में सबसे ऊपर तो तू ही है!" } ],
        fx: { en: "HA-HA-HA!", hi: "हा-हा-हा!" }, action: true }
    ]
  }
  ,

  // 124 — Goa beach: the sandcastle vs the sea
  {
    id: 124, age: "4-6", category: "holiday",
    title: { en: "The Castle That Wanted a Pool", hi: "स्विमिंग पूल वाला रेत का महल" },
    blurb: { en: "Every time Auggie builds a sandcastle, the sea knocks it flat. Can a Labrador outsmart the Arabian Sea?", hi: "ऑगी जब भी रेत का महल बनाता है, समंदर उसे गिरा देता है। क्या एक लैब्राडोर अरब सागर को मात दे पाएगा?" },
    moral: { en: "When you can't stop a problem, get clever and make friends with it.", hi: "जिस मुश्किल को रोक न सको, उससे दोस्ती करने का चालाक रास्ता ढूँढो।" },
    cover: { bg: "beach", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.35 }, { id: "papa", pose: "stand", mood: "laugh", x: 0.75, flip: true } ], props: [ { id: "sandcastle", x: 0.13 }, { id: "palm", x: 0.93 }, { id: "sun", x: 0.8, y: 0.12 } ], fx: { en: "SPLASH!", hi: "छपाक!" } },
    panels: [
      { bg: "beach", chars: [ { id: "auggie", pose: "stand", mood: "determined", x: 0.3 }, { id: "mumma", pose: "sit", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "umbrella", x: 0.9 }, { id: "palm", x: 0.07 }, { id: "sun", x: 0.5, y: 0.12 } ],
        cap: { en: "Goa! Hot sand, blue sea, and one Labrador with a big plan.", hi: "गोवा! गरम-गरम रेत, नीला समंदर, और एक लैब्राडोर का बड़ा प्लान।" },
        say: [ { who: 0, en: "Mumma, I'll build you the biggest castle in Goa!", hi: "मम्मा, मैं आपके लिए पूरे गोवा का सबसे बड़ा महल बनाऊँगा!" } ] },
      { bg: "beach", chars: [ { id: "auggie", pose: "sit", mood: "laugh", x: 0.3 }, { id: "papa", pose: "point", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "sandcastle", x: 0.5 } ],
        cap: { en: "Dig, pat, dig, pat. A tall castle! And Papa has a joke.", hi: "खोदो, थपको, खोदो, थपको। ऊँचा महल तैयार! और पापा का एक जोक भी।" },
        say: [ { who: 1, en: "Why's the sea so friendly? It keeps waving!", hi: "पता है समंदर खारा क्यों है? मछलियाँ दिन भर नमकीन खाती हैं!" },
               { who: 0, en: "Ha-ha! Papa, that's so bad it's good!", hi: "हा-हा! पापा, इतना बुरा जोक कि मज़ा आ गया!" } ] },
      { bg: "beach", chars: [ { id: "auggie", pose: "stand", mood: "angry", x: 0.42 } ], props: [ { id: "shell", x: 0.75, y: 0.88 } ],
        cap: { en: "Then a big wave rolls in. Whoosh! No more castle.", hi: "तभी आई एक बड़ी लहर। सर्र्र! महल ग़ायब।" },
        say: [ { who: 0, en: "Hey, sea! That was Mumma's castle!", hi: "ओए समंदर! वो मम्मा का महल था!", kind: "shout" } ],
        fx: { en: "WHOOSH!", hi: "सर्र्र!" }, action: true },
      { bg: "beach", chars: [ { id: "auggie", pose: "blast", mood: "surprised", x: 0.35 }, { id: "mumma", pose: "stand", mood: "laugh", x: 0.77, flip: true } ],
        cap: { en: "Auggie barks at the sea. The sea just splashes back.", hi: "ऑगी समंदर पर भौंका। समंदर ने बस छपाक से जवाब दे दिया।" },
        say: [ { who: 0, en: "It doesn't listen! Just like me at bath time.", hi: "ये तो सुनता ही नहीं! बिल्कुल मेरी तरह, नहाने के टाइम।" } ],
        fx: { en: "SPLASH!", hi: "छपाक!" }, action: true },
      { bg: "beach", chars: [ { id: "auggie", pose: "think", mood: "determined", x: 0.3 }, { id: "papa", pose: "stand", mood: "surprised", x: 0.72, flip: true } ], props: [ { id: "sandcastle", x: 0.5 } ],
        cap: { en: "Auggie thinks. The waves want to come in? So... let them!", hi: "ऑगी ने सोचा। लहरें अंदर आना चाहती हैं? तो आने दो!" },
        say: [ { who: 0, en: "I'll dig a moat. The sea can fill it!", hi: "मैं महल के चारों तरफ़ नहर खोदूँगा। पानी वहीं भरेगा!" },
               { who: 1, en: "A castle with its own swimming pool? Genius!", hi: "अपने स्विमिंग पूल वाला महल? वाह मेरे शेर!" } ] },
      { bg: "beach", chars: [ { id: "mumma", pose: "cheer", mood: "laugh", x: 0.22 }, { id: "auggie", pose: "lie", mood: "happy", x: 0.5, flip: true }, { id: "papa", pose: "sit", mood: "laugh", x: 0.8, flip: true } ], props: [ { id: "umbrella", x: 0.5 }, { id: "sandcastle", x: 0.07 }, { id: "bowl", x: 0.64, y: 0.88 } ],
        cap: { en: "The waves fill the moat. The castle stands! Papa sips coconut water.", hi: "लहरें नहर भरती हैं, और महल खड़ा का खड़ा! पापा नारियल पानी पी रहे हैं।" },
        say: [ { who: 0, en: "My castle has a pool! Cold water for my builder!", hi: "मेरे महल में पूल भी है! अब मेरे कारीगर के लिए ठंडा पानी!" },
               { who: 1, en: "Coconut for Papa. Cold water and shade for me!", hi: "नारियल पापा का। ठंडा पानी और छाँव मेरी!" } ],
        fx: { en: "SLURP!", hi: "गप-गप!" }, action: true }
    ]
  }
  ,

  // 125 — Hill station: the foggy morning in Ooty
  {
    id: 125, age: "4-6", category: "holiday",
    title: { en: "Who Stole the Mountains?", hi: "पहाड़ किसने चुराए?" },
    blurb: { en: "Auggie wakes up in Ooty and the mountains are gone! Is it a thief, or something sneakier?", hi: "ऊटी में ऑगी की आँख खुली तो पहाड़ ही ग़ायब! कोई चोर है, या कोई और शरारती?" },
    moral: { en: "When your eyes can't see the way, trust your nose and stay close.", hi: "जब आँखों को रास्ता न दिखे, तो नाक पर भरोसा करो और अपनों के पास रहो।" },
    cover: { bg: "mountains", chars: [ { id: "auggie", pose: "point", mood: "surprised", x: 0.33 }, { id: "papa", pose: "stand", mood: "laugh", x: 0.75, flip: true } ], props: [ { id: "cloud", x: 0.2, y: 0.3 }, { id: "cloud", x: 0.6, y: 0.22 }, { id: "tree", x: 0.92 } ], fx: { en: "WHOA!", hi: "अरे!" } },
    panels: [
      { bg: "mountains", chars: [ { id: "auggie", pose: "cheer", mood: "happy", x: 0.3 }, { id: "papa", pose: "point", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "tree", x: 0.07 }, { id: "sun", x: 0.88, y: 0.12 } ],
        cap: { en: "Holiday in the hills of Ooty! Big green mountains everywhere.", hi: "ऊटी की पहाड़ियों में छुट्टियाँ! चारों तरफ़ बड़े-बड़े हरे पहाड़।" },
        say: [ { who: 0, en: "Tomorrow I'll climb that one and wave at clouds!", hi: "कल मैं उस पहाड़ पर चढ़कर बादलों को टाटा करूँगा!" } ] },
      { bg: "mountains", chars: [ { id: "auggie", pose: "stand", mood: "scared", x: 0.33 }, { id: "papa", pose: "stand", mood: "sleepy", x: 0.75, flip: true } ], props: [ { id: "cloud", x: 0.15, y: 0.5 }, { id: "cloud", x: 0.55, y: 0.4 }, { id: "cloud", x: 0.9, y: 0.55 } ],
        cap: { en: "Next morning, everything is white. Soft, cold, white fog.", hi: "अगली सुबह सब सफ़ेद। ठंडी-ठंडी, रुई जैसी धुंध।" },
        say: [ { who: 0, en: "PAPA! Somebody stole the mountains!", hi: "पापा! कोई हमारे पहाड़ चुरा ले गया!", kind: "shout" } ],
        fx: { en: "WHOA!", hi: "हाय राम!" }, action: true },
      { bg: "mountains", chars: [ { id: "papa", pose: "point", mood: "laugh", x: 0.3 }, { id: "auggie", pose: "think", mood: "determined", x: 0.72, flip: true } ], props: [ { id: "cloud", x: 0.5, y: 0.35 }, { id: "cloud", x: 0.1, y: 0.55 } ],
        say: [ { who: 0, en: "Relax! They're just playing hide-and-seek in the mist!", hi: "अरे घबरा मत! पहाड़ धुंध के पीछे छुपन-छुपाई खेल रहे हैं!" },
               { who: 1, en: "Hide-and-seek? Then I'll FIND them!", hi: "छुपन-छुपाई? तो मैं ढूँढ के ही रहूँगा!" } ] },
      { bg: "mountains", chars: [ { id: "auggie", pose: "stand", mood: "surprised", x: 0.38 }, { id: "mumma", pose: "stand", mood: "laugh", x: 0.78, flip: true } ], props: [ { id: "cloud", x: 0.2, y: 0.45 }, { id: "cloud", x: 0.6, y: 0.5 } ],
        cap: { en: "First, Auggie tries to catch the fog. With his mouth.", hi: "पहले ऑगी ने धुंध पकड़ने की कोशिश की। मुँह से!" },
        say: [ { who: 0, en: "Chomp! Fog tastes like... cold nothing!", hi: "गप्प! धुंध का स्वाद... ठंडा-ठंडा कुछ नहीं!" } ],
        fx: { en: "CHOMP!", hi: "गप्प!" }, action: true },
      { bg: "mountains", chars: [ { id: "auggie", pose: "point", mood: "determined", x: 0.3 }, { id: "mumma", pose: "stand", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "cloud", x: 0.5, y: 0.4 }, { id: "bush", x: 0.08 } ],
        cap: { en: "Auggie can't see a thing. But his nose can!", hi: "आँखों को कुछ नहीं दिख रहा। पर नाक को सब दिखता है!" },
        say: [ { who: 0, en: "Hold my leash tight, Mumma! Tea stall this way!", hi: "मम्मा, पट्टा कसकर पकड़ो, पास रहो! चाय की दुकान इधर है!" },
               { who: 1, en: "Lead on, my furry little map!", hi: "चल मेरे सूँघू राजा, रास्ता दिखा!" } ] },
      { bg: "mountains", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "mumma", pose: "cheer", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "sun", x: 0.5, y: 0.12 }, { id: "tree", x: 0.92 } ],
        cap: { en: "The sun comes out. The fog floats away. Mountains!", hi: "धूप निकली, धुंध उड़ गई। और लो, पहाड़ वापस!" },
        say: [ { who: 0, en: "Found you, mountains! I win hide-and-seek!", hi: "मिल गए पहाड़! छुपन-छुपाई में मैं जीता!", kind: "shout" },
               { who: 1, en: "Best tea, best view, and the best nose!", hi: "बढ़िया चाय, बढ़िया नज़ारा, और सबसे बढ़िया नाक!" } ],
        fx: { en: "TA-DA!", hi: "टा-डा!" }, action: true }
    ]
  }
  ,

  // 126 — The overnight train and the upper berth
  {
    id: 126, age: "6-10", category: "holiday",
    title: { en: "Who Gets the Top Berth?", hi: "ऊपर वाली बर्थ किसकी?" },
    blurb: { en: "Auggie wants the top berth on the overnight train, but Mausi grabs it first. So why is Mausi still awake at midnight?", hi: "ऑगी को रात वाली ट्रेन में ऊपर की बर्थ चाहिए थी, पर मौसी ने पहले ले ली। फिर आधी रात को मौसी जाग क्यों रही हैं?" },
    moral: { en: "The best seat on any journey is beside a friend who needs you.", hi: "किसी भी सफ़र में सबसे अच्छी सीट वही है, जो ज़रूरत वाले दोस्त के पास हो।" },
    cover: { bg: "station", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "mausi", pose: "point", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "suitcase", x: 0.08 }, { id: "clock", x: 0.9, y: 0.15 } ], fx: { en: "TOOT!", hi: "छुक-छुक!" } },
    panels: [
      { bg: "station", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "mumma", pose: "point", mood: "determined", x: 0.72, flip: true } ], props: [ { id: "suitcase", x: 0.08 }, { id: "clock", x: 0.9, y: 0.15 } ],
        cap: { en: "9 PM, Chamakpur Station. The overnight train to Udaipur! Papa has booked a whole cabin.", hi: "रात के नौ बजे, चमकपुर स्टेशन। उदयपुर वाली रात की ट्रेन! पापा ने पूरा केबिन बुक किया है।" },
        say: [ { who: 0, en: "A bedroom on wheels?! I call the TOP berth!", hi: "पहियों वाला बेडरूम?! ऊपर वाली बर्थ मेरी!", kind: "shout" },
               { who: 1, en: "Leash first, mister! Platforms are busy and trains are huge.", hi: "पहले पट्टा, जनाब! प्लेटफ़ॉर्म पर भीड़ है और ट्रेन बहुत बड़ी।" } ] },
      { bg: "bedroom", chars: [ { id: "mausi", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "auggie", pose: "sit", mood: "sad", x: 0.72, flip: true } ], props: [ { id: "camera", x: 0.5, y: 0.3 } ],
        cap: { en: "Inside the cabin, Mausi zips up the little ladder like a squirrel.", hi: "केबिन के अंदर मौसी गिलहरी की तरह फटाफट सीढ़ी चढ़ गईं।" },
        say: [ { who: 0, en: "Top berth is mine! Hold that sulky pose. Selfie!", hi: "ऊपर वाली मेरी! मुँह ऐसे ही फुलाए रखो। सेल्फ़ी!" },
               { who: 1, en: "But the top is closer to the stars...", hi: "पर ऊपर से तो तारे पास दिखते हैं...", kind: "whisper" } ] },
      { bg: "bedroom", chars: [ { id: "papa", pose: "lie", mood: "surprised", x: 0.3 }, { id: "auggie", pose: "lie", mood: "laugh", x: 0.7, flip: true } ],
        cap: { en: "Bedtime. Auggie tries the ladder. One paw. Two paws. Three paws... oops.", hi: "सोने का टाइम। ऑगी सीढ़ी पर चढ़ा। एक पंजा। दो पंजे। तीन पंजे... धड़ाम!" },
        say: [ { who: 0, en: "Auggie! I ordered bed tea, not a bed Labrador!", hi: "ऑगी! मैंने बेड-टी माँगी थी, बेड-लैब्राडोर नहीं!" },
               { who: 1, en: "The ladder moved! ...Okay, fine, I moved.", hi: "सीढ़ी हिल गई! ...अच्छा बाबा, मैं हिल गया।" } ],
        fx: { en: "THUD!", hi: "धड़ाम!" }, action: true },
      { bg: "bedroom", chars: [ { id: "papa", pose: "sit", mood: "happy", x: 0.3 }, { id: "auggie", pose: "lie", mood: "sad", x: 0.72, flip: true } ],
        say: [ { who: 0, en: "Big dogs sleep down low, beta. If the train jolts, you stay safe.", hi: "बड़े कुत्ते नीचे सोते हैं, बेटा। ट्रेन झटका भी खाए, तो तू सुरक्षित रहेगा।" },
               { who: 1, en: "Down low is for boring dogs. Great. Now I'm a boring dog.", hi: "नीचे तो बोरिंग कुत्ते सोते हैं। वाह। अब मैं भी बोरिंग हो गया।" } ] },
      { bg: "bedroom", chars: [ { id: "auggie", pose: "lie", mood: "surprised", x: 0.3 }, { id: "mausi", pose: "lie", mood: "scared", x: 0.72, flip: true } ], props: [ { id: "star", x: 0.15, y: 0.12 }, { id: "star", x: 0.85, y: 0.1 } ],
        cap: { en: "Midnight. The train rushes through the dark. Then a tiny voice floats down from above...", hi: "आधी रात। ट्रेन अँधेरे में दौड़ रही है, खटाक-खटाक। तभी ऊपर से एक धीमी-सी आवाज़ आई..." },
        say: [ { who: 1, en: "Auggie? You awake? It's so high and so wobbly up here.", hi: "ऑगी? जाग रहे हो? ऊपर सब इतना हिल रहा है... डर लग रहा है।", kind: "whisper" },
               { who: 0, en: "Mausi is scared? Mausi is NEVER scared!", hi: "मौसी डर रही हैं? मौसी तो कभी नहीं डरतीं!", kind: "think" } ],
        fx: { en: "CLACK!", hi: "खटाक!" }, action: true },
      { bg: "bedroom", chars: [ { id: "auggie", pose: "sit", mood: "determined", x: 0.3 }, { id: "mausi", pose: "lie", mood: "happy", x: 0.72, flip: true } ],
        say: [ { who: 0, en: "I can't climb up. But hold my ear. It's the softest thing on this train.", hi: "मैं ऊपर नहीं आ सकता। पर मेरा कान पकड़ लो। पूरी ट्रेन में इससे मुलायम कुछ नहीं।" },
               { who: 1, en: "Oh, it IS soft! Like holding a warm, fluffy chapati.", hi: "अरे, सच में! जैसे गरमा-गरम फूली रोटी पकड़ी हो।" } ] },
      { bg: "bedroom", chars: [ { id: "auggie", pose: "lie", mood: "sleepy", x: 0.3 }, { id: "mausi", pose: "lie", mood: "sleepy", x: 0.72, flip: true } ], props: [ { id: "star", x: 0.5, y: 0.1 } ],
        cap: { en: "They count carrots together until the rocking train feels like a cradle.", hi: "दोनों मिलकर गाजरें गिनते रहे, और हिलती ट्रेन झूले जैसी लगने लगी।" },
        say: [ { who: 0, en: "Ninety-eight carrots... ninety-nine carrots... chhuk-chhuk...", hi: "अट्ठानवे गाजर... निन्यानवे गाजर... छुक-छुक...", kind: "whisper" },
               { who: 1, en: "Night Guard Auggie. Best berth-buddy ever.", hi: "चौकीदार ऑगी। दुनिया का सबसे प्यारा बर्थ-दोस्त।", kind: "whisper" } ],
        fx: { en: "ZZZ!", hi: "खर्र!" }, action: true },
      { bg: "station", chars: [ { id: "mausi", pose: "cheer", mood: "laugh", x: 0.22 }, { id: "auggie", pose: "cheer", mood: "happy", x: 0.5, flip: true }, { id: "mumma", pose: "stand", mood: "laugh", x: 0.8, flip: true } ],
        cap: { en: "Good morning, Udaipur! Mausi tells everyone about her brave night guard.", hi: "गुड मॉर्निंग, उदयपुर! मौसी सबको अपने बहादुर चौकीदार के बारे में बता रही हैं।" },
        say: [ { who: 1, en: "I didn't get the top berth. I got a better job.", hi: "ऊपर वाली बर्थ तो नहीं मिली। पर उससे बढ़िया काम मिल गया।" },
               { who: 0, en: "Hold that pose, Night Guard! Hero selfie!", hi: "पोज़ पकड़ो, चौकीदार साहब! हीरो वाली सेल्फ़ी!" } ] }
    ]
  }
  ,

  // 127 — Village holiday at Nanu's: bullock cart, well and the King Mango
  {
    id: 127, age: "6-10", category: "holiday",
    title: { en: "Auggie and the King Mango", hi: "ऑगी और राजा आम" },
    blurb: { en: "The biggest mango in Nanu's village hangs at the very top. Can a Labrador who hates waiting ever get it?", hi: "नानू के गाँव का सबसे बड़ा आम सबसे ऊँची डाल पर लटका है। जिस लैब्राडोर से इंतज़ार नहीं होता, क्या उसे वो आम मिलेगा?" },
    moral: { en: "Good things, like mangoes, taste sweeter when we wait for them.", hi: "आम हो या कोई भी अच्छी चीज़, इंतज़ार के बाद और मीठी लगती है।" },
    cover: { bg: "village", chars: [ { id: "auggie", pose: "think", mood: "surprised", x: 0.3 }, { id: "nanu", pose: "point", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "tree", x: 0.52 }, { id: "mango", x: 0.52, y: 0.18 }, { id: "house", x: 0.93 } ], fx: { en: "THUD!", hi: "धप्प!" } },
    panels: [
      { bg: "village", chars: [ { id: "nanu", pose: "wave", mood: "happy", x: 0.22 }, { id: "cow", pose: "stand", mood: "happy", x: 0.5 }, { id: "auggie", pose: "stand", mood: "surprised", x: 0.8, flip: true } ], props: [ { id: "house", x: 0.05 } ],
        cap: { en: "Summer holiday at Nanu's village! A bullock cart comes rattling down the dusty lane.", hi: "नानू के गाँव में गर्मी की छुट्टियाँ! धूल भरी गली में खड़-खड़ करती बैलगाड़ी आई।" },
        say: [ { who: 0, en: "Welcome, Auggie! Shyamu the bullock will take us home.", hi: "आ गया मेरा ऑगी! श्यामू बैल हमें घर तक ले चलेगा।" },
               { who: 2, en: "A car that runs on grass? What's the mileage?", hi: "घास से चलने वाली गाड़ी? एक पूली में कितने किलोमीटर?" } ] },
      { bg: "village", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "cow", pose: "stand", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "house", x: 0.93 }, { id: "tree", x: 0.06 } ],
        cap: { en: "Bump, bump, BUMP! Auggie's ears flap like two flags.", hi: "धचक, धचक, धचक! ऑगी के कान दो झंडों की तरह फड़फड़ा रहे हैं।" },
        say: [ { who: 1, en: "Moo! Hold on to your ears, city dog!", hi: "म्बाँ! कान सँभाल के, शहरी बाबू!" },
               { who: 0, en: "This beats a car! It has a bullock engine!", hi: "ये तो कार से भी बढ़िया! इसमें तो बैल वाला इंजन है!" } ],
        fx: { en: "BUMP!", hi: "धचक!" }, action: true },
      { bg: "village", chars: [ { id: "nanu", pose: "stand", mood: "happy", x: 0.3 }, { id: "auggie", pose: "blast", mood: "surprised", x: 0.72, flip: true } ],
        cap: { en: "Nanu pulls water from the old well. Auggie woofs into it from a safe step away.", hi: "नानू पुराने कुएँ से पानी खींच रहे हैं। ऑगी ने थोड़ी दूर से कुएँ में 'भौं' किया।" },
        say: [ { who: 1, en: "Nanu! A dog lives in the well! He copies me!", hi: "नानू! कुएँ में एक कुत्ता रहता है! मेरी नकल उतारता है!", kind: "shout" },
               { who: 0, en: "That's an echo, beta. Sound bounces back. And we never lean over wells!", hi: "वो गूँज है बेटा, आवाज़ टकराकर लौट आती है। और कुएँ पर कभी झुकते नहीं!" } ],
        fx: { en: "WOOF!", hi: "भौं!" }, action: true },
      { bg: "village", chars: [ { id: "auggie", pose: "point", mood: "determined", x: 0.28 }, { id: "nanu", pose: "stand", mood: "laugh", x: 0.75, flip: true } ], props: [ { id: "tree", x: 0.52 }, { id: "mango", x: 0.52, y: 0.15 } ],
        cap: { en: "At the very top of Nanu's mango tree hangs one giant mango.", hi: "नानू के आम के पेड़ की सबसे ऊँची डाल पर लटका है एक बड़ा-सा आम।" },
        say: [ { who: 0, en: "That's the King Mango. And today, it's MINE!", hi: "वो है राजा आम। और आज वो मेरा है!" },
               { who: 1, en: "Not ripe yet, beta. Every day on the tree, it gets sweeter!", hi: "अभी कच्चा है बेटा। पेड़ पर हर दिन वो और मीठा होता जाता है!" } ] },
      { bg: "village", chars: [ { id: "auggie", pose: "cheer", mood: "determined", x: 0.35 }, { id: "monkey", pose: "sit", mood: "laugh", x: 0.78, flip: true } ], props: [ { id: "tree", x: 0.6 }, { id: "mango", x: 0.6, y: 0.12 } ],
        cap: { en: "Wait? Labradors don't DO waiting! Auggie jumps. Auggie shakes the tree. Auggie barks.", hi: "इंतज़ार? लैब्राडोर इंतज़ार नहीं करते! ऑगी कूदा। पेड़ हिलाया। भौंका भी।" },
        say: [ { who: 0, en: "Fall down, King Mango! ...Please? I'll give you a carrot!", hi: "गिर जा, राजा आम! ...प्लीज़? तुझे एक गाजर दूँगा!" },
               { who: 1, en: "Ha! Shouting only brings down leaves, doggy!", hi: "हा-हा! चिल्लाने से तो बस पत्ते गिरते हैं, कुत्ते भाई!" } ] },
      { bg: "village", chars: [ { id: "auggie", pose: "sit", mood: "sad", x: 0.3 }, { id: "nanu", pose: "sit", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "tree", x: 0.52 } ],
        say: [ { who: 1, en: "I planted this tree when your Mumma was tiny. Its first mango took five years.", hi: "ये पेड़ मैंने तब लगाया था जब तेरी मम्मा छोटी-सी थी। पहला आम पाँच साल बाद आया।" },
               { who: 0, en: "Five YEARS? And I couldn't wait five minutes.", hi: "पाँच साल?! और मुझसे पाँच मिनट नहीं रुका गया।" } ] },
      { bg: "village", chars: [ { id: "auggie", pose: "lie", mood: "surprised", x: 0.4 } ], props: [ { id: "tree", x: 0.6 }, { id: "mango", x: 0.62, y: 0.85 } ],
        cap: { en: "So Auggie does the hardest trick ever. He waits. And naps. Two whole days later...", hi: "तो ऑगी ने सबसे मुश्किल करतब किया: इंतज़ार। और झपकी। पूरे दो दिन बाद..." },
        say: [ { who: 0, en: "Nanu! I waited, and the mango came to ME!", hi: "नानू! मैंने इंतज़ार किया, और आम खुद चलकर मेरे पास आ गया!", kind: "shout" } ],
        fx: { en: "THUD!", hi: "धप्प!" }, action: true },
      { bg: "village", chars: [ { id: "mumma", pose: "stand", mood: "happy", x: 0.22 }, { id: "auggie", pose: "sit", mood: "laugh", x: 0.5 }, { id: "nanu", pose: "sit", mood: "laugh", x: 0.8, flip: true } ], props: [ { id: "mango", x: 0.36, y: 0.75 } ],
        cap: { en: "Mumma cuts the King Mango. A little piece for Auggie: no peel, no seed.", hi: "मम्मा ने राजा आम काटा। ऑगी के लिए छोटा-सा टुकड़ा: न छिलका, न गुठली।" },
        say: [ { who: 1, en: "It tastes like two whole days of sunshine!", hi: "इसमें तो पूरे दो दिन की धूप का स्वाद है!" },
               { who: 2, en: "Science fact: waiting makes everything sweeter. Not proven. But true!", hi: "विज्ञान की बात: इंतज़ार से सब मीठा हो जाता है। साबित नहीं हुआ, पर सच है!" } ] }
    ]
  }
  ,

  // 128 — Rainy day: the trip is cancelled, so the holiday comes home
  {
    id: 128, age: "6-10", category: "holiday",
    title: { en: "Holiday in the Living Room", hi: "ड्रॉइंग रूम में छुट्टियाँ" },
    blurb: { en: "Bags packed, harness on... then the sky goes BOOM and the trip is cancelled. Can Auggie save the holiday without leaving home?", hi: "बैग तैयार, हार्नेस पहन लिया... तभी आसमान गरजा और ट्रिप कैंसल! क्या ऑगी घर से निकले बिना छुट्टी बचा पाएगा?" },
    moral: { en: "A holiday isn't a place; it's being together and making the fun yourselves.", hi: "छुट्टी कोई जगह नहीं होती; अपनों के साथ मिलकर बनाया मज़ा ही असली छुट्टी है।" },
    cover: { bg: "home", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "mumma", pose: "cheer", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "umbrella", x: 0.5 }, { id: "sandcastle", x: 0.08 }, { id: "sun", x: 0.88, y: 0.12 } ], fx: { en: "YAY!", hi: "याय!" } },
    panels: [
      { bg: "home", chars: [ { id: "mumma", pose: "cheer", mood: "happy", x: 0.3 }, { id: "auggie", pose: "cheer", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "suitcase", x: 0.5, y: 0.85 }, { id: "suitcase", x: 0.08 } ],
        cap: { en: "Bags packed. Harness on. Off to Puri beach in ten minutes!", hi: "बैग तैयार। हार्नेस पहन लिया। दस मिनट में पुरी बीच की ओर रवाना!" },
        say: [ { who: 0, en: "Every list ticked! Three whole weeks of planning, done!", hi: "हर लिस्ट पर टिक! पूरे तीन हफ़्ते की प्लानिंग, पूरी!" },
               { who: 1, en: "Seven carrots packed! One for every day, plus a spare!", hi: "सात गाजरें पैक! हर दिन की एक, और एक एक्स्ट्रा!" } ] },
      { bg: "rain", chars: [ { id: "papa", pose: "stand", mood: "sad", x: 0.3 }, { id: "auggie", pose: "stand", mood: "surprised", x: 0.72, flip: true } ], props: [ { id: "cloud", x: 0.2, y: 0.12 }, { id: "cloud", x: 0.75, y: 0.1 } ],
        cap: { en: "Then the sky goes BOOM. Heavy rain, flooded roads. The trip is cancelled.", hi: "तभी आसमान गरजा। मूसलाधार बारिश, सड़कों पर पानी ही पानी। ट्रिप कैंसल।" },
        say: [ { who: 0, en: "Sorry, team. The roads are closed. No holiday this time.", hi: "सॉरी टीम। सड़कें बंद हैं। इस बार छुट्टी नहीं हो पाएगी।" },
               { who: 1, en: "NO HOLIDAY?! This is a seven-carrot disaster!", hi: "छुट्टी नहीं?! ये तो सात-गाजर वाली मुसीबत है!", kind: "shout" } ],
        fx: { en: "BOOM!", hi: "कड़ाक!" }, action: true },
      { bg: "home", chars: [ { id: "auggie", pose: "lie", mood: "sad", x: 0.3 }, { id: "mumma", pose: "sit", mood: "sad", x: 0.72, flip: true } ], props: [ { id: "book", x: 0.55, y: 0.8 } ],
        cap: { en: "Auggie flops on the sofa to sulk. Then he sees Mumma quietly folding up her list.", hi: "ऑगी मुँह फुलाकर सोफ़े पर पसर गया। फिर उसने देखा, मम्मा चुपचाप अपनी लिस्ट मोड़ रही हैं।" },
        say: [ { who: 0, en: "I'm not moving. I'm a sad rug now.", hi: "मैं नहीं हिलूँगा। अब मैं एक उदास दरी हूँ।" },
               { who: 1, en: "Three weeks of lists... all washed away.", hi: "तीन हफ़्ते की लिस्टें... सब बारिश में बह गईं।", kind: "whisper" } ] },
      { bg: "home", chars: [ { id: "auggie", pose: "stand", mood: "determined", x: 0.3 }, { id: "mumma", pose: "sit", mood: "surprised", x: 0.72, flip: true } ],
        cap: { en: "Auggie jumps off the sofa. Sad rugs never fixed anything.", hi: "ऑगी सोफ़े से कूद पड़ा। उदास दरी बनने से आज तक कुछ ठीक नहीं हुआ।" },
        say: [ { who: 0, en: "Mumma, I sulked for me. Now I'll fix it for you! Beach, come HERE!", hi: "मम्मा, अब तक मैं अपने लिए रूठा था। अब आपके लिए कुछ करूँगा! बीच, इधर आओ!" },
               { who: 1, en: "The beach? In my drawing room? Hai Ram...", hi: "बीच? मेरे ड्रॉइंग रूम में? हाय राम..." } ] },
      { bg: "home", chars: [ { id: "auggie", pose: "stand", mood: "laugh", x: 0.3 }, { id: "papa", pose: "lie", mood: "surprised", x: 0.72, flip: true } ], props: [ { id: "bowl", x: 0.5, y: 0.88 }, { id: "puddle", x: 0.55, y: 0.92 } ],
        cap: { en: "Step one: the sea. Auggie tips over his water bowl.", hi: "पहला कदम: समंदर। ऑगी ने अपना पानी का कटोरा उलट दिया।" },
        say: [ { who: 1, en: "Lovely sea, Auggie! I just surfed straight onto the sofa!", hi: "वाह रे समंदर! मैं तो फिसलकर सीधा सोफ़े पर सर्फ़िंग कर आया!" },
               { who: 0, en: "Hmm. Too small for a sea. Too big for a floor.", hi: "हम्म। समंदर के लिए छोटा, फ़र्श के लिए बहुत बड़ा।" } ],
        fx: { en: "SPLOSH!", hi: "छपाक!" }, action: true },
      { bg: "airport", chars: [ { id: "mausi", pose: "point", mood: "laugh", x: 0.3 }, { id: "auggie", pose: "stand", mood: "determined", x: 0.72, flip: true } ], props: [ { id: "plane", x: 0.5, y: 0.12 }, { id: "suitcase", x: 0.92 } ],
        cap: { en: "Plan B! Mop the floor. Mausi draws boarding passes. The front door becomes... AUGGIE AIRLINES!", hi: "प्लान बी! पहले पोंछा। फिर मौसी ने बोर्डिंग पास बनाए। घर का दरवाज़ा बन गया... ऑगी एयरलाइंस!" },
        say: [ { who: 0, en: "Captain Auggie, hold that pose! Pilot selfie!", hi: "कैप्टन ऑगी, पोज़ पकड़ो! पायलट वाली सेल्फ़ी!" },
               { who: 1, en: "Pilot speaking! Next stop: Blue Bedsheet Beach. Snacks are free!", hi: "पायलट बोल रहा हूँ! अगला स्टॉप: नीली चादर बीच। नाश्ता मुफ़्त!" } ] },
      { bg: "beach", chars: [ { id: "papa", pose: "point", mood: "laugh", x: 0.2 }, { id: "auggie", pose: "lie", mood: "laugh", x: 0.5 }, { id: "mumma", pose: "sit", mood: "laugh", x: 0.8, flip: true } ], props: [ { id: "sandcastle", x: 0.35 }, { id: "umbrella", x: 0.93 }, { id: "sun", x: 0.12, y: 0.12 } ],
        cap: { en: "A blue bedsheet sea. A cushion sandcastle. A lamp for a sun. It feels just like Puri!", hi: "नीली चादर का समंदर। तकियों का रेत-महल। लैंप का सूरज। बिल्कुल पुरी जैसा लग रहा है!" },
        say: [ { who: 0, en: "Five stars! Best beach ever. Not one grain of sand in my shoes!", hi: "पाँच सितारे! सबसे बढ़िया बीच। जूतों में रेत का एक दाना नहीं!" },
               { who: 2, en: "HA-HA-HA! Mittsy, that one was actually funny!", hi: "हा-हा-हा! मिट्सी, ये वाला तो सच में मज़ेदार था!" } ],
        fx: { en: "HA-HA!", hi: "हा-हा!" }, action: true },
      { bg: "home", chars: [ { id: "mumma", pose: "sit", mood: "happy", x: 0.3 }, { id: "auggie", pose: "cheer", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "book", x: 0.5, y: 0.8 } ],
        cap: { en: "That night, Mumma writes a brand-new list. It has only one line.", hi: "उस रात मम्मा ने एक नई लिस्ट लिखी। उसमें बस एक ही लाइन थी।" },
        say: [ { who: 0, en: "'Holiday: all of us, together.' Tick! Best trip ever, Auggie.", hi: "'छुट्टी: हम सब, एक साथ।' टिक! सबसे बढ़िया ट्रिप, ऑगी।" },
               { who: 1, en: "And seven carrots! ...Okay, five. The pilot got hungry.", hi: "और सात गाजरें! ...अच्छा, पाँच। पायलट को भूख लग गई थी।" } ] }
    ]
  }
  ,

  // ===================== AUGGIE AND FOREST =====================

  // 129 — Picnic at the edge of the forest: Chintu the squirrel
  {
    id: 129, age: "4-6", category: "forest",
    title: { en: "Hello, Chintu Squirrel!", hi: "नमस्ते, चिंटू गिलहरी!" },
    blurb: { en: "Auggie wants to share his apple with a squirrel. So why does Mumma say no?", hi: "ऑगी अपना सेब गिलहरी के साथ बाँटना चाहता है। फिर मम्मा मना क्यों कर रही हैं?" },
    moral: { en: "Love wild animals by watching quietly, never feeding them, and leaving no trash.", hi: "जंगली जानवरों से प्यार ऐसे करो: चुपचाप देखो, खाना मत दो, और कचरा मत छोड़ो।" },
    cover: { bg: "forest", chars: [ { id: "auggie", pose: "sit", mood: "happy", x: 0.3 }, { id: "squirrel", pose: "stand", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "tree", x: 0.88 }, { id: "apple", x: 0.5, y: 0.85 } ], fx: { en: "CHIK-CHIK!", hi: "चिक-चिक!" } },
    panels: [
      { bg: "forest", chars: [ { id: "mumma", pose: "point", mood: "happy", x: 0.3 }, { id: "auggie", pose: "cheer", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "tree", x: 0.07 }, { id: "bottle", x: 0.5, y: 0.85 } ],
        cap: { en: "Picnic day at the edge of Hara-Bhara Forest!", hi: "हरा-भरा जंगल के किनारे पिकनिक का दिन!" },
        say: [ { who: 0, en: "Mat, apples, water, leash, trash bag. List done!", hi: "चटाई, सेब, पानी, पट्टा, कचरे का थैला। लिस्ट पूरी!" } ] },
      { bg: "forest", chars: [ { id: "auggie", pose: "point", mood: "surprised", x: 0.3 }, { id: "squirrel", pose: "stand", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "tree", x: 0.88 }, { id: "apple", x: 0.45, y: 0.85 } ],
        say: [ { who: 1, en: "Chik-chik! Who's this giant yellow cushion?", hi: "चिक-चिक! ये पीला-पीला बड़ा गद्दा कौन है?" },
               { who: 0, en: "A squirrel! Here, have half my apple!", hi: "गिलहरी! आओ, मेरा सेब आधा-आधा!" } ] },
      { bg: "forest", chars: [ { id: "mumma", pose: "stand", mood: "happy", x: 0.3 }, { id: "auggie", pose: "sit", mood: "sad", x: 0.72, flip: true } ], props: [ { id: "apple", x: 0.5, y: 0.85 } ],
        say: [ { who: 0, en: "No, baby! Wild animals find their own food.", hi: "ना बेटा! जंगली जानवर अपना खाना खुद ढूँढते हैं। हम नहीं खिलाते।" },
               { who: 1, en: "Not even one tiny bite? ...Okay. No feeding.", hi: "एक छोटा-सा टुकड़ा भी नहीं? ...अच्छा बाबा। नहीं खिलाऊँगा।" } ] },
      { bg: "forest", chars: [ { id: "auggie", pose: "run", mood: "surprised", x: 0.38 }, { id: "squirrel", pose: "stand", mood: "laugh", x: 0.8, flip: true } ], props: [ { id: "tree", x: 0.55 } ],
        cap: { en: "Auggie runs round the tree to say hi. So does his leash!", hi: "ऑगी हेलो बोलने पेड़ के चारों ओर भागा। उसका पट्टा भी!" },
        say: [ { who: 0, en: "Mumma! The tree tied me up!", hi: "मम्मा! पेड़ ने मुझे बाँध लिया!", kind: "shout" } ],
        fx: { en: "TWIRL!", hi: "गोल-गोल!" }, action: true },
      { bg: "forest", chars: [ { id: "auggie", pose: "lie", mood: "happy", x: 0.3 }, { id: "squirrel", pose: "stand", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "tree", x: 0.92 } ],
        cap: { en: "Untangled, Auggie lies very still. Chintu comes down all by himself.", hi: "पट्टा खुला तो ऑगी चुपचाप लेट गया। चिंटू अपने आप नीचे उतर आया।" },
        say: [ { who: 0, en: "Hi, Chintu. I'll just watch. No touching.", hi: "हाय चिंटू। मैं बस देखूँगा। पंजा नहीं लगाऊँगा, पक्का।", kind: "whisper" },
               { who: 1, en: "You're the quietest cushion I ever met!", hi: "तुम तो सबसे शांत गद्दे निकले!" } ] },
      { bg: "forest", chars: [ { id: "mumma", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "auggie", pose: "point", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "dustbin", x: 0.5, y: 0.85 }, { id: "tree", x: 0.07 } ],
        cap: { en: "Picnic over. The wind steals a wrapper. Auggie's nose finds it!", hi: "पिकनिक ख़त्म। हवा एक रैपर उड़ा ले गई। ऑगी की नाक ने ढूँढ निकाला!" },
        say: [ { who: 1, en: "All packed! We leave only pawprints!", hi: "सब समेट लिया! यहाँ बस पंजों के निशान छोड़ेंगे!" },
               { who: 0, en: "HA-HA! That's my tidy boy!", hi: "हा-हा! ये है मेरा सफ़ाई वाला राजा बेटा!" } ],
        fx: { en: "SNIFF!", hi: "सूँ-सूँ!" }, action: true }
    ]
  }
  ,

  // 130 — A lost puppy in the woods
  {
    id: 130, age: "4-6", category: "forest",
    title: { en: "Where Is Golu's Amma?", hi: "गोलू की अम्मा कहाँ?" },
    blurb: { en: "A tiny puppy is crying in the woods. Can Auggie's nose find his mother before sunset?", hi: "जंगल में एक नन्हा पिल्ला रो रहा है। क्या सूरज ढलने से पहले ऑगी की नाक उसकी अम्मा को ढूँढ पाएगी?" },
    moral: { en: "When someone small is scared, a kind friend helps them find their way home.", hi: "जब कोई छोटा डरा हो, तो अच्छा दोस्त उसे घर का रास्ता ढूँढने में मदद करता है।" },
    cover: { bg: "forest", chars: [ { id: "auggie", pose: "point", mood: "determined", x: 0.3 }, { id: "moti", pose: "sit", mood: "sad", x: 0.72, flip: true, s: 0.6 } ], props: [ { id: "tree", x: 0.08 }, { id: "bush", x: 0.9 } ], fx: { en: "SNIFF!", hi: "सूँ-सूँ!" } },
    panels: [
      { bg: "forest", chars: [ { id: "auggie", pose: "stand", mood: "laugh", x: 0.3 }, { id: "papa", pose: "point", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "tree", x: 0.06 }, { id: "tree", x: 0.94 } ],
        cap: { en: "Sunday walk in the woods. Auggie's on his leash, nose busy.", hi: "जंगल में इतवार की सैर। ऑगी पट्टे में, और नाक काम पर।" },
        say: [ { who: 1, en: "Why do trees never get lost? They're always rooted!", hi: "पेड़ कभी खोते क्यों नहीं? क्योंकि उनकी जड़ें पक्की होती हैं!" } ] },
      { bg: "forest", chars: [ { id: "auggie", pose: "think", mood: "determined", x: 0.3 }, { id: "moti", pose: "sit", mood: "sad", x: 0.72, flip: true, s: 0.6 } ], props: [ { id: "bush", x: 0.85 } ],
        cap: { en: "Then Auggie's ears hear a tiny sound. Eee... eee...", hi: "तभी ऑगी के कानों में एक पतली-सी आवाज़ आई। कूँ... कूँ..." },
        say: [ { who: 1, en: "I'm Golu. I lost my Amma!", hi: "मैं गोलू हूँ। मेरी अम्मा खो गई!" },
               { who: 0, en: "Don't cry, little one. My nose finds everything!", hi: "रो मत, छोटू। मेरी नाक सब ढूँढ लेती है!" } ] },
      { bg: "forest", chars: [ { id: "moti", pose: "sit", mood: "sad", x: 0.15, s: 0.6 }, { id: "auggie", pose: "stand", mood: "determined", x: 0.45 }, { id: "papa", pose: "stand", mood: "happy", x: 0.78, flip: true } ],
        say: [ { who: 1, en: "Papa, hold my leash tight. We're finding his Amma!", hi: "पापा, पट्टा कसकर पकड़ो। हम इसकी अम्मा ढूँढेंगे!" },
               { who: 2, en: "Team Sniff, go! I'll carry Golu.", hi: "टीम सूँघू, चलो! गोलू को मैं गोदी में ले लेता हूँ।" } ] },
      { bg: "forest", chars: [ { id: "auggie", pose: "point", mood: "surprised", x: 0.3 }, { id: "peacock", pose: "stand", mood: "laugh", x: 0.75, flip: true } ], props: [ { id: "bush", x: 0.92 } ],
        cap: { en: "Auggie follows a smell... straight to a peacock!", hi: "ऑगी एक खुशबू के पीछे चला... और पहुँचा सीधा एक मोर के पास!" },
        say: [ { who: 1, en: "Do I look like a puppy's Amma? I'm GORGEOUS!", hi: "मैं किसी पिल्ले की अम्मा लगता हूँ? मैं तो जंगल का हीरो हूँ!" },
               { who: 0, en: "Oops! Wrong smell. Very pretty smell, though.", hi: "उफ़्फ़! ग़लत खुशबू। पर खुशबू थी बड़ी सुंदर।" } ] },
      { bg: "forest", chars: [ { id: "auggie", pose: "point", mood: "determined", x: 0.3 }, { id: "moti", pose: "sit", mood: "happy", x: 0.65, flip: true, s: 0.6 } ], props: [ { id: "tree", x: 0.92 } ],
        cap: { en: "Auggie sniffs Golu's ear. Milk and marigolds! Now find THAT smell.", hi: "ऑगी ने गोलू का कान सूँघा। दूध और गेंदे के फूल! अब यही खुशबू ढूँढो।" },
        say: [ { who: 0, en: "Got it! This way, to the village edge!", hi: "मिल गई! इधर, गाँव के किनारे की तरफ़!" } ],
        fx: { en: "SNIFF!", hi: "सूँ-सूँ!" }, action: true },
      { bg: "village", chars: [ { id: "moti", pose: "stand", mood: "happy", x: 0.22 }, { id: "moti", pose: "cheer", mood: "laugh", x: 0.5, s: 0.6 }, { id: "auggie", pose: "sit", mood: "laugh", x: 0.8, flip: true } ],
        cap: { en: "At the village edge, a worried mother is calling and calling.", hi: "गाँव के किनारे एक परेशान माँ अपने बच्चे को बार-बार पुकार रही है।" },
        say: [ { who: 0, en: "Golu! My little one! Thank you, big yellow friend!", hi: "गोलू! मेरा बच्चा! शुक्रिया, बड़े पीले दोस्त!" },
               { who: 2, en: "Best smell in the whole forest: a family hug!", hi: "पूरे जंगल की सबसे प्यारी खुशबू: माँ की झप्पी!" } ],
        fx: { en: "YAY!", hi: "याय!" }, action: true }
    ]
  }
  ,

  // 131 — Monsoon forest walk: frogs, a peacock and the Wag-Wiggle
  {
    id: 131, age: "4-6", category: "forest",
    title: { en: "The Wag-Wiggle Rain Dance", hi: "बारिश का पूँछ-मटक नाच" },
    blurb: { en: "A peacock dances in the monsoon rain, and Auggie wants to dance too. But his tail is no fan!", hi: "बारिश में मोर नाच रहा है, और ऑगी भी नाचना चाहता है। पर उसकी पूँछ कोई पंखा थोड़ी है!" },
    moral: { en: "Everyone has their own dance, and every dance is a happy one.", hi: "हर किसी का अपना नाच होता है, और हर नाच प्यारा होता है।" },
    cover: { bg: "rain", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "peacock", pose: "stand", mood: "happy", x: 0.75, flip: true } ], props: [ { id: "puddle", x: 0.5, y: 0.92 }, { id: "umbrella", x: 0.08 } ], fx: { en: "WIGGLE!", hi: "मटक!" } },
    panels: [
      { bg: "rain", chars: [ { id: "mausi", pose: "point", mood: "laugh", x: 0.3 }, { id: "auggie", pose: "cheer", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "umbrella", x: 0.08 }, { id: "tree", x: 0.94 } ],
        cap: { en: "Monsoon walk in the Western Ghats forest! Tip-tap, tip-tap on every leaf.", hi: "पश्चिमी घाट के जंगल में बारिश वाली सैर! हर पत्ते पर टप-टप, टप-टप।" },
        say: [ { who: 0, en: "Rain selfie! Hold that pose, wet doggy!", hi: "बारिश वाली सेल्फ़ी! पोज़ पकड़ो, भीगे राजा!" } ] },
      { bg: "jungle", chars: [ { id: "auggie", pose: "stand", mood: "surprised", x: 0.3 }, { id: "peacock", pose: "stand", mood: "happy", x: 0.8, flip: true } ], props: [ { id: "rock", x: 0.8, y: 0.9 } ],
        cap: { en: "From the path, on his leash, Auggie spots a peacock on a far rock.", hi: "पगडंडी पर, पट्टे में बँधे ऑगी को दूर चट्टान पर एक मोर दिखा।" },
        say: [ { who: 0, en: "WOW! He's dancing! I want to dance like that!", hi: "वाह! वो तो नाच रहा है! मुझे भी ऐसे ही नाचना है!", kind: "shout" } ] },
      { bg: "rain", chars: [ { id: "auggie", pose: "run", mood: "laugh", x: 0.38 }, { id: "mausi", pose: "stand", mood: "laugh", x: 0.78, flip: true } ], props: [ { id: "puddle", x: 0.4, y: 0.92 } ],
        cap: { en: "Auggie spins his tail like a fan. Round, round... into a puddle!", hi: "ऑगी ने पूँछ पंखे की तरह घुमाई। गोल, गोल... और सीधा कीचड़ में!" },
        say: [ { who: 0, en: "My tail isn't a fan. It's a mop!", hi: "मेरी पूँछ पंखा नहीं है। ये तो पोंछा है!" } ],
        fx: { en: "SPLASH!", hi: "छपाक!" }, action: true },
      { bg: "rain", chars: [ { id: "frog", pose: "sit", mood: "laugh", x: 0.3 }, { id: "auggie", pose: "sit", mood: "surprised", x: 0.72, flip: true } ], props: [ { id: "puddle", x: 0.3, y: 0.92 } ],
        say: [ { who: 0, en: "Ribbit! Rain dance is easy, big guy. Just HOP!", hi: "टर्र-टर्र! बारिश का नाच तो आसान है भाई। बस फुदको!" },
               { who: 1, en: "Frogs hop. Labradors don't hop. Labradors PLOP!", hi: "मेंढक फुदकते हैं। लैब्राडोर नहीं फुदकते। लैब्राडोर धप्प से गिरते हैं!" } ] },
      { bg: "jungle", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "peacock", pose: "stand", mood: "happy", x: 0.8, flip: true } ], props: [ { id: "rock", x: 0.8, y: 0.9 } ],
        cap: { en: "So Auggie makes up his OWN dance. Wag, wiggle, happy woof!", hi: "तो ऑगी ने अपना ही नाच बना डाला। पूँछ मटक, कमर लचक, खुश भौं!" },
        say: [ { who: 1, en: "Nice moves, yellow friend! What's it called?", hi: "वाह पीले दोस्त, क्या ठुमके हैं! इस नाच का नाम?" },
               { who: 0, en: "The Wag-Wiggle! Doggy dance number one!", hi: "पूँछ-मटक! कुत्तों का नंबर वन नाच!" } ],
        fx: { en: "WIGGLE!", hi: "मटक!" }, action: true },
      { bg: "rain", chars: [ { id: "mausi", pose: "cheer", mood: "laugh", x: 0.22 }, { id: "frog", pose: "sit", mood: "happy", x: 0.5 }, { id: "auggie", pose: "lie", mood: "happy", x: 0.8, flip: true } ], props: [ { id: "umbrella", x: 0.06 } ],
        cap: { en: "Walk over. Mausi dries a muddy, happy Labrador with a big towel.", hi: "सैर ख़त्म। मौसी बड़े तौलिये से एक कीचड़ वाले, खुश लैब्राडोर को पोंछ रही हैं।" },
        say: [ { who: 2, en: "Peacocks fan, frogs hop, I wiggle. Everyone dances!", hi: "मोर पंख फैलाए, मेंढक फुदके, मैं मटका। सब नाचते हैं!" },
               { who: 0, en: "Best dance video ever! Ten million views!", hi: "सबसे बढ़िया डांस वीडियो! एक करोड़ व्यूज़ पक्के!" } ] }
    ]
  }
  ,

  // 132 — A night under the stars with an owl
  {
    id: 132, age: "6-10", category: "forest",
    title: { en: "Who Said HOO?", hi: "हू-हू कौन बोला?" },
    blurb: { en: "Camping in Satpura, Auggie plans to count every star. Then something in the dark says HOO. So who is scared of whom?", hi: "सतपुड़ा में कैंपिंग, और ऑगी हर तारा गिनने वाला है। तभी अँधेरे से कोई बोला, 'हू!' अब कौन किससे डर रहा है?" },
    moral: { en: "Saying 'I'm scared' out loud is brave, and it helps friends find each other.", hi: "'मुझे डर लग रहा है' कह देना भी बहादुरी है, और इसी से दोस्ती भी हो जाती है।" },
    cover: { bg: "forest", chars: [ { id: "auggie", pose: "sit", mood: "surprised", x: 0.3 }, { id: "owl", pose: "stand", mood: "happy", x: 0.75, flip: true } ], props: [ { id: "tent", x: 0.08 }, { id: "campfire", x: 0.52, y: 0.88 }, { id: "star", x: 0.6, y: 0.1 }, { id: "star", x: 0.88, y: 0.14 } ], fx: { en: "HOO!", hi: "हू-हू!" } },
    panels: [
      { bg: "forest", chars: [ { id: "auggie", pose: "sit", mood: "happy", x: 0.3 }, { id: "nanu", pose: "sit", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "tent", x: 0.08 }, { id: "campfire", x: 0.52, y: 0.88 }, { id: "star", x: 0.4, y: 0.1 }, { id: "star", x: 0.85, y: 0.12 } ],
        cap: { en: "Camping night in Satpura forest! Tent up, campfire crackling, Auggie's leash looped on Nanu's wrist.", hi: "सतपुड़ा के जंगल में कैंपिंग की रात! तंबू तैयार, अलाव चटक रहा है, और ऑगी का पट्टा नानू की कलाई पर।" },
        say: [ { who: 0, en: "Tonight I'll count EVERY star. One carrot, two carrots...", hi: "आज रात मैं हर तारा गिनूँगा। एक गाजर, दो गाजर..." },
               { who: 1, en: "Beta, there are more stars than sand grains on every beach!", hi: "बेटा, आसमान में तारे दुनिया के सारे समंदर-किनारों की रेत से भी ज़्यादा हैं!" } ] },
      { bg: "forest", chars: [ { id: "auggie", pose: "cheer", mood: "scared", x: 0.35 }, { id: "nanu", pose: "sit", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "campfire", x: 0.1, y: 0.88 }, { id: "star", x: 0.5, y: 0.1 } ],
        cap: { en: "Suddenly, from the dark trees... HOO! HOO-HOO!", hi: "अचानक अँधेरे पेड़ों से आवाज़ आई... हू! हू-हू!" },
        say: [ { who: 0, en: "Who said HOO?! Nanu, save me!", hi: "हू कौन बोला?! नानू, बचाओ!", kind: "shout" },
               { who: 1, en: "An owl, beta. Owls work the night shift while you snore!", hi: "उल्लू है बेटा। तू खर्राटे लेता है, तब उल्लू की ड्यूटी चलती है!" } ],
        fx: { en: "HOO!", hi: "हू-हू!" }, action: true },
      { bg: "forest", chars: [ { id: "auggie", pose: "sit", mood: "determined", x: 0.3 }, { id: "nanu", pose: "sit", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "campfire", x: 0.52, y: 0.88 } ],
        say: [ { who: 0, en: "I wasn't scared. I was... practising my lap-jump.", hi: "मैं डरा नहीं था। मैं तो... गोदी-छलाँग की प्रैक्टिस कर रहा था।" },
               { who: 1, en: "Of course. A very good lap-jump. Ten out of ten.", hi: "हाँ-हाँ, बिल्कुल। बहुत बढ़िया छलाँग। दस में से दस।" } ] },
      { bg: "forest", chars: [ { id: "auggie", pose: "think", mood: "surprised", x: 0.3 }, { id: "owl", pose: "stand", mood: "scared", x: 0.75, flip: true } ], props: [ { id: "tree", x: 0.88 } ],
        cap: { en: "Two huge round eyes blink from a low branch.", hi: "नीची डाल से दो बड़ी-बड़ी गोल आँखें झपकीं।" },
        say: [ { who: 1, en: "Please don't bark! Your woof nearly blew me off my branch!", hi: "प्लीज़ भौंकना मत! तुम्हारी भौं से मैं डाल से गिरते-गिरते बची!" },
               { who: 0, en: "You're scared of ME? But I was scared of YOU!", hi: "तुम मुझसे डरती हो? पर मैं तो तुमसे डर रहा था!" } ] },
      { bg: "forest", chars: [ { id: "auggie", pose: "sit", mood: "surprised", x: 0.22 }, { id: "nanu", pose: "point", mood: "happy", x: 0.5 }, { id: "owl", pose: "stand", mood: "laugh", x: 0.8, flip: true } ], props: [ { id: "tree", x: 0.92 } ],
        cap: { en: "Nanu has a science fact, of course. Nobody asked. Everybody listens.", hi: "नानू के पास विज्ञान की एक बात है, ज़ाहिर है। किसी ने पूछा नहीं। सब सुन रहे हैं।" },
        say: [ { who: 1, en: "Owls can't roll their eyes, so they turn their whole heads!", hi: "उल्लू आँखें घुमा नहीं सकते, इसलिए पूरी गर्दन ही घुमा लेते हैं!" },
               { who: 2, en: "I'm Gyani. Watch! Almost all the way round. Ta-da!", hi: "मैं ज्ञानी हूँ। देखो! लगभग पूरी गोल घूम गई। टा-डा!" } ] },
      { bg: "forest", chars: [ { id: "auggie", pose: "sit", mood: "scared", x: 0.3 }, { id: "owl", pose: "stand", mood: "laugh", x: 0.75, flip: true } ], props: [ { id: "tree", x: 0.88 }, { id: "star", x: 0.5, y: 0.1 } ],
        say: [ { who: 0, en: "Gyani, truth is... the dark makes my tail go stiff.", hi: "ज्ञानी, सच बताऊँ? अँधेरे में मेरी पूँछ अकड़ जाती है।" },
               { who: 1, en: "And loud woofs make my feathers go fluffy. We're even!", hi: "और तेज़ भौं से मेरे पंख फूल जाते हैं। हिसाब बराबर!" } ] },
      { bg: "forest", chars: [ { id: "auggie", pose: "lie", mood: "happy", x: 0.3 }, { id: "owl", pose: "stand", mood: "happy", x: 0.75, flip: true } ], props: [ { id: "star", x: 0.2, y: 0.08 }, { id: "star", x: 0.35, y: 0.13 }, { id: "star", x: 0.5, y: 0.09 }, { id: "star", x: 0.62, y: 0.15 } ],
        cap: { en: "Gyani shows Auggie seven bright stars shaped like a big ladle.", hi: "ज्ञानी ने ऑगी को सात चमकते तारे दिखाए, बिल्कुल एक बड़ी कलछी जैसे।" },
        say: [ { who: 1, en: "The Saptarishi! Old travellers used them to find the North Star.", hi: "ये है सप्तर्षि! पुराने मुसाफ़िर इन्हीं से ध्रुव तारा ढूँढते थे।" },
               { who: 0, en: "Seven stars! That's seven carrots of stars. Best count ever!", hi: "सात तारे! मतलब सात गाजर जितने तारे। सबसे बढ़िया गिनती!" } ],
        fx: { en: "TWINKLE!", hi: "टिम-टिम!" }, action: true },
      { bg: "forest", chars: [ { id: "nanu", pose: "stand", mood: "happy", x: 0.2 }, { id: "auggie", pose: "lie", mood: "sleepy", x: 0.5 }, { id: "owl", pose: "stand", mood: "happy", x: 0.8, flip: true } ], props: [ { id: "tent", x: 0.35 }, { id: "star", x: 0.65, y: 0.1 } ],
        cap: { en: "Nanu pours water on the campfire until it's cold. Gyani keeps watch from her branch.", hi: "नानू ने अलाव पर पानी डालकर उसे पूरा ठंडा कर दिया। ज्ञानी अपनी डाल से पहरा दे रही है।" },
        say: [ { who: 1, en: "Goodnight, Gyani. Scared together is much less scary.", hi: "गुड नाइट, ज्ञानी। साथ-साथ डरो, तो डर आधा रह जाता है।", kind: "whisper" },
               { who: 2, en: "Hoo-hoo. That's owl for 'sweet dreams'.", hi: "हू-हू। उल्लू की भाषा में इसका मतलब है, 'मीठे सपने'।" } ] }
    ]
  }
  ,

  // 133 — Meeting a shy deer, with shy Kabir's help
  {
    id: 133, age: "6-10", category: "forest",
    title: { en: "Chandni, the Shy Deer", hi: "शर्मीली हिरनी चाँदनी" },
    blurb: { en: "Auggie's hello is as big as a bus, and the spotted deer runs away. Can shy Kabir teach him a quieter way?", hi: "ऑगी का 'हेलो' पूरी बस जितना बड़ा है, और चित्तीदार हिरनी भाग जाती है। क्या शर्मीला कबीर उसे धीमा तरीका सिखा पाएगा?" },
    moral: { en: "Shy hearts open slowly, so be gentle, be quiet, and let them choose.", hi: "शर्मीले दिल धीरे-धीरे खुलते हैं; धीरे बोलो, धीरज रखो, और उन्हें खुद पास आने दो।" },
    cover: { bg: "forest", chars: [ { id: "kabir", pose: "sit", mood: "happy", x: 0.2 }, { id: "auggie", pose: "sit", mood: "happy", x: 0.48 }, { id: "deer", pose: "stand", mood: "happy", x: 0.82, flip: true } ], props: [ { id: "tree", x: 0.95 }, { id: "bush", x: 0.65 } ], fx: { en: "SHH!", hi: "श्श्श!" } },
    panels: [
      { bg: "forest", chars: [ { id: "auggie", pose: "point", mood: "happy", x: 0.22 }, { id: "kabir", pose: "stand", mood: "scared", x: 0.5, flip: true }, { id: "deer", pose: "stand", mood: "surprised", x: 0.85, flip: true, s: 0.7 } ], props: [ { id: "tree", x: 0.05 } ],
        cap: { en: "A forest trail near Bandipur. Mumma holds Auggie's leash. Kabir holds his breath.", hi: "बांदीपुर के पास जंगल की पगडंडी। मम्मा ने ऑगी का पट्टा पकड़ा है। कबीर ने अपनी साँस।" },
        say: [ { who: 0, en: "A deer! With polka dots! I'm saying HELLO!", hi: "हिरन! बिंदियों वाला! मैं अभी हेलो बोलता हूँ!" },
               { who: 1, en: "Auggie, shh... she looks shy. Like me.", hi: "ऑगी, श्श्श... वो शर्मीली लग रही है। मेरी तरह।", kind: "whisper" } ] },
      { bg: "forest", chars: [ { id: "auggie", pose: "blast", mood: "laugh", x: 0.33 }, { id: "kabir", pose: "stand", mood: "surprised", x: 0.75, flip: true } ], props: [ { id: "bush", x: 0.93 } ],
        cap: { en: "Auggie's hello is the size of a bus. The deer vanishes in two leaps.", hi: "ऑगी का हेलो पूरी बस जितना बड़ा था। हिरनी दो छलाँगों में ग़ायब!" },
        say: [ { who: 0, en: "HELLOOO! ...Where'd she go? Was it my carrot breath?", hi: "हेलोऽऽऽ! ...कहाँ गई? मेरे मुँह से गाजर की बू आ रही थी क्या?", kind: "shout" } ],
        fx: { en: "WOOF!", hi: "भौं-भौं!" }, action: true },
      { bg: "forest", chars: [ { id: "auggie", pose: "sit", mood: "sad", x: 0.3 }, { id: "kabir", pose: "sit", mood: "sad", x: 0.72, flip: true } ],
        say: [ { who: 0, en: "Nobody runs away from me. Everybody LOVES me!", hi: "मुझसे कोई नहीं भागता। मुझसे तो सब प्यार करते हैं!" },
               { who: 1, en: "Big hellos feel scary when you're shy. At school, I hide behind my bag.", hi: "शर्मीलों को बड़ा हेलो डरावना लगता है। स्कूल में मैं अपने बैग के पीछे छुप जाता हूँ।" } ] },
      { bg: "forest", chars: [ { id: "auggie", pose: "think", mood: "surprised", x: 0.3 }, { id: "kabir", pose: "point", mood: "determined", x: 0.72, flip: true } ],
        say: [ { who: 0, en: "So how do you say hello to a shy friend?", hi: "तो किसी शर्मीले दोस्त को हेलो कैसे बोलते हैं?" },
               { who: 1, en: "Sit down. Be quiet. Look away a little. Let her choose.", hi: "नीचे बैठो। चुप रहो। थोड़ा इधर-उधर देखो। उसे खुद आने दो।" } ] },
      { bg: "forest", chars: [ { id: "auggie", pose: "lie", mood: "determined", x: 0.3 }, { id: "kabir", pose: "sit", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "bush", x: 0.08 } ],
        cap: { en: "They sit on the trail. Five minutes. Ten minutes. Auggie's nose starts to itch.", hi: "दोनों पगडंडी पर बैठ गए। पाँच मिनट। दस मिनट। ऑगी की नाक में खुजली शुरू।" },
        say: [ { who: 0, en: "Sitting still is basically a nap. I'm an expert... ah... ahh...", hi: "चुप बैठना तो झपकी जैसा है। मैं उस्ताद हूँ... आ... आ...", kind: "whisper" },
               { who: 1, en: "Don't you DARE sneeze!", hi: "ख़बरदार जो छींके!", kind: "whisper" } ] },
      { bg: "river", chars: [ { id: "auggie", pose: "lie", mood: "happy", x: 0.3 }, { id: "deer", pose: "stand", mood: "happy", x: 0.75, flip: true } ], props: [ { id: "tree", x: 0.95 } ],
        cap: { en: "Slowly, the deer steps out to drink from the stream. She looks right at them.", hi: "धीरे-धीरे हिरनी धारा से पानी पीने निकली। और सीधे उनकी तरफ़ देखा।" },
        say: [ { who: 1, en: "You're the loud one. You're much quieter now.", hi: "तुम वही शोर वाले हो ना? अब तो बड़े शांत हो।" },
               { who: 0, en: "Sorry about my bus-sized hello. My paws stay right here.", hi: "सॉरी, मेरा हेलो बस जितना बड़ा था। मेरे पंजे यहीं रहेंगे, पक्का।", kind: "whisper" } ] },
      { bg: "river", chars: [ { id: "kabir", pose: "stand", mood: "determined", x: 0.22 }, { id: "auggie", pose: "sit", mood: "happy", x: 0.5 }, { id: "deer", pose: "stand", mood: "happy", x: 0.8, flip: true } ],
        say: [ { who: 2, en: "I'm Chandni. My spots help me hide in the sunny leaves.", hi: "मैं चाँदनी हूँ। मेरी बिंदियाँ धूप वाले पत्तों में मुझे छुपा लेती हैं।" },
               { who: 0, en: "I'm Kabir. I'm shy too. ...Hi, Chandni.", hi: "मैं कबीर। मैं भी शर्मीला हूँ। ...हाय, चाँदनी।" } ] },
      { bg: "forest", chars: [ { id: "kabir", pose: "cheer", mood: "laugh", x: 0.22 }, { id: "auggie", pose: "cheer", mood: "laugh", x: 0.5, flip: true }, { id: "mumma", pose: "stand", mood: "laugh", x: 0.8, flip: true } ], props: [ { id: "tree", x: 0.05 } ],
        cap: { en: "Chandni flicks her white tail and bounds home. Nobody touched, fed or chased her.", hi: "चाँदनी ने अपनी सफ़ेद पूँछ झटकी और उछलती हुई घर चली गई। न किसी ने छुआ, न खिलाया, न पीछा किया।" },
        say: [ { who: 1, en: "New record! A friend made with zero woofs!", hi: "नया रिकॉर्ड! बिना एक भी भौं के नया दोस्त!" },
               { who: 0, en: "And I said hi first. That's MY new record!", hi: "और हाय मैंने पहले बोला। ये मेरा नया रिकॉर्ड है!" } ],
        fx: { en: "YAY!", hi: "याय!" }, action: true }
    ]
  }
  ,

  // 134 — The forest ranger's rules: leave no trace
  {
    id: 134, age: "6-10", category: "forest",
    title: { en: "Only Pawprints, Please!", hi: "सिर्फ़ पंजों के निशान!" },
    blurb: { en: "Auggie wants to see a tiger. But first, one banana peel wakes up a gloopy monster. Who left that mess?", hi: "ऑगी को बाघ देखना है। पर उससे पहले एक केले के छिलके से जाग उठा गिलगिला राक्षस। ये गंदगी किसकी है?" },
    moral: { en: "Take only memories, leave only footprints, and own up when you slip.", hi: "जंगल से बस यादें ले जाओ, बस पैरों के निशान छोड़ो, और ग़लती हो जाए तो मान लो।" },
    cover: { bg: "jungle", chars: [ { id: "auggie", pose: "point", mood: "determined", x: 0.3 }, { id: "kichdu", pose: "stand", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "dustbin", x: 0.08 }, { id: "tree", x: 0.94 } ], fx: { en: "GLOOP!", hi: "गिलप!" } },
    panels: [
      { bg: "forest", chars: [ { id: "auggie", pose: "cheer", mood: "happy", x: 0.3 }, { id: "papa", pose: "stand", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "tree", x: 0.06 }, { id: "map", x: 0.52, y: 0.8 } ],
        cap: { en: "Jungle camp by the tiger forest. Ranger Meena Didi's rules: stay on the trail, stay quiet, leave nothing.", hi: "बाघ वाले जंगल के पास जंगल-कैंप। रेंजर मीना दीदी के नियम: पगडंडी पर रहो, शांत रहो, कुछ मत छोड़ो।" },
        say: [ { who: 0, en: "I'm here for a TIGER! A big stripy one, up close!", hi: "मैं तो बाघ देखने आया हूँ! बड़ा, धारीदार, एकदम पास से!" },
               { who: 1, en: "Far away, with Ranger Didi, and on your leash. Tigers need space!", hi: "दूर से, रेंजर दीदी के साथ, और पट्टे में। बाघ को अपनी जगह चाहिए!" } ] },
      { bg: "forest", chars: [ { id: "auggie", pose: "stand", mood: "laugh", x: 0.3 }, { id: "mausi", pose: "stand", mood: "surprised", x: 0.72, flip: true } ], props: [ { id: "banana", x: 0.48, y: 0.85 }, { id: "bush", x: 0.08 } ],
        cap: { en: "Snack break. Auggie finishes his banana and flicks the peel into a bush.", hi: "नाश्ते का टाइम। ऑगी ने केला खाया और छिलका झाड़ी में उछाल दिया।" },
        say: [ { who: 0, en: "It's a plant thing. It'll just turn back into forest!", hi: "ये तो पेड़-पौधे वाली चीज़ है। अपने आप जंगल बन जाएगा!" },
               { who: 1, en: "Hmm. Are you sure about that, Auggie?", hi: "हम्म। पक्का, ऑगी? मुझे तो शक है।" } ] },
      { bg: "jungle", chars: [ { id: "auggie", pose: "stand", mood: "scared", x: 0.3 }, { id: "kichdu", pose: "blast", mood: "laugh", x: 0.72, flip: true, s: 1.2 } ], props: [ { id: "bush", x: 0.92 } ],
        cap: { en: "The bush wobbles. Out oozes Kichdu, made of old wrappers someone left, plus one fresh peel!", hi: "झाड़ी हिली। बाहर निकला किचडू, किसी के छोड़े पुराने रैपरों से बना, और ऊपर से एक ताज़ा छिलका!" },
        say: [ { who: 1, en: "Every bit of litter makes me BIGGER! Thanks for the peel!", hi: "हर कचरे से मैं और बड़ा होता हूँ! छिलके के लिए थैंक यू!" },
               { who: 0, en: "MY peel made you bigger?!", hi: "मेरे छिलके से तुम बड़े हो गए?!", kind: "shout" } ],
        fx: { en: "GLOOP!", hi: "गिलप!" }, action: true },
      { bg: "jungle", chars: [ { id: "auggie", pose: "sit", mood: "sad", x: 0.3 }, { id: "monkey", pose: "sit", mood: "happy", x: 0.75, flip: true } ], props: [ { id: "tree", x: 0.92 } ],
        cap: { en: "Ranger Meena explains: peels rot slowly here, and monkeys learn to beg from people.", hi: "रेंजर मीना दीदी ने समझाया: यहाँ छिलके धीरे सड़ते हैं, और बंदर इंसानों से खाना माँगना सीख जाते हैं।" },
        say: [ { who: 1, en: "Banana smell? Humans have bananas? Give me MORE!", hi: "केले की खुशबू? इंसानों के पास केले हैं? मुझे और चाहिए!" },
               { who: 0, en: "Oh no. I thought one little peel didn't count.", hi: "अरे नहीं। मुझे लगा एक छोटे-से छिलके से क्या फ़र्क पड़ेगा।" } ] },
      { bg: "jungle", chars: [ { id: "auggie", pose: "blast", mood: "determined", x: 0.3 }, { id: "kichdu", pose: "stand", mood: "laugh", x: 0.72, flip: true, s: 1.2 } ],
        cap: { en: "Auggie tries to scare Kichdu away with his biggest woof.", hi: "ऑगी ने अपनी सबसे बड़ी भौं से किचडू को भगाने की कोशिश की।" },
        say: [ { who: 0, en: "Go away, gloop! WOOF!", hi: "भाग जा, गिलगिले! भौं!", kind: "shout" },
               { who: 1, en: "Barking doesn't clean, doggy! And it scares the birds.", hi: "भौंकने से सफ़ाई नहीं होती, कुत्ते जी! ऊपर से चिड़ियाँ डर जाती हैं।" } ],
        fx: { en: "WOOF!", hi: "भौं-भौं!" }, action: true },
      { bg: "forest", chars: [ { id: "auggie", pose: "point", mood: "determined", x: 0.22 }, { id: "papa", pose: "stand", mood: "happy", x: 0.5 }, { id: "kichdu", pose: "stand", mood: "surprised", x: 0.8, flip: true, s: 0.7 } ], props: [ { id: "dustbin", x: 0.64, y: 0.85 } ],
        cap: { en: "Auggie picks up his own peel first. Then his Super Sniffer finds every hidden wrapper.", hi: "ऑगी ने सबसे पहले अपना छिलका उठाया। फिर उसकी सुपर सूँघू नाक ने छुपे हुए सारे रैपर ढूँढ निकाले।" },
        say: [ { who: 0, en: "My mistake, my clean-up. And I'll pick up everyone else's too!", hi: "ग़लती मेरी, सफ़ाई भी मेरी। और बाकी सबका कचरा भी मैं उठाऊँगा!" },
               { who: 2, en: "Hey... I'm shrinking. I feel light. Is this... happy?", hi: "अरे... मैं छोटा हो रहा हूँ। हल्का-हल्का लग रहा है। यही खुशी है क्या?" } ],
        fx: { en: "SNIFF!", hi: "सूँ-सूँ!" }, action: true },
      { bg: "river", chars: [ { id: "auggie", pose: "sit", mood: "surprised", x: 0.3 }, { id: "papa", pose: "stand", mood: "happy", x: 0.62, flip: true }, { id: "tiger", pose: "stand", mood: "happy", x: 0.88, flip: true, s: 0.6 } ],
        cap: { en: "Evening, from the tall watchtower. Ranger Meena points far across the river...", hi: "शाम को ऊँचे वॉचटावर से, रेंजर मीना दीदी ने दूर नदी के उस पार इशारा किया..." },
        say: [ { who: 0, en: "A TIGER! Drinking water, like a giant stripy kitty!", hi: "बाघ! पानी पी रहा है, जैसे कोई बड़ी धारीदार बिल्ली!", kind: "whisper" },
               { who: 1, en: "Clean, quiet forest, happy tiger. Ranger Didi's rules really work!", hi: "साफ़-शांत जंगल, खुश बाघ। रेंजर दीदी के नियम सच में काम करते हैं!", kind: "whisper" } ] },
      { bg: "forest", chars: [ { id: "kichdu", pose: "cheer", mood: "happy", x: 0.22, s: 0.6 }, { id: "auggie", pose: "cheer", mood: "laugh", x: 0.5, flip: true }, { id: "mausi", pose: "point", mood: "laugh", x: 0.8, flip: true } ], props: [ { id: "dustbin", x: 0.07 }, { id: "camera", x: 0.9, y: 0.3 } ],
        cap: { en: "Back at camp, Ranger Meena gives tiny Kichdu a new job and a shiny badge.", hi: "कैंप लौटकर रेंजर मीना दीदी ने नन्हे किचडू को नया काम और एक चमकता बिल्ला दिया।" },
        say: [ { who: 0, en: "Forest Clean-Up Captain! Nobody ever gave me a job before!", hi: "जंगल-सफ़ाई कप्तान! आज तक किसी ने मुझे काम ही नहीं दिया था!" },
               { who: 1, en: "Take only photos, leave only pawprints. Right, Captain?", hi: "सिर्फ़ फ़ोटो ले जाओ, सिर्फ़ पंजों के निशान छोड़ो। है ना, कप्तान?" } ] }
    ]
  }
);
