window.AUGGIE_COMICS = window.AUGGIE_COMICS || [];
window.AUGGIE_COMICS.push(

  // ===================== AUGGIE AND SCHOOL =====================

  // 111 — Class pet for a day
  {
    id: 111, age: "4-6", category: "school",
    title: { en: "Class Pet for a Day", hi: "एक दिन का क्लास पेट" },
    blurb: { en: "Auggie is the class pet today, but can a big waggy tail survive Miss Ji's tidy classroom?", hi: "आज ऑगी क्लास का पेट है, पर क्या इतनी बड़ी हिलती पूँछ मिस जी की साफ़-सुथरी क्लास में टिक पाएगी?" },
    moral: { en: "Sitting still and listening helps everyone learn, even the class pet.", hi: "चुपचाप बैठकर सुनने से सब सीखते हैं, क्लास का पेट भी!" },
    cover: { bg: "classroom", chars: [ { id: "auggie", pose: "sit", mood: "happy", x: 0.35 }, { id: "missji", pose: "stand", mood: "laugh", x: 0.75, flip: true } ], props: [ { id: "book", x: 0.12 } ], fx: { en: "STAR!", hi: "तारा!" } },
    panels: [
      { bg: "classroom", chars: [ { id: "auggie", pose: "stand", mood: "happy", x: 0.3 }, { id: "missji", pose: "point", mood: "happy", x: 0.72, flip: true } ],
        cap: { en: "Today Auggie is the class pet at Chamakpur Public School!", hi: "आज ऑगी चमकपुर पब्लिक स्कूल का क्लास पेट है!" },
        say: [ { who: 1, en: "Rule one: sit still. Rule two: no mess!", hi: "पहला नियम: चुपचाप बैठो। दूसरा: कोई गड़बड़ नहीं!" } ] },
      { bg: "classroom", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.35 }, { id: "rohan", pose: "stand", mood: "surprised", x: 0.75, flip: true } ],
        cap: { en: "Auggie wags hello. His tail wipes the whole blackboard!", hi: "ऑगी ने पूँछ हिलाकर हेलो कहा। पूरा ब्लैकबोर्ड साफ़!" },
        say: [ { who: 1, en: "Miss Ji! Auggie's tail ate the sums!", hi: "मिस जी! ऑगी की पूँछ सारे सवाल खा गई!", kind: "shout" } ],
        fx: { en: "SWISH!", hi: "सर्र!" }, action: true },
      { bg: "classroom", chars: [ { id: "auggie", pose: "lie", mood: "sad", x: 0.3 }, { id: "missji", pose: "stand", mood: "surprised", x: 0.72, flip: true } ],
        say: [ { who: 1, en: "Arre! My two-plus-two is gone!", hi: "अरे! मेरा दो और दो कहाँ गया!" },
               { who: 0, en: "Sorry, Miss Ji. Big tail, big wag.", hi: "सॉरी मिस जी। पूँछ बड़ी, तो हिलती भी बड़ी।" } ] },
      { bg: "classroom", chars: [ { id: "kabir", pose: "sit", mood: "happy", x: 0.28 }, { id: "auggie", pose: "think", mood: "surprised", x: 0.68, flip: true } ],
        say: [ { who: 0, en: "Sit like me. Paws on desk. Very still.", hi: "मेरी तरह बैठो। पंजे डेस्क पर। बिल्कुल चुप।", kind: "whisper" },
               { who: 1, en: "Still is easy. Still is like a nap!", hi: "चुप बैठना आसान है। ये तो झपकी जैसा है!", kind: "think" } ] },
      { bg: "classroom", chars: [ { id: "auggie", pose: "sit", mood: "determined", x: 0.2 }, { id: "zoya", pose: "sit", mood: "happy", x: 0.5 }, { id: "missji", pose: "stand", mood: "laugh", x: 0.8, flip: true } ],
        cap: { en: "The whole class sits still. Even Auggie's tail!", hi: "पूरी क्लास चुप बैठी है। ऑगी की पूँछ भी!" },
        say: [ { who: 2, en: "Best listeners in Chamakpur! Gold star for Auggie!", hi: "वाह! पूरे चमकपुर में इतनी शांत क्लास कहीं नहीं! ऑगी को गोल्ड स्टार!" } ],
        fx: { en: "STAR!", hi: "तारा!" }, action: true },
      { bg: "playground", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.33 }, { id: "missji", pose: "sit", mood: "happy", x: 0.72, flip: true } ],
        cap: { en: "After the bell, Miss Ji's hand finds her pocket.", hi: "घंटी के बाद मिस जी का हाथ जेब में जाता है।" },
        say: [ { who: 1, en: "Psst. Class pets get carrots. Don't tell anyone.", hi: "श्श्श। क्लास पेट को गाजर मिलती है। किसी को बताना मत।", kind: "whisper" },
               { who: 0, en: "Best school ever! Crunch!", hi: "सबसे बढ़िया स्कूल! कुर्र-कुर्र!" } ],
        fx: { en: "CRUNCH!", hi: "कुर्र-कुर्र!" }, action: true }
    ]
  },

  // 112 — Sneaking in with Kabir's tiffin
  {
    id: 112, age: "4-6", category: "school",
    title: { en: "The Paratha Trail", hi: "पराठे की खुशबू के पीछे" },
    blurb: { en: "Kabir's tiffin smells like paratha, so Auggie sneaks all the way to school. What will Miss Ji say?", hi: "कबीर के टिफ़िन से पराठे की खुशबू आती है, और ऑगी चुपके-चुपके स्कूल तक पहुँच जाता है। अब मिस जी क्या कहेंगी?" },
    moral: { en: "Sneaking gets you stuck. Asking nicely gets you a tiffin break.", hi: "चुपके से जाओगे तो फँस जाओगे, प्यार से पूछोगे तो टिफ़िन ब्रेक मिलेगा।" },
    cover: { bg: "school", chars: [ { id: "auggie", pose: "point", mood: "surprised", x: 0.35 }, { id: "kabir", pose: "stand", mood: "laugh", x: 0.75, flip: true } ], props: [ { id: "tree", x: 0.1 } ], fx: { en: "SNIFF!", hi: "सूँ-सूँ!" } },
    panels: [
      { bg: "home", chars: [ { id: "kabir", pose: "stand", mood: "happy", x: 0.28 }, { id: "auggie", pose: "point", mood: "happy", x: 0.68, flip: true } ],
        cap: { en: "Kabir packs his tiffin. Paratha! Auggie's nose wakes up.", hi: "कबीर टिफ़िन भर रहा है। पराठा! ऑगी की नाक जाग गई।" },
        say: [ { who: 1, en: "School smells like paratha? I'm coming too!", hi: "स्कूल में पराठे की खुशबू? तो मैं भी चलूँगा!" } ],
        fx: { en: "SNIFF!", hi: "सूँ-सूँ!" }, action: true },
      { bg: "home", chars: [ { id: "auggie", pose: "run", mood: "determined", x: 0.35 }, { id: "kabir", pose: "stand", mood: "laugh", x: 0.75, flip: true } ],
        cap: { en: "Auggie tries to hide inside the school bag.", hi: "ऑगी स्कूल बैग के अंदर छुपने की कोशिश करता है।" },
        say: [ { who: 1, en: "Auggie, only your nose fits in there!", hi: "हाय राम! ऑगी, इसमें तो बस तुम्हारी नाक घुसती है!" } ] },
      { bg: "school", chars: [ { id: "auggie", pose: "stand", mood: "scared", x: 0.4 } ], props: [ { id: "tree", x: 0.12 } ],
        cap: { en: "Auggie tiptoes behind Kabir, all the way to school. Then... the bell!", hi: "ऑगी चुपके-चुपके कबीर के पीछे-पीछे स्कूल तक आ गया। तभी... घंटी!" },
        say: [ { who: 0, en: "Who is ringing that giant bell?!", hi: "ये इतनी बड़ी घंटी कौन बजा रहा है?!", kind: "shout" } ],
        fx: { en: "TAN-TAN!", hi: "टन-टन!" }, action: true },
      { bg: "classroom", chars: [ { id: "kabir", pose: "stand", mood: "determined", x: 0.2 }, { id: "auggie", pose: "sit", mood: "sad", x: 0.5 }, { id: "missji", pose: "stand", mood: "surprised", x: 0.82, flip: true } ],
        cap: { en: "Kabir is shy. But his friend needs him.", hi: "कबीर शर्मीला है। पर दोस्त को उसकी ज़रूरत है।" },
        say: [ { who: 0, en: "Miss Ji... may Auggie stay? Please?", hi: "मिस जी... ऑगी रुक सकता है? प्लीज़?" },
               { who: 2, en: "A dog in my tidy classroom? Hmm...", hi: "मेरी साफ़-सुथरी क्लास में कुत्ता? हम्म..." } ] },
      { bg: "playground", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.33 }, { id: "missji", pose: "point", mood: "happy", x: 0.75, flip: true } ],
        say: [ { who: 1, en: "Dogs wait in the playground. Tiffin break is outside!", hi: "कुत्ते मैदान में रुकेंगे। टिफ़िन ब्रेक बाहर ही होता है!" },
               { who: 0, en: "Tiffin break! My favourite subject!", hi: "टिफ़िन ब्रेक! मेरा सबसे प्यारा सब्जेक्ट!" } ] },
      { bg: "playground", chars: [ { id: "rohan", pose: "sit", mood: "happy", x: 0.2 }, { id: "auggie", pose: "sit", mood: "happy", x: 0.5 }, { id: "anaya", pose: "sit", mood: "happy", x: 0.8, flip: true } ], props: [ { id: "apple", x: 0.65, y: 0.7 } ],
        say: [ { who: 0, en: "Auggie, want my laddoo? It's super sweet!", hi: "ऑगी, मेरा लड्डू खाएगा? एकदम मीठा है!" },
               { who: 2, en: "No sweets for dogs! Apple slices, coming up!", hi: "ना-ना! कुत्तों को मिठाई नहीं। ये लो, सेब के टुकड़े!" } ],
        fx: { en: "CRUNCH!", hi: "कुर्र-कुर्र!" }, action: true }
    ]
  },

  // 113 — Pet Day and the Best Pet trophy
  {
    id: 113, age: "4-6", category: "school",
    title: { en: "Pet Day Trophy", hi: "पेट डे की ट्रॉफ़ी" },
    blurb: { en: "Chiku is first, Pinku is fabulous, and Auggie wants the Best Pet trophy. Who wins?", hi: "चीकू सबसे आगे, पिंकू सबसे सुंदर, और ऑगी को चाहिए बेस्ट पेट ट्रॉफ़ी। जीतेगा कौन?" },
    moral: { en: "A kind heart wins bigger than the fanciest trick.", hi: "सबसे बड़ा करतब है दिल का अच्छा होना।" },
    cover: { bg: "playground", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "pinku", pose: "sit", mood: "happy", x: 0.58 }, { id: "missji", pose: "stand", mood: "happy", x: 0.85, flip: true } ], props: [ { id: "trophy", x: 0.1 } ], fx: { en: "YAY!", hi: "याय!" } },
    panels: [
      { bg: "playground", chars: [ { id: "chiku", pose: "run", mood: "happy", x: 0.2 }, { id: "auggie", pose: "stand", mood: "happy", x: 0.5 }, { id: "pinku", pose: "sit", mood: "happy", x: 0.8, flip: true } ],
        cap: { en: "Pet Day at Chamakpur Public School! Every kid brings a friend.", hi: "चमकपुर पब्लिक स्कूल में पेट डे! हर बच्चा अपना दोस्त लाया है।" },
        say: [ { who: 0, en: "I'm first! I'm always first!", hi: "मैं पहले आया! मैं हमेशा पहले आता हूँ!" },
               { who: 2, en: "And I'm the most beautiful. Obviously.", hi: "और सबसे सुंदर मैं हूँ। ज़ाहिर है।" } ] },
      { bg: "playground", chars: [ { id: "auggie", pose: "sit", mood: "determined", x: 0.3 }, { id: "missji", pose: "point", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "trophy", x: 0.52 } ],
        say: [ { who: 1, en: "The Best Pet wins this shiny trophy!", hi: "बेस्ट पेट को मिलेगी ये चमचमाती ट्रॉफ़ी!" },
               { who: 0, en: "Shiny! I'll do my biggest trick!", hi: "चमचम! मैं अपना सबसे बड़ा करतब दिखाऊँगा!" } ] },
      { bg: "playground", chars: [ { id: "auggie", pose: "lie", mood: "laugh", x: 0.4 }, { id: "rohan", pose: "stand", mood: "surprised", x: 0.78, flip: true } ], props: [ { id: "flower", x: 0.12 }, { id: "flower", x: 0.6 } ],
        cap: { en: "Auggie rolls over... and over... into the flower pots!", hi: "ऑगी लुढ़का... और लुढ़का... सीधा गमलों में!" },
        say: [ { who: 1, en: "Auggie! That's the garden, not the stage!", hi: "ऑगी! वो बगीचा है, स्टेज नहीं!", kind: "shout" } ],
        fx: { en: "ROLL!", hi: "लुढ़क!" }, action: true },
      { bg: "playground", chars: [ { id: "auggie", pose: "stand", mood: "surprised", x: 0.3 }, { id: "pinku", pose: "lie", mood: "sad", x: 0.7, flip: true } ],
        say: [ { who: 1, en: "Too hot. I'm fainting. Goodbye, world.", hi: "बहुत गर्मी है। मैं बेहोश हो रहा हूँ। अलविदा दुनिया।" },
               { who: 0, en: "Pinku! Hold on! I'll get water!", hi: "पिंकू! रुक जा! मैं पानी लाता हूँ!", kind: "shout" } ] },
      { bg: "playground", chars: [ { id: "auggie", pose: "wave", mood: "happy", x: 0.2 }, { id: "pinku", pose: "sit", mood: "happy", x: 0.5, flip: true }, { id: "missji", pose: "stand", mood: "laugh", x: 0.82, flip: true } ], props: [ { id: "bowl", x: 0.35, y: 0.75 } ],
        cap: { en: "Auggie brings the water bowl. Slurp! Pinku is fine.", hi: "ऑगी पानी का कटोरा लाया। गप-गप! पिंकू ठीक है।" },
        say: [ { who: 2, en: "Now THAT is a trick. Kindness!", hi: "ये हुआ असली करतब। दिल का अच्छा होना!" } ],
        fx: { en: "SLURP!", hi: "गप-गप!" }, action: true },
      { bg: "playground", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "pinku", pose: "sit", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "trophy", x: 0.5 } ],
        cap: { en: "Best Pet: Auggie, for the biggest heart!", hi: "बेस्ट पेट: ऑगी, सबसे बड़े दिल के लिए!" },
        say: [ { who: 1, en: "I'm never speaking to you again. Okay, congratulations.", hi: "मैं तुमसे कभी बात नहीं करूँगा। अच्छा, बधाई हो।" },
               { who: 0, en: "Shared trophy? It's big enough for two!", hi: "ट्रॉफ़ी बाँट लें? दो के लिए काफ़ी बड़ी है!" } ],
        fx: { en: "YAY!", hi: "याय!" }, action: true }
    ]
  },

  // 114 — Sports Day: Zoya's jelly legs
  {
    id: 114, age: "6-10", category: "school",
    title: { en: "Run to Auggie!", hi: "ऑगी की तरफ़ भागो!" },
    blurb: { en: "Zoya is the fastest kid in class, so why are her legs shaking on Sports Day?", hi: "ज़ोया क्लास में सबसे तेज़ दौड़ती है, फिर स्पोर्ट्स डे पर उसकी टाँगें क्यों काँप रही हैं?" },
    moral: { en: "Being brave isn't never being scared. It's running anyway.", hi: "बहादुरी का मतलब डर न लगना नहीं, डर के बावजूद दौड़ना है।" },
    cover: { bg: "playground", chars: [ { id: "zoya", pose: "run", mood: "determined", x: 0.3 }, { id: "auggie", pose: "cheer", mood: "laugh", x: 0.7, flip: true } ], props: [ { id: "trophy", x: 0.92 } ], fx: { en: "ZOOM!", hi: "ज़ूम!" } },
    panels: [
      { bg: "playground", chars: [ { id: "auggie", pose: "stand", mood: "happy", x: 0.3 }, { id: "rohan", pose: "stand", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "balloon", x: 0.92, y: 0.2 } ],
        cap: { en: "Sports Day! Flags, whistles, and one very excited Labrador on a leash.", hi: "स्पोर्ट्स डे! झंडियाँ, सीटियाँ, और पट्टे में एक बहुत ही उतावला लैब्राडोर।" },
        say: [ { who: 0, en: "I'm the mascot! What does a mascot eat?", hi: "मैं मैस्कॉट हूँ! मैस्कॉट क्या खाता है?" },
               { who: 1, en: "Mascots don't eat, Auggie. They cheer!", hi: "मैस्कॉट खाता नहीं है ऑगी। चीयर करता है!" } ] },
      { bg: "playground", chars: [ { id: "auggie", pose: "sit", mood: "surprised", x: 0.3 }, { id: "zoya", pose: "stand", mood: "sad", x: 0.72, flip: true } ],
        cap: { en: "Zoya is the fastest runner in class. But today her legs feel like jelly.", hi: "ज़ोया क्लास में सबसे तेज़ दौड़ती है। पर आज उसकी टाँगें जेली बन गई हैं।" },
        say: [ { who: 1, en: "Last year I fell in front of everyone. Everyone laughed.", hi: "पिछले साल मैं सबके सामने गिर गई थी। सब हँसे थे।", kind: "whisper" } ] },
      { bg: "playground", chars: [ { id: "missji", pose: "blast", mood: "determined", x: 0.25 }, { id: "auggie", pose: "run", mood: "laugh", x: 0.68, flip: true } ],
        cap: { en: "Miss Ji blows the practice whistle. Auggie's leash slips right out of Rohan's hand...", hi: "मिस जी ने प्रैक्टिस की सीटी बजाई। और ऑगी का पट्टा रोहन के हाथ से फिसल गया..." },
        say: [ { who: 1, en: "WHISTLE! Whistle means GO, right? GO GO GO!", hi: "सीटी! सीटी मतलब भागो, है ना? भागो भागो भागो!", kind: "shout" } ],
        fx: { en: "PEEEP!", hi: "पीईई!" }, action: true },
      { bg: "playground", chars: [ { id: "rohan", pose: "stand", mood: "laugh", x: 0.2 }, { id: "auggie", pose: "cheer", mood: "happy", x: 0.5 }, { id: "missji", pose: "point", mood: "surprised", x: 0.82, flip: true } ],
        cap: { en: "Auggie crosses the finish line first. Then he eats the finish ribbon.", hi: "ऑगी सबसे पहले फ़िनिश लाइन पार करता है। फिर फ़िनिश वाला रिबन खा जाता है।" },
        say: [ { who: 2, en: "Auggie! Dogs can't win the kids' race! And spit that out!", hi: "ऑगी! बच्चों की रेस कुत्ते नहीं जीतते! और वो थूको!", kind: "shout" },
               { who: 0, en: "New record: fastest dog, slowest listener!", hi: "नया रिकॉर्ड: सबसे तेज़ कुत्ता, सबसे धीमा सुनने वाला!" } ] },
      { bg: "playground", chars: [ { id: "auggie", pose: "sit", mood: "sad", x: 0.3 }, { id: "zoya", pose: "sit", mood: "sad", x: 0.72, flip: true } ],
        say: [ { who: 0, en: "I made a mess. Zoya, you looked scared. What do you need?", hi: "मैंने गड़बड़ कर दी। ज़ोया, तुम डरी हुई लग रही थीं। बताओ, क्या चाहिए?" },
               { who: 1, en: "I'm not scared. ...Okay, I'm scared. I don't want to fall.", hi: "मैं डरी नहीं हूँ। ...अच्छा, डरी हूँ। मैं गिरना नहीं चाहती।" } ] },
      { bg: "playground", chars: [ { id: "auggie", pose: "point", mood: "determined", x: 0.3 }, { id: "zoya", pose: "stand", mood: "determined", x: 0.72, flip: true } ],
        say: [ { who: 0, en: "Then don't look at the crowd. Look at me at the finish. Run to Auggie!", hi: "तो भीड़ को मत देखो। फ़िनिश लाइन पर मुझे देखो। ऑगी की तरफ़ भागो!" },
               { who: 1, en: "Run to Auggie. Okay. I can do that.", hi: "ऑगी की तरफ़ भागो। ठीक है। ये मैं कर सकती हूँ।" } ] },
      { bg: "playground", chars: [ { id: "zoya", pose: "run", mood: "determined", x: 0.3 }, { id: "auggie", pose: "sit", mood: "laugh", x: 0.75, flip: true } ],
        cap: { en: "The real race. Zoya's eyes lock on one big yellow dog. She flies!", hi: "असली रेस। ज़ोया की नज़र बस एक बड़े पीले कुत्ते पर। और वो उड़ चली!" },
        say: [ { who: 1, en: "ZOYA! ZOYA! CARROT-SPEED, ZOYA!", hi: "ज़ोया! ज़ोया! गाजर-स्पीड, ज़ोया!", kind: "shout" } ],
        fx: { en: "ZOOM!", hi: "ज़ूम!" }, action: true },
      { bg: "playground", chars: [ { id: "zoya", pose: "cheer", mood: "laugh", x: 0.25 }, { id: "auggie", pose: "cheer", mood: "happy", x: 0.55, flip: true }, { id: "missji", pose: "stand", mood: "laugh", x: 0.85, flip: true } ], props: [ { id: "trophy", x: 0.4, y: 0.3 } ],
        cap: { en: "Gold medal! And not one fall.", hi: "गोल्ड मेडल! और एक बार भी नहीं गिरी।" },
        say: [ { who: 0, en: "I was scared the whole time. And I still won!", hi: "मैं पूरे टाइम डरी हुई थी। फिर भी जीत गई!" },
               { who: 2, en: "Gold medal for Zoya. Gold carrot for the mascot.", hi: "ज़ोया को गोल्ड मेडल। मैस्कॉट को गोल्ड गाजर।" } ],
        fx: { en: "YAY!", hi: "याय!" }, action: true }
    ]
  },

  // 115 — The library's missing book
  {
    id: 115, age: "6-10", category: "school",
    title: { en: "The Missing Library Book", hi: "लाइब्रेरी की गुम किताब" },
    blurb: { en: "The class's favourite book vanishes, Rohan blames Kabir, and Detective Auggie's nose smells... samosa?", hi: "क्लास की सबसे प्यारी किताब गायब, रोहन का शक कबीर पर, और जासूस ऑगी की नाक को आ रही है... समोसे की खुशबू?" },
    moral: { en: "Telling the truth early is braver than hiding, and lighter too.", hi: "सच जल्दी बोल देना छुपाने से ज़्यादा बहादुरी है, और दिल भी हल्का रहता है।" },
    cover: { bg: "school", chars: [ { id: "auggie", pose: "point", mood: "determined", x: 0.35 }, { id: "anaya", pose: "stand", mood: "surprised", x: 0.75, flip: true } ], props: [ { id: "book", x: 0.12 } ], fx: { en: "SNIFF!", hi: "सूँ-सूँ!" } },
    panels: [
      { bg: "school", chars: [ { id: "rohan", pose: "stand", mood: "surprised", x: 0.2 }, { id: "auggie", pose: "sit", mood: "happy", x: 0.5 }, { id: "missji", pose: "point", mood: "determined", x: 0.82, flip: true } ],
        cap: { en: "Library period. The class favourite, 'Bholu's Big Trumpet', is missing!", hi: "लाइब्रेरी पीरियड। क्लास की सबसे प्यारी किताब 'भोलू की बड़ी तुरही' गायब!" },
        say: [ { who: 2, en: "Nobody goes for tiffin break until that book is found!", hi: "जब तक किताब नहीं मिलती, कोई टिफ़िन ब्रेक पर नहीं जाएगा!" },
               { who: 0, en: "No tiffin?! This is the worst mystery ever!", hi: "टिफ़िन नहीं?! ये तो सबसे बुरा रहस्य है!" } ] },
      { bg: "school", chars: [ { id: "rohan", pose: "point", mood: "angry", x: 0.28 }, { id: "kabir", pose: "stand", mood: "scared", x: 0.7, flip: true } ],
        say: [ { who: 0, en: "Kabir had it last! I saw him!", hi: "आख़िरी बार कबीर के पास थी! मैंने देखा था!" },
               { who: 1, en: "I... I put it back. I think. Maybe?", hi: "मैंने... मैंने रख दी थी। शायद। लगता तो है?" } ] },
      { bg: "school", chars: [ { id: "auggie", pose: "point", mood: "determined", x: 0.3 }, { id: "kabir", pose: "stand", mood: "happy", x: 0.72, flip: true } ],
        say: [ { who: 0, en: "Detective Auggie is on the case! Super Sniffer, activate!", hi: "जासूस ऑगी केस पर है! सुपर सूँघू नाक, चालू!" },
               { who: 1, en: "Sniff my bag first, please! I'm innocent!", hi: "पहले मेरा बैग सूँघो, प्लीज़! मैं बेकसूर हूँ!" } ],
        fx: { en: "SNIFF!", hi: "सूँ-सूँ!" }, action: true },
      { bg: "school", chars: [ { id: "auggie", pose: "point", mood: "surprised", x: 0.3 }, { id: "missji", pose: "stand", mood: "surprised", x: 0.72, flip: true } ],
        cap: { en: "The nose follows a smell... straight into Miss Ji's desk drawer.", hi: "नाक खुशबू के पीछे चली... सीधे मिस जी की दराज़ में।" },
        say: [ { who: 0, en: "Found it! Wait. This is a samosa.", hi: "मिल गई! रुको। ये तो समोसा है।" },
               { who: 1, en: "That is MY samosa, detective. Keep sniffing.", hi: "वो मेरा समोसा है, जासूस जी। आगे सूँघो।" } ] },
      { bg: "school", chars: [ { id: "auggie", pose: "think", mood: "surprised", x: 0.3 }, { id: "anaya", pose: "stand", mood: "sad", x: 0.72, flip: true } ],
        cap: { en: "Then Auggie sniffs something new. Blue paint. On Anaya's fingers.", hi: "तभी ऑगी की नाक को कुछ नया मिला। नीला रंग। अनाया की उँगलियों पर।" },
        say: [ { who: 0, en: "Anaya, you smell like blue paint... and elephants.", hi: "अनाया, तुमसे नीले रंग की खुशबू आ रही है... और हाथियों की।", kind: "whisper" },
               { who: 1, en: "I took it home to paint Bholu. I was scared to say.", hi: "मैं भोलू का चित्र बनाने के लिए घर ले गई थी। बताने से डर लगा।", kind: "whisper" } ] },
      { bg: "school", chars: [ { id: "auggie", pose: "sit", mood: "happy", x: 0.3 }, { id: "anaya", pose: "stand", mood: "determined", x: 0.72, flip: true } ],
        say: [ { who: 0, en: "I could tell everyone. But it's your story, not my nose's.", hi: "मैं सबको बता सकता हूँ। पर ये तुम्हारी कहानी है, मेरी नाक की नहीं।" },
               { who: 1, en: "My tummy's doing flips. But hiding feels worse. Okay.", hi: "मेरा पेट उलट-पुलट हो रहा है। पर छुपाना और भारी लगता है। ठीक है।" } ] },
      { bg: "classroom", chars: [ { id: "anaya", pose: "wave", mood: "determined", x: 0.2 }, { id: "kabir", pose: "stand", mood: "happy", x: 0.5 }, { id: "missji", pose: "stand", mood: "laugh", x: 0.82, flip: true } ], props: [ { id: "book", x: 0.35, y: 0.7 } ],
        say: [ { who: 0, en: "Miss Ji, I took the book. I'm sorry. Here's my painting too.", hi: "मिस जी, किताब मैं ले गई थी। सॉरी। ये मेरी पेंटिंग भी है।" },
               { who: 2, en: "Truth gets a gold star. Late books get library duty!", hi: "सच बोलने पर गोल्ड स्टार। देर से लौटाने पर लाइब्रेरी ड्यूटी!" } ] },
      { bg: "playground", chars: [ { id: "rohan", pose: "stand", mood: "sad", x: 0.2 }, { id: "kabir", pose: "stand", mood: "happy", x: 0.5, flip: true }, { id: "auggie", pose: "lie", mood: "laugh", x: 0.82, flip: true } ],
        cap: { en: "Tiffin break at last! Anaya's painting goes up on the library wall.", hi: "आख़िर टिफ़िन ब्रेक! अनाया की पेंटिंग लाइब्रेरी की दीवार पर लग गई।" },
        say: [ { who: 0, en: "Sorry, Kabir. I blamed you without even looking.", hi: "सॉरी कबीर। मैंने बिना देखे ही तुम पर शक कर लिया।" },
               { who: 2, en: "Case closed! Detective fee: one carrot, please.", hi: "केस बंद! जासूस की फ़ीस: एक गाजर, प्लीज़।" } ],
        fx: { en: "YAY!", hi: "याय!" }, action: true }
    ]
  },

  // 116 — The school play: Kabir the squeaky lion
  {
    id: 116, age: "6-10", category: "school",
    title: { en: "The Squeaky Lion", hi: "चूँ-चूँ वाला शेर" },
    blurb: { en: "Kabir must roar in the school play, but his roar is a squeak. Can Auggie help without stealing the show?", hi: "कबीर को स्कूल के नाटक में दहाड़ना है, पर उसकी दहाड़ तो चूँ-चूँ है। क्या ऑगी बिना शो चुराए मदद कर पाएगा?" },
    moral: { en: "A small voice of your own beats a big borrowed one.", hi: "अपनी छोटी आवाज़ किसी की उधार ली बड़ी आवाज़ से बेहतर है।" },
    cover: { bg: "school", chars: [ { id: "kabir", pose: "blast", mood: "determined", x: 0.3 }, { id: "auggie", pose: "cheer", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "crown", x: 0.3, y: 0.18 }, { id: "star", x: 0.9, y: 0.15 } ], fx: { en: "ROAR!", hi: "दहाड़!" } },
    panels: [
      { bg: "classroom", chars: [ { id: "kabir", pose: "stand", mood: "scared", x: 0.2 }, { id: "auggie", pose: "sit", mood: "happy", x: 0.5 }, { id: "missji", pose: "point", mood: "happy", x: 0.82, flip: true } ],
        cap: { en: "Annual Day is coming! Miss Ji gives out parts for the play 'The Sleepy Lion'.", hi: "एनुअल डे आ रहा है! मिस जी नाटक 'सोता हुआ शेर' के रोल बाँट रही हैं।" },
        say: [ { who: 2, en: "Kabir, you are the Lion. One line: ROAR!", hi: "कबीर, तुम शेर हो। बस एक लाइन: दहाड़!" },
               { who: 0, en: "Me? Roar? My roar is more of a squeak.", hi: "मैं? दहाड़? मेरी दहाड़ तो चूँ-चूँ जैसी है।" } ] },
      { bg: "classroom", chars: [ { id: "auggie", pose: "cheer", mood: "happy", x: 0.3 }, { id: "anaya", pose: "point", mood: "happy", x: 0.72, flip: true } ],
        say: [ { who: 0, en: "Can I be the lion's tail? I have a great tail!", hi: "मैं शेर की पूँछ बन जाऊँ? मेरी पूँछ कमाल की है!" },
               { who: 1, en: "You're Sound Effects, Auggie. Behind the curtain. Quiet till your cue!", hi: "तुम साउंड इफ़ेक्ट हो, ऑगी। पर्दे के पीछे। इशारा मिलने तक चुप!" } ] },
      { bg: "school", chars: [ { id: "kabir", pose: "stand", mood: "scared", x: 0.2 }, { id: "auggie", pose: "blast", mood: "surprised", x: 0.5 }, { id: "rohan", pose: "stand", mood: "laugh", x: 0.82, flip: true } ], props: [ { id: "tree", x: 0.35 } ],
        cap: { en: "Rehearsal. Kabir opens his mouth. Nothing comes out. Auggie helps... early.", hi: "रिहर्सल। कबीर मुँह खोलता है। कुछ नहीं निकलता। ऑगी मदद करता है... ज़रा जल्दी।" },
        say: [ { who: 1, en: "WOOF! I mean ROAR! I mean... oops, the tree.", hi: "भौं! मतलब दहाड़! मतलब... अरे, पेड़ गिर गया।", kind: "shout" },
               { who: 2, en: "The lion's dog just knocked over the whole jungle!", hi: "शेर के कुत्ते ने पूरा जंगल ही गिरा दिया!" } ],
        fx: { en: "WOOF!", hi: "भौं-भौं!" }, action: true },
      { bg: "school", chars: [ { id: "kabir", pose: "sit", mood: "sad", x: 0.28 }, { id: "auggie", pose: "sit", mood: "determined", x: 0.7, flip: true } ],
        say: [ { who: 0, en: "Everyone will laugh at me tomorrow. I'm the squeaky lion.", hi: "कल सब मुझ पर हँसेंगे। मैं चूँ-चूँ वाला शेर हूँ।" },
               { who: 1, en: "Then we practise tonight. Roar at me. I'm a scary carrot.", hi: "तो आज रात प्रैक्टिस। मुझ पर दहाड़ो। मैं डरावनी गाजर हूँ।" } ] },
      { bg: "garden", chars: [ { id: "kabir", pose: "blast", mood: "determined", x: 0.28 }, { id: "auggie", pose: "cheer", mood: "laugh", x: 0.7, flip: true } ],
        cap: { en: "They practise till the streetlights come on. Squeak... squeak... small roar!", hi: "स्ट्रीट लाइट जलने तक प्रैक्टिस चली। चूँ... चूँ... छोटी-सी दहाड़!" },
        say: [ { who: 0, en: "Was that a roar? Did I roar?", hi: "क्या वो दहाड़ थी? मैं दहाड़ा?" },
               { who: 1, en: "That was a roar! A little one. Little roars count!", hi: "वो दहाड़ ही थी! छोटी-सी। छोटी दहाड़ भी गिनती में आती है!" } ],
        fx: { en: "ROAR!", hi: "दहाड़!" }, action: true },
      { bg: "school", chars: [ { id: "kabir", pose: "stand", mood: "scared", x: 0.3 }, { id: "zoya", pose: "stand", mood: "surprised", x: 0.72, flip: true } ], props: [ { id: "star", x: 0.1, y: 0.15 }, { id: "star", x: 0.9, y: 0.2 } ],
        cap: { en: "Show night. Lights! Parents! Kabir's knees knock together. The cue comes...", hi: "शो की रात। लाइटें! मम्मी-पापा! कबीर के घुटने काँप रहे हैं। इशारा आया..." },
        say: [ { who: 0, en: "Roar...", hi: "दहाड़...", kind: "whisper" },
               { who: 1, en: "Louder, Kabir! Nobody heard that!", hi: "ज़ोर से, कबीर! किसी ने नहीं सुना!", kind: "whisper" } ] },
      { bg: "school", chars: [ { id: "auggie", pose: "blast", mood: "determined", x: 0.25 }, { id: "kabir", pose: "stand", mood: "determined", x: 0.68, flip: true } ],
        cap: { en: "From behind the curtain, one gigantic WOOF shakes the whole hall!", hi: "पर्दे के पीछे से एक ज़बरदस्त भौं-भौं ने पूरा हॉल हिला दिया!" },
        say: [ { who: 1, en: "That wasn't me! ...But I'm the lion. Kabir is the lion. ROAR!", hi: "वो मैं नहीं था! ...पर शेर मैं हूँ। कबीर शेर है। दहाड़!", kind: "shout" } ],
        fx: { en: "WOOF!", hi: "भौं-भौं!" }, action: true },
      { bg: "school", chars: [ { id: "missji", pose: "stand", mood: "laugh", x: 0.2 }, { id: "kabir", pose: "cheer", mood: "happy", x: 0.5 }, { id: "auggie", pose: "cheer", mood: "laugh", x: 0.82, flip: true } ],
        cap: { en: "A real roar. Small, wobbly, and all his own. The hall cheers loudest of all!", hi: "एक असली दहाड़। छोटी, काँपती, और पूरी तरह उसकी अपनी। हॉल तालियों से गूँज उठा!" },
        say: [ { who: 0, en: "Best lion ever. And the loudest sound effect in school history.", hi: "अब तक का सबसे अच्छा शेर। और स्कूल के इतिहास का सबसे तेज़ साउंड इफ़ेक्ट।" },
               { who: 1, en: "My roar was little. But it was MINE!", hi: "मेरी दहाड़ छोटी थी। पर वो मेरी थी!" } ] }
    ]
  },

  // ===================== AUGGIE AND OFFICE =====================

  // 117 — Bring Your Dog to Work Day
  {
    id: 117, age: "4-6", category: "office",
    title: { en: "Auggie Goes to Work!", hi: "ऑगी चला ऑफ़िस!" },
    blurb: { en: "It's Bring Your Dog to Work Day! But what job can a big yellow dog actually do?", hi: "आज 'कुत्ते को ऑफ़िस लाओ' डे है! पर एक बड़ा पीला कुत्ता ऑफ़िस में आख़िर करेगा क्या?" },
    moral: { en: "When people are working, wait kindly, and your turn to play will come.", hi: "जब कोई काम कर रहा हो, तो प्यार से इंतज़ार करो, खेलने का टाइम भी आएगा।" },
    cover: { bg: "office", chars: [ { id: "auggie", pose: "sit", mood: "laugh", x: 0.35 }, { id: "papa", pose: "stand", mood: "surprised", x: 0.75, flip: true } ], props: [ { id: "laptop", x: 0.56 }, { id: "bowl", x: 0.12 } ], fx: { en: "SPIN!", hi: "गोल-गोल!" } },
    panels: [
      { bg: "city", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "papa", pose: "stand", mood: "laugh", x: 0.72, flip: true } ],
        cap: { en: "It's Bring Your Dog to Work Day in Chamakpur!", hi: "आज चमकपुर में 'कुत्ते को ऑफ़िस लाओ' डे है!" },
        say: [ { who: 0, en: "I'm going to WORK! Like a real grown-up!", hi: "मैं ऑफ़िस जा रहा हूँ! एकदम बड़े लोगों की तरह!" },
               { who: 1, en: "My new co-worker! Co-WOOF-er! Get it?", hi: "तुम्हें मिलेगा 'पूँछ-ताछ' काउंटर! समझे? पूँछ-ताछ!" } ] },
      { bg: "office", chars: [ { id: "auggie", pose: "point", mood: "happy", x: 0.3 }, { id: "papa", pose: "point", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "bowl", x: 0.52, y: 0.8 } ],
        say: [ { who: 1, en: "Here's your water bowl. And leash on in the corridor!", hi: "ये रहा तुम्हारा पानी का कटोरा। और गलियारे में पट्टा पहनकर चलना!" },
               { who: 0, en: "So many desks! So many smells! Sniff!", hi: "बाप रे! इतनी मेज़ें! इतनी खुशबुएँ! सूँ-सूँ!" } ] },
      { bg: "office", chars: [ { id: "auggie", pose: "sit", mood: "laugh", x: 0.35 }, { id: "papa", pose: "stand", mood: "surprised", x: 0.75, flip: true } ], props: [ { id: "laptop", x: 0.12 } ],
        cap: { en: "Auggie finds Papa's spinny chair. Round and round and round!", hi: "ऑगी को मिल गई पापा की घूमने वाली कुर्सी। गोल-गोल-गोल!" },
        say: [ { who: 0, en: "Work is AMAZING! Wheeee!", hi: "ऑफ़िस तो कमाल है! वूऊऊ!", kind: "shout" } ],
        fx: { en: "SPIN!", hi: "गोल-गोल!" }, action: true },
      { bg: "office", chars: [ { id: "auggie", pose: "sit", mood: "sad", x: 0.3 }, { id: "papa", pose: "stand", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "laptop", x: 0.9 } ],
        cap: { en: "Auggie wants to say hello to EVERYONE. But everyone is typing.", hi: "ऑगी को सबको हेलो बोलना है। पर सब टक-टक टाइप कर रहे हैं।" },
        say: [ { who: 1, en: "Shh, beta. They're thinking. Wait for chai break.", hi: "श्श्श, बेटा। सब सोच रहे हैं। चाय ब्रेक तक रुको।", kind: "whisper" },
               { who: 0, en: "Wait? That's the hardest job in the office!", hi: "रुकना? ये तो ऑफ़िस का सबसे मुश्किल काम है!", kind: "think" } ] },
      { bg: "office", chars: [ { id: "auggie", pose: "lie", mood: "determined", x: 0.3 }, { id: "papa", pose: "sit", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "laptop", x: 0.52 } ],
        cap: { en: "Auggie decides to wait under the desk. Quiet as a sleepy carrot.", hi: "ऑगी ने तय किया, वो मेज़ के नीचे चुपचाप लेटकर रुकेगा। सोई हुई गाजर जितना चुप।" },
        say: [ { who: 1, en: "Good boy. THAT is real office work.", hi: "शाबाश, मेरा राजा बेटा! यही तो असली ऑफ़िस का काम है।", kind: "whisper" } ] },
      { bg: "office", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "papa", pose: "stand", mood: "laugh", x: 0.72, flip: true } ],
        cap: { en: "TING! Chai break! Everyone rushes over to pat Auggie.", hi: "टन-टन! चाय ब्रेक! सब ऑगी को सहलाने दौड़े।" },
        say: [ { who: 1, en: "You're our new Chief Happiness Officer!", hi: "आज से तुम हमारे चीफ़ हैप्पीनेस ऑफ़िसर हो!" },
               { who: 0, en: "Salary: one carrot a day. Deal?", hi: "तनख़्वाह: रोज़ एक गाजर। पक्का?" } ],
        fx: { en: "TING!", hi: "टन-टन!" }, action: true }
    ]
  },

  // 118 — A video call gone wrong
  {
    id: 118, age: "4-6", category: "office",
    title: { en: "Papa, You're on Mute!", hi: "पापा, आप म्यूट पर हो!" },
    blurb: { en: "Papa is talking and talking, but nobody can hear him! Can Auggie save the big meeting?", hi: "पापा बोले जा रहे हैं, पर कोई सुन ही नहीं रहा! क्या ऑगी बड़ी मीटिंग बचा पाएगा?" },
    moral: { en: "Gentle help is the best help: a soft tap beats a big jump.", hi: "धीरे से की गई मदद सबसे अच्छी होती है, छोटा-सा इशारा बड़ी छलांग से बेहतर।" },
    cover: { bg: "office", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "papa", pose: "sit", mood: "surprised", x: 0.74, flip: true } ], props: [ { id: "laptop", x: 0.52 } ], fx: { en: "OOPS!", hi: "उफ़्फ़!" } },
    panels: [
      { bg: "office", chars: [ { id: "papa", pose: "sit", mood: "determined", x: 0.28 }, { id: "auggie", pose: "sit", mood: "happy", x: 0.74, flip: true } ], props: [ { id: "laptop", x: 0.5 } ],
        say: [ { who: 0, en: "Big video call! Quiet as a mouse, okay?", hi: "बड़ी वीडियो कॉल है! चूहे जितना चुप, ठीक है?" },
               { who: 1, en: "Quieter! I'll be a sleeping mouse!", hi: "चूहे से भी चुप! सोए हुए चूहे जितना!" } ] },
      { bg: "office", chars: [ { id: "papa", pose: "blast", mood: "laugh", x: 0.28 }, { id: "auggie", pose: "think", mood: "surprised", x: 0.74, flip: true } ], props: [ { id: "laptop", x: 0.5 } ],
        cap: { en: "Papa talks and talks. The screen-people wave their arms like crazy.", hi: "पापा बोलते गए, बोलते गए। स्क्रीन वाले लोग ज़ोर-ज़ोर से हाथ हिलाते रहे।" },
        say: [ { who: 1, en: "Uh-oh. Papa's on MUTE! Nobody can hear him!", hi: "ओ हो! पापा तो म्यूट पर हैं! कोई सुन ही नहीं रहा!", kind: "think" } ] },
      { bg: "office", chars: [ { id: "auggie", pose: "cheer", mood: "determined", x: 0.35 }, { id: "papa", pose: "sit", mood: "surprised", x: 0.77, flip: true } ], props: [ { id: "laptop", x: 0.56 } ],
        cap: { en: "Auggie jumps up to press the button... with ALL his paws!", hi: "ऑगी बटन दबाने के लिए कूदा... चारों पंजों के साथ!" },
        say: [ { who: 0, en: "Don't worry, Papa! I'll fix it!", hi: "फ़िक्र मत करो पापा! मैं हूँ ना!", kind: "shout" } ],
        fx: { en: "BOING!", hi: "धम्म!" }, action: true },
      { bg: "office", chars: [ { id: "auggie", pose: "point", mood: "laugh", x: 0.3 }, { id: "papa", pose: "stand", mood: "surprised", x: 0.74, flip: true } ], props: [ { id: "laptop", x: 0.5 } ],
        cap: { en: "Now everyone can hear. And see one GIANT wet nose!", hi: "अब सबको सुनाई दे रहा है। और दिख रही है एक बड़ी-सी गीली नाक!" },
        say: [ { who: 0, en: "Hello, screen-people! Sniff sniff! Nice to meet you!", hi: "नमस्ते स्क्रीन वालो! सूँ-सूँ! आपसे मिलकर बड़ी खुशी हुई!" },
               { who: 1, en: "Auggie! That's your nose, not my slides!", hi: "अरे ऑगी! ये तुम्हारी नाक है, मेरी स्लाइड नहीं!", kind: "shout" } ],
        fx: { en: "SNIFF!", hi: "सूँ-सूँ!" }, action: true },
      { bg: "office", chars: [ { id: "auggie", pose: "wave", mood: "determined", x: 0.3 }, { id: "papa", pose: "sit", mood: "surprised", x: 0.72, flip: true } ],
        cap: { en: "Ten minutes later, Papa is on mute AGAIN! This time, Auggie thinks first.", hi: "दस मिनट बाद पापा फिर म्यूट पर! इस बार ऑगी ने कूदने से पहले सोचा।" },
        say: [ { who: 0, en: "Tap-tap. Papa... the button. Mute!", hi: "टुक-टुक। पापा... बटन। म्यूट!", kind: "whisper" },
               { who: 1, en: "Oh! I'm on mute? Thank you, partner!", hi: "अरे! मैं म्यूट पर था? थैंक यू, पार्टनर!" } ] },
      { bg: "office", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "papa", pose: "stand", mood: "laugh", x: 0.72, flip: true } ],
        cap: { en: "Meeting over! The whole team wants Auggie at every call.", hi: "मीटिंग खत्म! पूरी टीम कहती है, हर कॉल में ऑगी चाहिए!" },
        say: [ { who: 1, en: "You're not just my dog. You're my PAW-tner!", hi: "तुम तो मेरे सबसे बढ़िया पंजा-पार्टनर हो!" },
               { who: 0, en: "Next meeting, put carrots on the agenda!", hi: "अगली मीटिंग में गाजर पर भी बात होगी ना?" } ],
        fx: { en: "YAY!", hi: "याय!" }, action: true }
    ]
  },

  // 119 — The office lunch that must not be shared
  {
    id: 119, age: "4-6", category: "office",
    title: { en: "Guard the Tiffin, Auggie!", hi: "टिफ़िन का चौकीदार ऑगी" },
    blurb: { en: "Papa's tiffin smells of rajma, and Auggie promised to guard it. Will his nose keep the promise too?", hi: "पापा के टिफ़िन से राजमा की खुशबू आ रही है, और ऑगी ने पहरा देने का वादा किया है। पर क्या उसकी नाक भी वादा निभाएगी?" },
    moral: { en: "A promise kept feels even better than a full tummy.", hi: "निभाया हुआ वादा भरे पेट से भी ज़्यादा अच्छा लगता है।" },
    cover: { bg: "office", chars: [ { id: "auggie", pose: "lie", mood: "determined", x: 0.35 }, { id: "papa", pose: "stand", mood: "laugh", x: 0.75, flip: true } ], props: [ { id: "apple", x: 0.12 } ], fx: { en: "SNIFF!", hi: "सूँ-सूँ!" } },
    panels: [
      { bg: "home", chars: [ { id: "mumma", pose: "stand", mood: "laugh", x: 0.3 }, { id: "auggie", pose: "wave", mood: "happy", x: 0.72, flip: true } ],
        cap: { en: "Mumma packs Papa's lunch. Rajma-chawal! And a very long list.", hi: "मम्मा ने पापा का टिफ़िन पैक किया। राजमा-चावल! और साथ में लंबी-सी लिस्ट।" },
        say: [ { who: 0, en: "Auggie, guard Mittsy's tiffin at the office. Promise?", hi: "ऑगी, ऑफ़िस में मिट्सी के टिफ़िन का ध्यान रखना। वादा?" },
               { who: 1, en: "Paw promise, Mumma! Pinky-paw promise!", hi: "पक्का वादा, मम्मा! पंजा-प्रॉमिस!" } ] },
      { bg: "office", chars: [ { id: "auggie", pose: "sit", mood: "determined", x: 0.3 }, { id: "papa", pose: "stand", mood: "happy", x: 0.72, flip: true } ],
        cap: { en: "Papa goes into a long meeting. The tiffin stays with Auggie.", hi: "पापा लंबी मीटिंग में चले गए। टिफ़िन रह गया ऑगी के पास।" },
        say: [ { who: 1, en: "Back in one hour, Guard Auggie!", hi: "एक घंटे में आता हूँ, चौकीदार साहब!" },
               { who: 0, en: "Guarding is easy. I'm a professional!", hi: "पहरा देना तो बाएँ पंजे का खेल है!" } ] },
      { bg: "office", chars: [ { id: "auggie", pose: "point", mood: "surprised", x: 0.4 } ],
        cap: { en: "Ten minutes later... the smell of rajma tickles his nose.", hi: "दस मिनट बाद... राजमा की खुशबू नाक में गुदगुदी करने लगी।" },
        say: [ { who: 0, en: "Just one sniff. Sniffs don't count... right?", hi: "बस एक बार सूँघ लूँ? सूँघना तो गिनती में नहीं आता... है ना?", kind: "think" } ],
        fx: { en: "SNIFF!", hi: "सूँ-सूँ!" }, action: true },
      { bg: "office", chars: [ { id: "auggie", pose: "cheer", mood: "scared", x: 0.4 } ],
        cap: { en: "One small sniff becomes a BIG sniff. The lid goes POP!", hi: "छोटी-सी सूँ बन गई बड़ी वाली सूँ-सूँ। और ढक्कन खुल गया!" },
        say: [ { who: 0, en: "NO, nose! We PROMISED Mumma!", hi: "ना, नाक, ना! हमने मम्मा से वादा किया है!", kind: "shout" } ],
        fx: { en: "POP!", hi: "पॉप!" }, action: true },
      { bg: "office", chars: [ { id: "auggie", pose: "lie", mood: "determined", x: 0.4 } ],
        cap: { en: "Auggie shuts the lid, turns around, and squeezes his eyes shut.", hi: "ऑगी ने ढक्कन बंद किया, मुँह फेरा, और आँखें कसकर मींच लीं।" },
        say: [ { who: 0, en: "Think of carrots. Carrot, carrot, carrot, carrot...", hi: "गाजर के बारे में सोचो। गाजर, गाजर, गाजर, गाजर...", kind: "think" } ] },
      { bg: "office", chars: [ { id: "papa", pose: "stand", mood: "laugh", x: 0.3 }, { id: "auggie", pose: "cheer", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "apple", x: 0.51, y: 0.7 } ],
        cap: { en: "Papa is back! Under the rajma, Mumma hid a surprise box.", hi: "पापा लौट आए! राजमा के नीचे मम्मा ने छुपाया था एक सरप्राइज़ डिब्बा।" },
        say: [ { who: 0, en: "Onions in rajma aren't for dogs. These apples are yours!", hi: "राजमा में प्याज़ है, वो कुत्तों के लिए नहीं। ये सेब तुम्हारे हैं!" },
               { who: 1, en: "Promise kept AND apples? Best day ever!", hi: "वादा भी निभाया और सेब भी मिले? मज़ा आ गया!" } ] }
    ]
  },

  // 120 — The office colleague who is scared of dogs (Billo Ji, the office cat)
  {
    id: 120, age: "6-10", category: "office",
    title: { en: "Billo Ji Does Not Like Dogs", hi: "बिल्लो जी को कुत्ते नहीं भाते" },
    blurb: { en: "The office's oldest employee is a cat who is terrified of dogs. Can Auggie make a friend without scaring her up the bookshelf?", hi: "ऑफ़िस की सबसे पुरानी कर्मचारी है एक बिल्ली, जिसे कुत्तों से बहुत डर लगता है। क्या ऑगी उसे डराए बिना दोस्त बना पाएगा?" },
    moral: { en: "Some friends need time, so go at their speed and let them come to you.", hi: "कुछ दोस्तों को वक़्त चाहिए, उनकी रफ़्तार से चलो और उन्हें खुद पास आने दो।" },
    cover: { bg: "office", chars: [ { id: "auggie", pose: "lie", mood: "happy", x: 0.35 }, { id: "cat", pose: "sit", mood: "happy", x: 0.74, flip: true } ], props: [ { id: "laptop", x: 0.12 } ], fx: { en: "PURR!", hi: "घुर्र-घुर्र!" } },
    panels: [
      { bg: "office", chars: [ { id: "auggie", pose: "stand", mood: "happy", x: 0.2 }, { id: "papa", pose: "stand", mood: "happy", x: 0.5 }, { id: "cat", pose: "stand", mood: "scared", x: 0.8, flip: true } ],
        cap: { en: "Papa's office has one very senior employee: Billo Ji the cat, Boss of the Sunny Window.", hi: "पापा के ऑफ़िस में एक बड़ी अफ़सर हैं: बिल्लो जी, धूप वाली खिड़की की मालकिन।" },
        say: [ { who: 0, en: "Hello! I'm Auggie! Want to be best friends?", hi: "हेलो! मैं ऑगी! मेरी बेस्ट फ़्रेंड बनोगी?" },
               { who: 2, en: "A DOG?! In MY office?!", hi: "कुत्ता?! मेरे ऑफ़िस में?! हाय राम!", kind: "shout" } ],
        fx: { en: "HISS!", hi: "फ़्स्स!" }, action: true },
      { bg: "office", chars: [ { id: "auggie", pose: "sit", mood: "sad", x: 0.3 }, { id: "papa", pose: "sit", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "laptop", x: 0.52 } ],
        cap: { en: "Billo Ji shoots up the bookshelf and glares down from the very top.", hi: "बिल्लो जी फ़ुर्र से अलमारी पर चढ़ गईं और ऊपर से घूरने लगीं।" },
        say: [ { who: 0, en: "Why is she scared? I'm soft! I'm basically a cushion with legs!", hi: "वो डर क्यों गई? मैं तो नरम-नरम हूँ! चलता-फिरता तकिया!" },
               { who: 1, en: "Some friendships take time, beta. You can't rush a cat.", hi: "कुछ दोस्ती में वक़्त लगता है, बेटा। बिल्ली के साथ जल्दबाज़ी नहीं चलती।" } ] },
      { bg: "office", chars: [ { id: "auggie", pose: "blast", mood: "laugh", x: 0.3 }, { id: "cat", pose: "stand", mood: "scared", x: 0.72, flip: true } ],
        cap: { en: "Try one: the doggy hello. Zoomies, a giant wag and a happy bark!", hi: "पहली कोशिश: कुत्ते वाला हेलो। भागा-दौड़ी, पूँछ-हिलाई और ज़ोर की भौं!" },
        say: [ { who: 0, en: "HELLO, BILLO JI! LET'S PLAY!", hi: "हेलो बिल्लो जी! चलो खेलें!", kind: "shout" },
               { who: 1, en: "Too LOUD! My whiskers are shaking!", hi: "बाप रे, कितना शोर! मेरी मूँछें काँप रही हैं!" } ],
        fx: { en: "WOOF!", hi: "भौं-भौं!" }, action: true },
      { bg: "office", chars: [ { id: "auggie", pose: "wave", mood: "happy", x: 0.3 }, { id: "cat", pose: "sit", mood: "angry", x: 0.72, flip: true } ], props: [ { id: "ball", x: 0.51, y: 0.8 } ],
        cap: { en: "Try two: a gift. Auggie's very best, very slobbery ball.", hi: "दूसरी कोशिश: तोहफ़ा। ऑगी की सबसे प्यारी, सबसे गीली गेंद।" },
        say: [ { who: 0, en: "It's only a little bit wet. That's the best part!", hi: "बस थोड़ी-सी गीली है। यही तो इसकी खासियत है!" },
               { who: 1, en: "Ew. Ew. EW. Take it back to Dog Land.", hi: "छी-छी-छी! ले जाओ इसे वापस, कुत्तों की दुनिया में!" } ] },
      { bg: "office", chars: [ { id: "auggie", pose: "sit", mood: "sad", x: 0.3 }, { id: "mausi", pose: "stand", mood: "happy", x: 0.72, flip: true } ],
        cap: { en: "At lunch, Mausi drops by. Auggie is too sad to even beg for her sandwich.", hi: "लंच में मौसी मिलने आईं। ऑगी इतना उदास था कि उसने सैंडविच तक नहीं माँगा।" },
        say: [ { who: 0, en: "Mausi, I tried everything. I need help. Cat help.", hi: "मौसी, मैंने सब करके देख लिया। मुझे मदद चाहिए। बिल्ली वाली मदद।" },
               { who: 1, en: "Cats like calm. Go slow, go low, look away, and wait.", hi: "बिल्लियों को शांति पसंद है। धीरे चलो, नीचे बैठो, नज़र हटाओ, और रुको।" } ] },
      { bg: "office", chars: [ { id: "auggie", pose: "lie", mood: "determined", x: 0.3 }, { id: "cat", pose: "sit", mood: "surprised", x: 0.72, flip: true } ],
        cap: { en: "So Auggie lies flat by the sunny window. He looks away. He waits. And waits.", hi: "ऑगी धूप वाली खिड़की के पास चुपचाप लेट गया। नज़र फेर ली। और इंतज़ार... इंतज़ार..." },
        say: [ { who: 0, en: "Don't wag. Don't wag. Tail, I said DON'T WAG!", hi: "पूँछ, मत हिल। मत हिल। अरे, बोला ना, मत हिल!", kind: "think" },
               { who: 1, en: "Hmm. The big one is... quiet today.", hi: "हम्म। ये बड़ा वाला आज... चुप है।", kind: "whisper" } ] },
      { bg: "office", chars: [ { id: "cat", pose: "point", mood: "happy", x: 0.3 }, { id: "auggie", pose: "lie", mood: "happy", x: 0.72, flip: true } ],
        cap: { en: "Paw by paw, Billo Ji creeps closer. Sniff. Sniff. Then she curls up against Auggie.", hi: "दबे पाँव बिल्लो जी पास आईं। सूँ... सूँ... और फिर ऑगी से सटकर गोल होकर बैठ गईं।" },
        say: [ { who: 0, en: "You're warm. Like a sunny window with ears.", hi: "तुम तो गरम-गरम हो। कानों वाली धूप की खिड़की!" },
               { who: 1, en: "Going slow was my hardest trick ever. And my best.", hi: "धीरे चलना मेरा सबसे मुश्किल करतब था। और सबसे बढ़िया भी।", kind: "whisper" } ],
        fx: { en: "PURR!", hi: "घुर्र-घुर्र!" }, action: true },
      { bg: "office", chars: [ { id: "mausi", pose: "stand", mood: "laugh", x: 0.2 }, { id: "auggie", pose: "lie", mood: "happy", x: 0.5 }, { id: "cat", pose: "lie", mood: "happy", x: 0.8, flip: true } ],
        cap: { en: "Chai break. Two colleagues snooze in the sun: one big and golden, one small and fussy.", hi: "चाय ब्रेक। धूप में दो साथी ऊँघ रहे हैं: एक बड़ा और सुनहरा, एक छोटी और नखरीली।" },
        say: [ { who: 0, en: "Hold that pose! Office selfie of the year!", hi: "बस, ऐसे ही रुको! साल की सबसे बढ़िया ऑफ़िस सेल्फ़ी!" },
               { who: 2, en: "Tell no one I like this dog. ...Okay, tell everyone.", hi: "किसी को मत बताना कि ये कुत्ता मुझे पसंद है। ...अच्छा, सबको बता दो।" } ] }
    ]
  },

  // 121 — The paper-shredder mishap
  {
    id: 121, age: "6-10", category: "office",
    title: { en: "Auggie and the Paper Muncher", hi: "ऑगी और कागज़-खाऊ मशीन" },
    blurb: { en: "Papa's big presentation is at three. The shredder is hungry. And guess who's in charge of feeding it...", hi: "पापा की बड़ी प्रेज़ेंटेशन तीन बजे है। श्रेडर मशीन को ज़ोर की भूख लगी है। और उसे खिलाने की ड्यूटी... ऑगी की!" },
    moral: { en: "Owning up quickly turns a big mess into a small fix.", hi: "गलती झट से मान लो, तो बड़ी गड़बड़ भी छोटी-सी रह जाती है।" },
    cover: { bg: "office", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "papa", pose: "stand", mood: "surprised", x: 0.74, flip: true } ], props: [ { id: "machine", x: 0.52 } ], fx: { en: "BRRRR!", hi: "घर्र्र!" } },
    panels: [
      { bg: "office", chars: [ { id: "papa", pose: "blast", mood: "laugh", x: 0.3 }, { id: "auggie", pose: "sit", mood: "happy", x: 0.72, flip: true } ], props: [ { id: "machine", x: 0.1 } ],
        cap: { en: "Papa's big presentation is at three. He printed it just before the printer jammed. Again.", hi: "पापा की बड़ी प्रेज़ेंटेशन तीन बजे है। कागज़ छप गए, और फिर... प्रिंटर महाराज फिर से अटक गए!" },
        say: [ { who: 0, en: "Phew! Safe in the red tray. Printer, you can sulk now.", hi: "शुक्र है! लाल ट्रे में रख दी। अब प्रिंटर, तू जितना चाहे रूठ।" },
               { who: 1, en: "Maybe the printer needs a nap. Naps fix everything.", hi: "शायद प्रिंटर को झपकी चाहिए। झपकी से सब ठीक हो जाता है।" } ] },
      { bg: "office", chars: [ { id: "papa", pose: "point", mood: "happy", x: 0.28 }, { id: "auggie", pose: "cheer", mood: "determined", x: 0.74, flip: true } ], props: [ { id: "machine", x: 0.5 } ],
        say: [ { who: 0, en: "Your job: old papers from the GREEN tray go in the shredder.", hi: "तुम्हारी ड्यूटी: हरी ट्रे के पुराने कागज़ श्रेडर में डालो। सिर्फ़ हरी वाली!" },
               { who: 1, en: "Shredder Chief Auggie, reporting for duty! Salary in carrots, please.", hi: "श्रेडर चीफ़ ऑगी हाज़िर है! तनख़्वाह गाजर में चाहिए।" } ] },
      { bg: "office", chars: [ { id: "auggie", pose: "blast", mood: "laugh", x: 0.3 } ], props: [ { id: "machine", x: 0.62 } ],
        cap: { en: "The shredder munches and crunches. Auggie feeds it. And feeds it. From the RED tray.", hi: "श्रेडर कुतर-कुतर खाता गया। ऑगी खिलाता गया, खिलाता गया। लाल ट्रे से!" },
        say: [ { who: 0, en: "Eat up, Mr Shredder! You eat even faster than me!", hi: "खाओ-खाओ, श्रेडर जी! तुम तो मुझसे भी तेज़ खाते हो!" } ],
        fx: { en: "BRRRR!", hi: "घर्र्र!" }, action: true },
      { bg: "office", chars: [ { id: "auggie", pose: "think", mood: "scared", x: 0.45 } ], props: [ { id: "machine", x: 0.12 } ],
        cap: { en: "Then Auggie spots a paper strip with Papa's big chart on it. Uh-oh.", hi: "तभी ऑगी को एक पट्टी पर पापा का बड़ा चार्ट दिखा। ओ हो!" },
        say: [ { who: 0, en: "Red tray, green tray... to me they look the SAME!", hi: "लाल ट्रे, हरी ट्रे... मुझे तो दोनों एक जैसी दिखती हैं!", kind: "think" },
               { who: 0, en: "I could hide it all under the rug. Nobody would know...", hi: "सारे कागज़ दरी के नीचे छुपा दूँ? किसी को पता भी नहीं चलेगा...", kind: "think" } ] },
      { bg: "office", chars: [ { id: "auggie", pose: "sit", mood: "sad", x: 0.3 }, { id: "papa", pose: "stand", mood: "surprised", x: 0.72, flip: true } ],
        cap: { en: "But hiding feels heavy. Auggie pads straight to Papa, tail down low.", hi: "पर छुपाने से दिल भारी हो गया। ऑगी पूँछ नीचे किए सीधा पापा के पास गया।" },
        say: [ { who: 0, en: "Papa... I fed your presentation to the shredder. I'm really sorry.", hi: "पापा... मैंने आपकी प्रेज़ेंटेशन श्रेडर को खिला दी। सच्ची-मुच्ची सॉरी।" },
               { who: 1, en: "Dogs can't tell red from green! My mistake too. Thanks for telling me fast.", hi: "अरे, कुत्तों को लाल-हरा एक जैसा दिखता है! गलती मेरी भी है। जल्दी बताया, शाबाश।" } ] },
      { bg: "office", chars: [ { id: "papa", pose: "blast", mood: "determined", x: 0.28 }, { id: "auggie", pose: "point", mood: "surprised", x: 0.74, flip: true } ], props: [ { id: "machine", x: 0.51 } ],
        cap: { en: "But the grumpy printer still won't print. Then Auggie's Super Sniffer twitches...", hi: "पर रूठा प्रिंटर अब भी नहीं चल रहा। तभी ऑगी की सुपर नाक फड़की..." },
        say: [ { who: 1, en: "Wait! That printer smells like... MY carrot from last Tuesday!", hi: "रुको! इस प्रिंटर में से मेरी पिछले मंगलवार वाली गाजर की खुशबू आ रही है!" },
               { who: 0, en: "A carrot? In my PRINTER?", hi: "गाजर? मेरे प्रिंटर में?!", kind: "shout" } ],
        fx: { en: "SNIFF!", hi: "सूँ-सूँ!" }, action: true },
      { bg: "office", chars: [ { id: "papa", pose: "cheer", mood: "laugh", x: 0.28 }, { id: "auggie", pose: "sit", mood: "happy", x: 0.74, flip: true } ], props: [ { id: "machine", x: 0.51 } ],
        cap: { en: "Out pops the carrot. The printer whirs back to life. Fresh copies at 2:59!", hi: "गाजर बाहर निकली और प्रिंटर फिर चल पड़ा। नई कॉपियाँ ठीक 2:59 पर!" },
        say: [ { who: 0, en: "So THAT's why it's been grumpy all week!", hi: "तो इसीलिए ये पूरे हफ़्ते से मुँह फुलाए बैठा था!" },
               { who: 1, en: "I wasn't hiding it. I was saving it. For later.", hi: "मैंने छुपाई नहीं थी। संभालकर रखी थी। बाद के लिए।" } ],
        fx: { en: "WHIRR!", hi: "खट-खट!" }, action: true },
      { bg: "office", chars: [ { id: "papa", pose: "stand", mood: "laugh", x: 0.3 }, { id: "auggie", pose: "cheer", mood: "laugh", x: 0.72, flip: true } ], props: [ { id: "star", x: 0.15, y: 0.15 }, { id: "star", x: 0.85, y: 0.12 } ],
        cap: { en: "The presentation is a hit! And the shredded strips make perfect party confetti.", hi: "प्रेज़ेंटेशन सुपरहिट! और कतरे हुए कागज़ बन गए पार्टी की रंग-बिरंगी बारिश।" },
        say: [ { who: 0, en: "The shredder loved your work, Auggie. It said it was paper-fect!", hi: "पता है श्रेडर को कौन-से बादाम पसंद हैं? कागज़ी बादाम!" },
               { who: 1, en: "Ha-ha! Terrible! ...Say it again!", hi: "हा-हा! कितना बेकार जोक! ...फिर से सुनाओ!" } ] }
    ]
  },

  // 122 — Auggie's business idea: a carrot company
  {
    id: 122, age: "6-10", category: "office",
    title: { en: "Auggie's Crunchy Carrot Company", hi: "ऑगी की करारी गाजर कंपनी" },
    blurb: { en: "Auggie starts his very own carrot company. There's just one problem: the boss keeps eating the stock!", hi: "ऑगी ने अपनी खुद की गाजर कंपनी खोली है। बस एक दिक्कत है: बॉस खुद ही सारा माल चट कर जाता है!" },
    moral: { en: "A good business, like a good friend, thinks about what others need.", hi: "अच्छा काम वही, जिसमें दूसरों की ज़रूरत का ध्यान हो, बिल्कुल अच्छे दोस्त की तरह।" },
    cover: { bg: "cafe", chars: [ { id: "auggie", pose: "cheer", mood: "laugh", x: 0.3 }, { id: "mausi", pose: "stand", mood: "laugh", x: 0.74, flip: true } ], props: [ { id: "camera", x: 0.52, y: 0.45 } ], fx: { en: "CRUNCH!", hi: "कुर्र-कुर्र!" } },
    panels: [
      { bg: "office", chars: [ { id: "papa", pose: "sit", mood: "happy", x: 0.28 }, { id: "auggie", pose: "cheer", mood: "laugh", x: 0.74, flip: true } ], props: [ { id: "laptop", x: 0.5 } ],
        cap: { en: "Papa is practising his pitch for a big new project. Auggie listens very carefully.", hi: "पापा नए प्रोजेक्ट की पिच की प्रैक्टिस कर रहे हैं। ऑगी कान खड़े करके सुन रहा है।" },
        say: [ { who: 0, en: "Every business needs three things: a plan, a product, and patience.", hi: "हर बिज़नेस को तीन चीज़ें चाहिए: प्लान, प्रोडक्ट, और सब्र।" },
               { who: 1, en: "Business idea! Plan: carrots. Product: carrots. Patience: what's that?", hi: "मेरे पास भी आइडिया है! प्लान: गाजर। प्रोडक्ट: गाजर! सब्र: वो क्या होता है?" } ] },
      { bg: "home", chars: [ { id: "mumma", pose: "stand", mood: "laugh", x: 0.3 }, { id: "auggie", pose: "sit", mood: "surprised", x: 0.72, flip: true } ],
        cap: { en: "Mumma writes the business plan. It's a list, of course. Her laugh echoes three houses away.", hi: "मम्मा ने बिज़नेस प्लान लिखा। ज़ाहिर है, लिस्ट बनाकर। और हँसी? तीन घर दूर तक!" },
        say: [ { who: 0, en: "One: buy carrots. Two: wash carrots. Three: DO NOT EAT the carrots!", hi: "एक: गाजर खरीदो। दो: गाजर धोओ। तीन: गाजर खुद मत खाओ!" },
               { who: 1, en: "Rule three sounds very strict. Can we vote on it?", hi: "तीसरा नियम तो बड़ा सख़्त है। उस पर वोटिंग कर लें?" } ] },
      { bg: "cafe", chars: [ { id: "auggie", pose: "sit", mood: "happy", x: 0.3 }, { id: "mausi", pose: "stand", mood: "laugh", x: 0.74, flip: true } ], props: [ { id: "camera", x: 0.54, y: 0.45 } ],
        cap: { en: "Next morning, 'Auggie's Crunchy Carrots' opens outside the café next to Papa's office.", hi: "अगली सुबह पापा के ऑफ़िस के बगल वाले कैफ़े के बाहर खुली दुकान: 'ऑगी की करारी गाजर'।" },
        say: [ { who: 1, en: "Hold that pose! Every company needs a founder photo!", hi: "बस, ऐसे ही रुको! हर कंपनी के मालिक की फ़ोटो तो बनती है!" },
               { who: 0, en: "Get my good side. Actually, both sides are good.", hi: "मेरी अच्छी साइड से लेना। वैसे दोनों ही साइड अच्छी हैं।" } ] },
      { bg: "cafe", chars: [ { id: "auggie", pose: "lie", mood: "surprised", x: 0.3 }, { id: "mausi", pose: "stand", mood: "surprised", x: 0.72, flip: true } ], props: [ { id: "carrot", x: 0.52 } ],
        cap: { en: "By eleven o'clock, the boss has 'quality-tested' nineteen carrots. One is left.", hi: "ग्यारह बजे तक बॉस ने उन्नीस गाजरें 'चखकर जाँच' लीं। बची बस एक।" },
        say: [ { who: 1, en: "Auggie! You ate the whole shop!", hi: "ऑगी! तू तो पूरी दुकान ही चट कर गया!", kind: "shout" },
               { who: 0, en: "Every carrot had to be checked. I'm a very careful boss.", hi: "हर गाजर जाँचनी पड़ती है ना। मैं बहुत ध्यान रखने वाला बॉस हूँ।" } ],
        fx: { en: "CRUNCH!", hi: "कुर्र-कुर्र!" }, action: true },
      { bg: "office", chars: [ { id: "auggie", pose: "sit", mood: "sad", x: 0.3 }, { id: "papa", pose: "sit", mood: "happy", x: 0.72, flip: true } ],
        cap: { en: "No carrots. No customers. Just one very full, very sad businessman.", hi: "ना गाजर, ना ग्राहक। बस एक पेट-भरा, मुँह-लटका बिज़नेसमैन।" },
        say: [ { who: 0, en: "Papa, I'm a terrible boss. I only thought about my tummy.", hi: "पापा, मैं बहुत बुरा बॉस हूँ। मैंने बस अपने पेट के बारे में सोचा।" },
               { who: 1, en: "Then think like a customer, beta. What do people here need?", hi: "तो ग्राहक बनकर सोचो, बेटा। यहाँ लोगों को क्या चाहिए?" } ] },
      { bg: "office", chars: [ { id: "auggie", pose: "point", mood: "determined", x: 0.3 }, { id: "papa", pose: "stand", mood: "surprised", x: 0.72, flip: true } ],
        cap: { en: "Auggie sniffs the office. Chai, biscuits, and lots of big, sleepy, four o'clock yawns.", hi: "ऑगी ने पूरा ऑफ़िस सूँघा। चाय, बिस्कुट, और चार बजे वाली लंबी-लंबी उबासियाँ।" },
        say: [ { who: 0, en: "They need a crunchy snack that wakes them up! With a free wag!", hi: "इन्हें चाहिए करारा नाश्ता, जो नींद भगा दे! साथ में पूँछ-हिलाई फ़्री!" },
               { who: 1, en: "Now THAT is a business idea!", hi: "हाँ! ये हुई ना बिज़नेस वाली बात!" } ],
        fx: { en: "SNIFF!", hi: "सूँ-सूँ!" }, action: true },
      { bg: "office", chars: [ { id: "auggie", pose: "stand", mood: "determined", x: 0.3 }, { id: "mumma", pose: "stand", mood: "laugh", x: 0.72, flip: true } ],
        cap: { en: "Chai break! Mumma brings fresh carrot sticks. Auggie serves them. Price: one head-scratch each.", hi: "चाय ब्रेक! मम्मा ताज़ी गाजर लाईं, ऑगी बाँट रहा है। कीमत: एक बार सिर सहलाना।" },
        say: [ { who: 0, en: "Customers first. Customers first. My tummy can wait. ...Probably.", hi: "पहले ग्राहक। पहले ग्राहक। पेट रुक सकता है। ...शायद।", kind: "think" },
               { who: 1, en: "Sold out in five minutes! Ha-ha-HA!", hi: "पाँच मिनट में सब बिक गया! हा-हा-हा!", kind: "shout" } ],
        fx: { en: "SOLD OUT!", hi: "सब बिक गया!" }, action: true },
      { bg: "office", chars: [ { id: "papa", pose: "stand", mood: "laugh", x: 0.22 }, { id: "auggie", pose: "wave", mood: "happy", x: 0.5, flip: true }, { id: "mausi", pose: "stand", mood: "laugh", x: 0.8, flip: true } ],
        cap: { en: "At the end of the day, one carrot is left. The boss saved it on purpose.", hi: "शाम तक एक गाजर बची। बॉस ने जान-बूझकर बचाई थी।" },
        say: [ { who: 1, en: "For my very first customer. Papa, you believed in Carrot Company!", hi: "ये मेरे सबसे पहले ग्राहक के लिए। पापा, आपने गाजर कंपनी पर भरोसा किया!" },
               { who: 0, en: "Thanks, boss! You really got to the ROOT of business!", hi: "थैंक यू, बॉस! गाजर भी जड़ है, और तुम भी बिज़नेस की जड़ तक पहुँच गए!" } ] }
    ]
  }
);
